# Connect to DB

In [1]:
import datetime
import pandas as pd
import numpy as np
import pyodbc
import tqdm

In [6]:
SERVER = '20.203.36.211'
DATABASE = 'MACDB'
USERNAME = 'ammar.a'
PASSWORD = 'P3tr0m!n'

In [87]:
SERVER = '20.203.36.211'
DATABASE = 'MACDB'
USERNAME = 'to.mckinsey'
PASSWORD = 'Petromin@1'

In [88]:
connectionString = f'DRIVER={{ODBC Driver 18 for SQL Server}};SERVER={SERVER};DATABASE={DATABASE};UID={USERNAME};PWD={PASSWORD};TrustServerCertificate=yes;'

In [89]:
conn = pyodbc.connect(connectionString)

In [9]:
cursor = conn.cursor()
cursor.execute("""
SELECT 
   TOP 1 *
  FROM MACDB.dbo.v_Invoice
""")
rows = cursor.fetchall()

In [10]:
rows

[('B307C673-1C94-49E1-B0B1-01000007C7D0', 'M-1480-8697', datetime.datetime(2023, 1, 7, 23, 40, 33), '79719D5F-191D-44C3-9442-7D940CE07006', '95E5858B-C616-4857-BE1F-F7D262CB4D48', '95E5858B-C616-4857-BE1F-F7D262CB4D48', '0604754A-496B-4534-B5A5-C959C335B486', '80AC933C-EF5D-4E70-ABB3-1BD818F6A96C', datetime.datetime(2023, 1, 7, 19, 41, 21), datetime.datetime(2023, 1, 7, 19, 41, 21), Decimal('161.7391'), Decimal('35.6522'), Decimal('126.0870'), Decimal('18.9130'), Decimal('145.0000'), Decimal('49.263200000'), 0, 0, None, 'None', '1480-8770', datetime.datetime(2023, 1, 7, 19, 13), datetime.datetime(2023, 1, 7, 19, 41, 21), 59395, 54242, datetime.datetime(2022, 11, 24, 19, 15, 57), 'Existing Customer', 0, 0, 1, None, None, 'Cash', 'PE Service')]

In [11]:
cursor = conn.cursor()
cursor.execute("""
SELECT
   InvoiceID, InvoiceNumber, a.ModifiedOn, a.BranchID,
       TransCustomerID, a.CustomerID, CustomerVehicleID, SystemUserID,
       InvoiceDate, InvoiceDueDate, InvoiceBeforeDiscountAmount,
       InvoiceDiscountAmount, InvoiceBeforeTaxAmount, InvoiceTaxAmount,
       InvoiceTotalAmount, InvoiceItemCost, IsFleet, IsPMS,
       CustomerContractID, CustomerContractType, WorkOrderNumber,
       WorkOrderStartDate, WorkOrderEndDate, WorkOrderMileage,
       PreviousMileage, PreviousVisitDate, NewOrExistingCustomer,
       NewCustomer, NewVehicle, Warranty, PMSID, PMSName,
       InvoiceType, ServiceType, b.CreationOn as CustomerCreationOn, b.ModifiedOn as CustomerModifiedOn,
       UserTitle, CustomerName, Mobile, Mobile2, Email, Gender,
       Nationality, BirthDate, LocationName, IsOwner, IsCashCustomer,
       PayTerm, Age, b.IsActive as CustomerIsActive, BranchCode, BranchType,
       c.IsActive as BranchIsActive, BranchName, AMBadgeNo, AreaManager, Region,
       RMBadgeNo, RegionalManager, Longitude, Latitude, City
  FROM MACDB.dbo.v_Invoice a
    INNER JOIN MACDB.dbo.v_Customer b
    ON a.CustomerID = b.CustomerID
    INNER JOIN MACDB.dbo.v_Branch c
    ON a.BranchID = c.BranchID
  WHERE 
      YEAR(InvoiceDate) >= 2025 and 
      MONTH(InvoiceDate) = 6 and
      CITY = 'JEDDAH'
""")
rows = cursor.fetchall()
trx_june_df = pd.DataFrame.from_records(rows, columns=[col[0] for col in cursor.description])

trx_june_df #.sort_values(["year", "month"]).pivot_table("count", "year", columns="month")

,InvoiceID,InvoiceNumber,ModifiedOn,BranchID,TransCustomerID,CustomerID,CustomerVehicleID,SystemUserID,InvoiceDate,InvoiceDueDate,...,BranchIsActive,BranchName,AMBadgeNo,AreaManager,Region,RMBadgeNo,RegionalManager,Longitude,Latitude,City
0,B43D8B08-295A-46E0-AF4E-0162BCB8C2B1,M-1903-002-26965,2025-06-01 19:50:45,5065B612-EB63-459E-9AAE-64C3DF03C24A,4E8E52F9-1E9B-4CB1-8E2D-B9E0EC77FA4B,4E8E52F9-1E9B-4CB1-8E2D-B9E0EC77FA4B,BD327550-5B10-4C62-A722-482965A097FA,B70AE93D-1B4C-41BA-8073-8628F1151374,2025-06-01 19:50:10,2025-06-01 19:50:10,...,True,AL AMAL,23429,Deepak Kumar Jha,PAC,None,None,0E-9,0E-9,JEDDAH
1,99AB3EEC-A925-427E-AFB1-01D27B9C542C,M-1903-002-26986,2025-06-02 17:02:53,5065B612-EB63-459E-9AAE-64C3DF03C24A,27AFBF4C-DA0D-4DE0-AC13-C84DD29C4B85,27AFBF4C-DA0D-4DE0-AC13-C84DD29C4B85,D0CE7586-1E4C-45FE-BA3C-ADD92AF47732,B70AE93D-1B4C-41BA-8073-8628F1151374,2025-06-02 17:02:35,2025-06-02 17:02:35,...,True,AL AMAL,23429,Deepak Kumar Jha,PAC,None,None,0E-9,0E-9,JEDDAH
2,AD5B8EC5-AD57-48F9-BAFE-038ADEF92BB1,M-1903-002-27395,2025-06-30 20:07:17,5065B612-EB63-459E-9AAE-64C3DF03C24A,24D28791-2982-4504-A72A-576E5851F07C,24D28791-2982-4504-A72A-576E5851F07C,1BC62079-471D-4CB3-8177-656D5B66E750,B70AE93D-1B4C-41BA-8073-8628F1151374,2025-06-30 20:07:01,2025-06-30 20:07:01,...,True,AL AMAL,23429,Deepak Kumar Jha,PAC,None,None,0E-9,0E-9,JEDDAH
3,EDB4DF3F-EBE5-46FC-98F1-0393C7222E50,M-1903-002-27029,2025-06-04 17:05:17,5065B612-EB63-459E-9AAE-64C3DF03C24A,2854C5B1-81BA-4695-B7EA-DDB09532B295,2854C5B1-81BA-4695-B7EA-DDB09532B295,A170260F-8153-4523-AFA8-AD6EE03904F5,B70AE93D-1B4C-41BA-8073-8628F1151374,2025-06-04 17:03:30,2025-06-04 17:03:30,...,True,AL AMAL,23429,Deepak Kumar Jha,PAC,None,None,0E-9,0E-9,JEDDAH
4,1172B0D4-37B8-4F1B-91FB-0577EEBCD104,M-1903-002-27303,2025-06-25 18:25:12,5065B612-EB63-459E-9AAE-64C3DF03C24A,8926EE53-32ED-4D00-AEF6-2B9EF37435CC,8926EE53-32ED-4D00-AEF6-2B9EF37435CC,B0EE99FD-8614-4EA0-80F6-9A78F95C4D4E,DAF0B314-A430-4146-B66C-559A733456E8,2025-06-25 18:24:38,2025-06-25 18:24:38,...,True,AL AMAL,23429,Deepak Kumar Jha,PAC,None,None,0E-9,0E-9,JEDDAH
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
43526,DFAAA190-C4C1-4213-83CF-FB6DB7DF1035,M-1900-002-29133,2025-06-15 23:15:28,41AE2BD9-BD94-46C2-BE11-896AE8586152,9C1BCE82-2188-4DB9-BA68-BD89EC49DF0C,9C1BCE82-2188-4DB9-BA68-BD89EC49DF0C,D163E1BC-35AA-4EBC-8958-5D37008C9A13,6A232805-F737-47CD-86E8-3382B6FD8B3E,2025-06-15 23:14:52,2025-06-15 23:14:52,...,True,JED-IND-SHIFABINDAJAM-WRS,20719,ALI KHAWAR,WR SOUTH,18466,SHERYAR KHAN,21.440000000,39.270000000,JEDDAH
43527,E956F4A4-2FDD-4CCD-B9E5-FBD23FC41F21,M-1618-288-37571,2025-06-01 13:58:48,72758A5D-C7BD-4615-BFC0-8CF2072D3E3B,6035D985-0F2E-4055-A552-9B74E9CE6C66,6035D985-0F2E-4055-A552-9B74E9CE6C66,0CD49CBA-BAB0-451F-99A1-B512A794FC6A,DC364E35-967F-49BE-85D0-0BFBE68934FB,2025-06-01 13:58:38,2025-06-01 13:58:38,...,True,JED-STD-ESMARTCAR-WRS,20719,ALI KHAWAR,WR SOUTH,18466,SHERYAR KHAN,21.500000000,39.260000000,JEDDAH
43528,E1BD53FB-705D-467F-929E-FB59C85CE755,M-1375-001-42487,2025-06-24 13:16:34,D16FA880-8761-4996-B506-BAC5BDE3279F,2F960ACC-E758-4DBE-B6CC-BF83234D1589,EB22DB02-42A1-455C-BE63-DB97DC6CD74D,4A9D8FD0-1F29-43FC-8B5D-9F18F11AC479,2BDA1A54-E9F9-4EF6-B09C-A5684B11A760,2025-06-24 13:14:34,2025-06-24 13:14:34,...,True,JED-STD-SANABEL-WRS,20719,ALI KHAWAR,WR SOUTH,18466,SHERYAR KHAN,21.410000000,39.270000000,JEDDAH
43529,A6EB0BC2-F7A7-43F8-BFE0-FBE4C235EF08,M-1375-001-42056,2025-06-02 23:41:30,D16FA880-8761-4996-B506-BAC5BDE3279F,ECCCCA45-BFFB-403E-80FB-2D4BB9D3F66A,ECCCCA45-BFFB-403E-80FB-2D4BB9D3F66A,C1572F2D-3E7B-419C-83AB-9CD75BC7F0A4,C3F33A77-A7ED-47AD-BDF8-5F3754A8769F,2025-06-02 23:25:31,2025-06-02 23:25:31,...,True,JED-STD-SANABEL-WRS,20719,ALI KHAWAR,WR SOUTH,18466,SHERYAR KHAN,21.410000000,39.270000000,JEDDAH
43530,D680CBD9-3BFF-4DEC-9B13-FBDE9E9895D0,M-1375-001-42215,2025-06-12 11:50:03,D16FA880-8761-4996-B506-BAC5BDE3279F,2F960ACC-E758-4DBE-B6CC-BF83234D1589,DB2367D4-462D-4018-9BDF-A1756EF03062,B406E42F-CDA7-4EBE-A055-0D9C1505B762,C3F33A77-A7ED-47AD-BDF8-5F3754A8769F,2025-06-12 11:49:16,2025-06-12 11:49:16,...,True,JED-STD-SANABEL-WRS,20719,ALI KHAWAR,WR SOUTH,18466,SHERYAR KHAN,21.410000000,39.270000000,JEDDAH

In [12]:
trx_june_df.shape

(43531, 62)

In [13]:
trx_june_df.columns

Index(['InvoiceID', 'InvoiceNumber', 'ModifiedOn', 'BranchID',
       'TransCustomerID', 'CustomerID', 'CustomerVehicleID', 'SystemUserID',
       'InvoiceDate', 'InvoiceDueDate', 'InvoiceBeforeDiscountAmount',
       'InvoiceDiscountAmount', 'InvoiceBeforeTaxAmount', 'InvoiceTaxAmount',
       'InvoiceTotalAmount', 'InvoiceItemCost', 'IsFleet', 'IsPMS',
       'CustomerContractID', 'CustomerContractType', 'WorkOrderNumber',
       'WorkOrderStartDate', 'WorkOrderEndDate', 'WorkOrderMileage',
       'PreviousMileage', 'PreviousVisitDate', 'NewOrExistingCustomer',
       'NewCustomer', 'NewVehicle', 'Warranty', 'PMSID', 'PMSName',
       'InvoiceType', 'ServiceType', 'CustomerCreationOn',
       'CustomerModifiedOn', 'UserTitle', 'CustomerName', 'Mobile', 'Mobile2',
       'Email', 'Gender', 'Nationality', 'BirthDate', 'LocationName',
       'IsOwner', 'IsCashCustomer', 'PayTerm', 'Age', 'CustomerIsActive',
       'BranchCode', 'BranchType', 'BranchIsActive', 'BranchName', 'AMBadgeNo',
       'AreaManager', 'Region', 'RMBadgeNo', 'RegionalManager', 'Longitude',
       'Latitude', 'City'],
      dtype='object')

In [14]:
trx_june_df["BranchName"].value_counts()

BranchName
JED-PET-HERAQUAS-WRN    1238
BANI MALIK TAJ          1168
JED-PET-SAHAFA-WRS      1025
BASHAIR                  947
JED-GUL-QURAISH1-WRN     856
                        ...
KNOZ ROWDAH               74
Saher Obhur                1
PE Rehab                   1
Corporate Center JDD       1
Salhia                     1
Name: count, Length: 99, dtype: int64

In [15]:
trx_june_df.groupby(["BranchCode", "BranchName"]).agg({
    "InvoiceID": "nunique",
    # "TransCustomerID": "nunique",
    "CustomerID": "nunique",
}).sort_values("CustomerID", ascending=False)

                                 InvoiceID  CustomerID
BranchCode BranchName
1025       JED-PET-HERAQUAS-WRN       1238        1187
2210       BANI MALIK TAJ             1168        1140
1008       JED-PET-SAHAFA-WRS         1025         972
2209       BASHAIR                     947         893
1006       JED-GUL-QURAISH1-WRN        856         829
...                                    ...         ...
2206       KNOZ ROWDAH                  74          72
2251       PE Rehab                      1           1
2257       Saher Obhur                   1           1
2116       Corporate Center JDD          1           1
2319       Salhia                        1           1

[100 rows x 2 columns]

In [16]:
cursor = conn.cursor()
cursor.execute("""
SELECT TOP 1
   *
  FROM MACDB.dbo.v_Invoice
""")
rows = cursor.fetchall()
df = pd.DataFrame.from_records(rows, columns=[col[0] for col in cursor.description])

df

,InvoiceID,InvoiceNumber,ModifiedOn,BranchID,TransCustomerID,CustomerID,CustomerVehicleID,SystemUserID,InvoiceDate,InvoiceDueDate,...,PreviousMileage,PreviousVisitDate,NewOrExistingCustomer,NewCustomer,NewVehicle,Warranty,PMSID,PMSName,InvoiceType,ServiceType
0,B307C673-1C94-49E1-B0B1-01000007C7D0,M-1480-8697,2023-01-07 23:40:33,79719D5F-191D-44C3-9442-7D940CE07006,95E5858B-C616-4857-BE1F-F7D262CB4D48,95E5858B-C616-4857-BE1F-F7D262CB4D48,0604754A-496B-4534-B5A5-C959C335B486,80AC933C-EF5D-4E70-ABB3-1BD818F6A96C,2023-01-07 19:41:21,2023-01-07 19:41:21,...,54242,2022-11-24 19:15:57,Existing Customer,0,0,1,None,None,Cash,PE Service

In [17]:
cursor = conn.cursor()
cursor.execute("""
SELECT 
   YEAR(ModifiedOn) as year, MONTH(ModifiedOn) as month , COUNT(*) as count
  FROM MACDB.dbo.v_Customer
  WHERE YEAR(ModifiedOn) >= 2024
  GROUP BY YEAR(ModifiedOn), MONTH(ModifiedOn)

""")
rows = cursor.fetchall()
df = pd.DataFrame.from_records(rows, columns=[col[0] for col in cursor.description])

df.sort_values(["year", "month"]).pivot_table("count", "year", columns="month")

month,1,2,3,4,5,6,7,8,9,10,11,12
year,,,,,,,,,,,,
2024,57212.0,44240.0,45110.0,45691.0,59142.0,67166.0,71362.0,71239.0,77414.0,69263.0,65166.0,68053.0
2025,70592.0,87719.0,92077.0,110314.0,159358.0,164441.0,237925.0,268737.0,90712.0,NaN,NaN,NaN

In [18]:
audit_df = pd.read_csv("june_data/plate_mobile_audit.csv/part-00000-9b48529b-efe6-4c97-9b0e-66fa6e9aa70d-c000.csv", sep=",")
audit_df.head()

,_id,plate_number,mobile,index,valid_mobile,valid_plate,valid_id,n_customer_id_mobile_db,min_customer_creation_on_mobile_db,min_customer_modified_on_mobile_db,...,not_found_correct_id,nothing,not_found_correct_id__notvalid_plate_notvalid_mobile,not_found_correct_id__valid_plate_notvalid_mobile,not_found_correct_id__notvalid_plate_valid_mobile,not_found_correct_id__valid_id,not_found_correct_id__exist_mobile_notexist_plate,not_found_correct_id__exist_plate_notexist_mobile,not_found_correct_id__notexist_plate_notexist_mobile,not_found_correct_id__exist_plate_exist_mobile
0,0006RGX__966563622803,6RGX,966563622803,391,1,0,0,176,2021-03-12,2020-03-26,...,1,0,0,0,1,0,0,0,0,0
1,0723BEZ__966554093228,723BEZ,966554093228,5259,1,0,0,14,2021-03-12,2022-07-27,...,1,0,0,0,1,0,0,0,0,0
2,1033KSA__966563323729,1033KSA,966563323729,7274,1,1,1,4,2023-08-26,2023-08-26,...,0,0,0,0,0,0,0,0,0,0
3,1111AAA__966536272544,1111AAA,966536272544,9295,1,0,0,39,2021-03-12,2023-10-15,...,1,0,0,0,1,0,0,0,0,0
4,1182JRD__966508962039,1182JRD,966508962039,11281,1,1,1,1,2021-06-01,2025-04-12,...,0,0,0,0,0,0,0,0,0,0

In [19]:
audit_df[audit_df["_id"] == "1234ASS__966543671341"]

,_id,plate_number,mobile,index,valid_mobile,valid_plate,valid_id,n_customer_id_mobile_db,min_customer_creation_on_mobile_db,min_customer_modified_on_mobile_db,...,not_found_correct_id,nothing,not_found_correct_id__notvalid_plate_notvalid_mobile,not_found_correct_id__valid_plate_notvalid_mobile,not_found_correct_id__notvalid_plate_valid_mobile,not_found_correct_id__valid_id,not_found_correct_id__exist_mobile_notexist_plate,not_found_correct_id__exist_plate_notexist_mobile,not_found_correct_id__notexist_plate_notexist_mobile,not_found_correct_id__exist_plate_exist_mobile
607,1234ASS__966543671341,1234ASS,966543671341,12707,1,1,1,107,2021-03-12,2021-06-28,...,1,0,0,0,0,1,1,0,0,0
2409,1234ASS__966543671341,1234ASS,966543671341,12705,1,1,1,107,2021-03-12,2021-06-28,...,1,0,0,0,0,1,1,0,0,0
149711,1234ASS__966543671341,1234ASS,966543671341,12704,1,1,1,107,2021-03-12,2021-06-28,...,1,0,0,0,0,1,1,0,0,0
199700,1234ASS__966543671341,1234ASS,966543671341,12706,1,1,1,107,2021-03-12,2021-06-28,...,1,0,0,0,0,1,1,0,0,0

In [20]:
# .select(
#     f.sum("found_correct_id").alias("total_found_correct_id"),
#     f.sum("not_found_correct_id").alias("total_not_found_correct_id"),
#     f.sum("nothing").alias("total_nothing"),
#     f.sum("not_found_correct_id__notvalid_plate_notvalid_mobile").alias("total_not_found_correct_id__notvalid_plate_notvalid_mobile"),
#     f.sum("not_found_correct_id__valid_plate_notvalid_mobile").alias("total_not_found_correct_id__valid_plate_notvalid_mobile"),
#     f.sum("not_found_correct_id__notvalid_plate_valid_mobile").alias("total_not_found_correct_id__notvalid_plate_valid_mobile"),
#     f.sum("not_found_correct_id__valid_id").alias("total_not_found_correct_id__valid_id"),
#     f.sum("not_found_correct_id__notexist_plate_notexist_mobile").alias("total_not_found_correct_id__notexist_plate_notexist_mobile"),
#     f.sum("not_found_correct_id__exist_mobile_notexist_plate").alias("total_not_found_correct_id__exist_mobile_notexist_plate"),
#     f.sum("not_found_correct_id__exist_plate_notexist_mobile").alias("total_not_found_correct_id__exist_plate_notexist_mobile"),
#     f.sum("not_found_correct_id__exist_plate_exist_mobile").alias("total_not_found_correct_id__exist_plate_exist_mobile"),
# )

In [21]:
audit_df.drop(columns="index").drop_duplicates()[[
    "found_correct_id",
    "not_found_correct_id",
    "nothing",
    "not_found_correct_id__notvalid_plate_notvalid_mobile",
    "not_found_correct_id__valid_plate_notvalid_mobile",
    "not_found_correct_id__notvalid_plate_valid_mobile",
    "not_found_correct_id__valid_id",
    "not_found_correct_id__notexist_plate_notexist_mobile",
    "not_found_correct_id__exist_mobile_notexist_plate",
    "not_found_correct_id__exist_plate_notexist_mobile",
    "not_found_correct_id__exist_plate_exist_mobile",
]].sum()

found_correct_id                                         60793
not_found_correct_id                                    169003
nothing                                                     35
not_found_correct_id__notvalid_plate_notvalid_mobile         9
not_found_correct_id__valid_plate_notvalid_mobile          184
not_found_correct_id__notvalid_plate_valid_mobile         4434
not_found_correct_id__valid_id                          164376
not_found_correct_id__notexist_plate_notexist_mobile     26314
not_found_correct_id__exist_mobile_notexist_plate        18195
not_found_correct_id__exist_plate_notexist_mobile        67426
not_found_correct_id__exist_plate_exist_mobile           52441
dtype: int64

In [22]:
mobile_list = audit_df["mobile"].astype("str").str.replace("^966", "0", regex="True").tolist()
len(mobile_list), len(set(mobile_list))

(242363, 218955)

In [23]:
plate_list = audit_df[audit_df["found_correct_id"] > 0]["plate_number"].tolist()
len(plate_list), len(set(plate_list))

(63100, 60778)

In [24]:
id_list = audit_df[audit_df["not_found_correct_id"] > 0]["_id"].tolist()
len(id_list), len(set(id_list))

(179216, 169002)

In [25]:

print(trx_june_df[trx_june_df["Mobile"].astype(str).isin(mobile_list)].groupby(["BranchCode", "BranchName"]).agg({"InvoiceID": "nunique", "CustomerID":"nunique"}).sort_values("CustomerID", ascending=False).head(10).to_markdown())

|                                     |   InvoiceID |   CustomerID |
|:------------------------------------|------------:|-------------:|
| ('1025', 'JED-PET-HERAQUAS-WRN')    |        1108 |         1065 |
| ('2210', 'BANI MALIK TAJ')          |        1052 |         1025 |
| ('1008', 'JED-PET-SAHAFA-WRS')      |         910 |          861 |
| ('2209', 'BASHAIR')                 |         825 |          804 |
| ('1006', 'JED-GUL-QURAISH1-WRN')    |         772 |          752 |
| ('2008', 'JED-PET-SAQRQURAISH-WRN') |         743 |          718 |
| ('1962', 'JED-STD-FEHYA-WRS')       |         692 |          666 |
| ('1136', 'JED-PET-RABEEA-WRS')      |         723 |          665 |
| ('1921', 'JED-STD-ALQERNI-WRN')     |         637 |          610 |
| ('1662', 'JED-PET-SAHER-WRS')       |         625 |          609 |

In [26]:
cursor = conn.cursor()
cursor.execute(f"""
    SELECT 
       a.CustomerID as CustomerCustomerID, a.CreationOn as CustomerCreationOn, a.ModifiedOn as CustomerModifiedOn, UserTitle, CustomerName,
       Mobile, Mobile2, Email, Gender, Nationality, BirthDate,
       LocationName, IsOwner, IsCashCustomer, PayTerm, Age,
       IsActive, CustomerVehicleID, b.CreationOn as VehicleCreationOn, b.ModifiedOn as VehicleModifiedOn,
       b.CustomerID as VehicleCustomerID, Make, Model, ModelYear, TransmissionType,
       PMSName, PlateNumber, VIN, IsDriverOwner
    FROM MACDB.dbo.v_Customer a
    FULL OUTER JOIN MACDB.dbo.v_Vehicle b
    ON a.CUSTOMERID = b.CUSTOMERID
    WHERE 
        (YEAR(a.ModifiedOn) = 2025 and Month(a.ModifiedOn) >= 6) or
        (YEAR(b.ModifiedOn) = 2025 and Month(b.ModifiedOn) >= 6)
""")
rows = cursor.fetchall()

df = pd.DataFrame.from_records(rows, columns=[col[0] for col in cursor.description])
df.head()

,CustomerCustomerID,CustomerCreationOn,CustomerModifiedOn,UserTitle,CustomerName,Mobile,Mobile2,Email,Gender,Nationality,...,VehicleModifiedOn,VehicleCustomerID,Make,Model,ModelYear,TransmissionType,PMSName,PlateNumber,VIN,IsDriverOwner
0,7C91BC19-1D00-4E78-BC20-00E34BF0F603,2021-03-12 00:11:18,2025-06-09 21:59:02,None,MR.JIHAD HUSIN ALMASRUHI,0560823654,None,None,None,None,...,2020-03-26 11:55:24,7C91BC19-1D00-4E78-BC20-00E34BF0F603,CHEVROLET,Caprice,2016.0,Automatic,None,2058NNJ,6G3NT5C22GL205354,False
1,5A709836-8C3C-43E9-9C5E-0130C45A816E,2024-11-27 20:57:43,2025-08-26 19:00:02,None,MOHAMMAD,0566731114,None,None,Male,None,...,2025-02-15 20:58:55,5A709836-8C3C-43E9-9C5E-0130C45A816E,TOYOTA,COROLLA,2023.0,Automatic,TOYOTA,1861KRR,RKLB20BE0P2030418,True
2,1936F708-B424-4276-B5E8-0001116F66D0,2021-10-28 13:18:52,2025-09-01 16:54:52,Mr.,AYED NASSER,0599924355,None,None,Company,Pakistani,...,2025-08-16 11:12:27,1936F708-B424-4276-B5E8-0001116F66D0,TOYOTA,YARIS,2024.0,Automatic,TOYOTA,9693BLR,MR2BE9B34R0085551,True
3,1936F708-B424-4276-B5E8-0001116F66D0,2021-10-28 13:18:52,2025-09-01 16:54:52,Mr.,AYED NASSER,0599924355,None,None,Company,Pakistani,...,2025-08-17 22:04:37,1936F708-B424-4276-B5E8-0001116F66D0,FAW,T77 PRO,2025.0,Automatic,None,4189JZR,LFBGE3061SJK11815,True
4,1936F708-B424-4276-B5E8-0001116F66D0,2021-10-28 13:18:52,2025-09-01 16:54:52,Mr.,AYED NASSER,0599924355,None,None,Company,Pakistani,...,2022-09-08 22:42:34,1936F708-B424-4276-B5E8-0001116F66D0,VOLVO,440,2013.0,Manual,None,4452NRA,YV2AS02A0D0911512,True

In [27]:
df.columns

Index(['CustomerCustomerID', 'CustomerCreationOn', 'CustomerModifiedOn',
       'UserTitle', 'CustomerName', 'Mobile', 'Mobile2', 'Email', 'Gender',
       'Nationality', 'BirthDate', 'LocationName', 'IsOwner', 'IsCashCustomer',
       'PayTerm', 'Age', 'IsActive', 'CustomerVehicleID', 'VehicleCreationOn',
       'VehicleModifiedOn', 'VehicleCustomerID', 'Make', 'Model', 'ModelYear',
       'TransmissionType', 'PMSName', 'PlateNumber', 'VIN', 'IsDriverOwner'],
      dtype='object')

In [28]:
df["key"] = df["CustomerCustomerID"] + "__" + df["CustomerVehicleID"]

In [29]:
int_customers = pd.read_parquet("../data/02_intermediate/int_customers", engine="fastparquet")
int_vehicles = pd.read_parquet("../data/02_intermediate/int_vehicles", engine="fastparquet")

In [30]:
spine_df = pd.read_parquet("../data/03_primary/prm_spine", engine="fastparquet")

In [31]:
spine_df["_id"].drop_duplicates().shape, spine_df["_key"].drop_duplicates().shape,

((3189261,), (3517768,))

In [32]:
spine_keys = spine_df["_key"].drop_duplicates().to_list()
june_keys = df["key"].drop_duplicates().to_list()

In [33]:
len(set(june_keys)), len(set(spine_keys))

(765355, 3517768)

In [34]:

len(set(june_keys).intersection(set(spine_keys)))

659738

In [35]:
set(june_keys) - set(spine_keys)

{'E3426337-7AC6-4899-8FA6-7DCCB78E7566__B21A9A74-DDFE-4733-98CD-5F78DCB3CF9A',
 'FCEDEDE5-AD2A-4A4F-9C4A-874D8FF96349__0680A9C0-1F98-4CB7-9BD8-590B4F95BD22',
 '00B881C0-EF6A-4E47-B202-E1E2D67DAED3__C96C02F8-FA50-47EC-B233-89D4FFFC5922',
 '3094B84B-3E71-4085-9400-8BAD32B14613__1C521D43-8159-43DD-B1E5-353B7A4F2553',
 'BADD38FE-3949-495D-8720-7BA2E1B84FD5__720D0E77-1728-4051-8407-57240868AB9A',
 '37E10B5A-D98F-4F35-9DC3-77A576BB3FA1__F7929319-AEE0-4C93-A127-C14A2D259648',
 '47522F1F-1A31-4A3F-A4F0-09BC4C0988EF__FA3DF694-F7EF-4E9D-97C9-93BF1187A34C',
 '2E0A2F2F-3471-4C04-91FF-F7D497F62995__0A9C4431-BA77-4571-852D-2310810F48B9',
 'C6C19EDF-17B3-4022-9CA0-13B69E0172F2__58CC4DE3-9B1E-493D-A8E2-4B5F74D33D61',
 '4F498727-AD80-4B7C-B3EE-AB17C1C94D11__969DF963-113F-4C05-9398-A3C5B7CC15DE',
 'C617DBC0-4B54-46D5-8948-5F6558FF948E__CA70296B-B044-46DF-BF0D-E7219A3E50B4',
 'DE4E824D-0F37-4C07-9AE5-098389F754EC__15438232-98AA-4228-BB79-6938CC425F1F',
 '3FCF434B-575B-4481-B342-CBD306B47114__843EDEC6-7BB9-47CF-8D1A-ED31637E409C',
 '8AC571BB-8331-451B-B517-8787F1425253__BE2D285E-5078-432C-8280-19883CACC4BB',
 'CA6E117D-1CC3-47DE-B2F6-B52A019FC380__87669469-58BA-496F-93BF-73126C723F57',
 '5872FFAC-9F24-437C-B8A0-193CA62931AC__878F0C22-4B22-4082-8092-775BE59BE77C',
 '38BB1FE2-1615-4808-8A19-FB2E0187A6D2__BA7BEEB0-ED37-4DA8-B9C7-11DAFB718381',
 '789B86D1-97C6-4A82-AD01-B77019468A78__815E2E34-4316-41B0-9549-130B3923B310',
 '6B787FC6-7CF2-4B66-985D-11D903E1FB57__A0AFDC92-5B83-4579-BF87-9B898B87A771',
 'FD3F017E-CAA5-46A1-BA1E-E1B19EFBD760__A30052E6-3747-4D63-8303-BFE5E9ABFA71',
 'DD4804A4-E505-4C60-B314-D55785ED9D6E__5BB669EC-C17E-4192-B097-D3D7CD9E5E11',
 'F72485B2-75C0-4394-89FA-21669D8C5E8E__D8FCC99A-4222-413C-9CAD-35CAA30C4B15',
 '9DDF8213-38AE-439A-9581-14A40B96194A__0D0C47F9-9E93-48E4-A4A3-1B1EE7FC4D44',
 '7E8A2494-A342-4A53-BF82-E1B698DAE818__69B521A2-7614-4D6E-90CE-ED0372F171AF',
 '736DE2B3-7B1E-441C-8609-29460C0CF96E__54D08721-5F60-45E5-BD40-051305ADA33D',
 '1EF95BF4-84EF-4FDC-BE0A-A3B1D1A25C5E__DAF722F4-6F51-493C-98DD-D7E753084DDF',
 '64E984A6-0A0D-42DB-A279-192B90FF63D2__41E8B224-911C-4710-A5A2-CD970DE0AF57',
 'D1749648-998F-498A-85E0-6F5B1BC0C292__83C92871-853D-43B5-B8B6-7B59C151ADCB',
 '4FBEAFA9-6699-487A-816F-E36656F08484__7C87CED4-15E0-4C7A-B1A2-450A3CC28881',
 'A269B8BA-2C00-4BF1-A330-1B72B153F618__343C6886-3008-4AF2-8388-95E13A216132',
 'D17062A0-D58B-41BC-B6AD-ADE21A677EF6__8408F5DA-0E6B-4730-905F-278C021D6036',
 '90D70712-5613-48C7-8603-4B312A7B139D__348611FA-E86B-488A-B532-B5C779162E9E',
 'D145206B-EBCA-4269-9BAE-DD90ECCADBCF__9CF6D8EB-144D-4E74-87C2-65DD0DF4E112',
 '6ECE3F9A-39FF-4B9C-95A1-593884B58D77__8BBD8C7D-2917-4D61-BB21-3FF08371E066',
 '1E0C17B1-561F-42FE-91E1-E50091E40029__6DFE8329-836F-4A75-BF29-EFEDE980349B',
 '375FC31F-769A-403B-A6A6-7B99AB15E079__541C1FD1-77E5-4BF2-8FA5-1D0E50950E79',
 '78253D5D-D2FE-474A-8DD8-65AE0B145DAA__1EEA9FB0-912E-4E26-B6D5-635202F45096',
 '19E65E19-BC46-4CB9-8F95-6C9369B7F03F__3B949346-BCBD-49BE-A705-217878EBBDE9',
 'B8A1A804-7983-4172-9C64-A3D07DE1805A__59D6C557-94F8-4948-906C-21C186481041',
 '498CEB46-C492-46B3-8EDF-41B53714A985__633D0695-C343-448D-A6DF-A8A51A895F70',
 'CF03A47E-764C-43C4-A45A-2D80642E7E12__76CFB12B-B407-4BE1-A2A8-03D340F0F8DF',
 'C9BC7EF2-EE98-4B9B-9062-A30EFC8D2616__69BA5D93-C725-48EE-87BD-758BBFA53C3F',
 'F556B091-3D91-4D59-8A34-D9E38EC3E23D__1A8E4CD7-C0E4-427E-A426-E5247F348E39',
 'BAB20972-6C89-4EC8-96C3-A91FD138238D__40BFD5AE-80D2-4375-96CE-2FBDA0EE4ED9',
 '6006C018-C392-4C94-9818-DD0D8CB7376F__0A4C2351-BC5B-4183-B318-5393F1ADD3FF',
 '9F0B28D1-91CB-4CEA-A282-D73644039E7C__33BFFB6C-F7CC-41C3-8777-09D06ECFCFB6',
 '28FC2665-FACB-4D55-A194-D9ACC444BED1__E6E74544-A836-4529-A3CA-B104BC8FB96A',
 '81E8DFFA-9DEF-47C8-B27A-C17B8907E535__33EE2485-4287-4ACD-8C94-4F473A6A0B6A',
 '2AF98ABA-CB3F-48BC-81FB-5FCD87345F8E__261BFAD5-C091-46AB-8664-F770C796E269',
 '97706AFB-7236-4CEB-BAD7-D199F8AAB68A__F2FA1168-66CC-4752-B137-8D455EE047E8',
 '221A44B2-CCDE-412A-857F-49C8F41B375B__7DAB5221-A560-4027-8243-C1BBA7215A3F',
 '244EC1A6-9E52-45D3-AFFF-11E60B1FB20F__F65A62A4-AF40-493E-8329-DD7324C9AB6E',
 'BCB81D7C-BE27-48EA-997E-976784B49FA5__0C4B4E93-06DF-42FE-8C03-39275CFE21FB',
 '3B20F472-B4F4-40DD-A561-B76D84B9C179__C241D572-58C9-493C-86F9-4325DCB94463',
 '733A3D5A-B2EE-46D9-98B0-C6C0EDA3726F__6D6821B7-C4B3-4957-9145-4D4C45FAF761',
 'F1BCE865-DEDC-41B4-A570-C5BA8474419F__5C32320C-637A-4B55-8970-1F50ED070623',
 'CA5A6F37-4AD7-466D-88DF-7B93E7E1137E__7362DAD9-3C20-4AF8-AB96-8BBA451717B2',
 '33AA69F6-C13C-4B45-A264-5C0F759A609E__8CFB849C-ACF1-4EF3-815C-0436C7FBEEF3',
 'E0A61C4C-D689-46BD-8C9A-13E2FC765601__D8FB5A72-1336-44C5-94D9-7E78C81E1CB8',
 '91FB0224-1D7B-4E09-8608-A72DE18A1BE1__E69630E2-843C-46D5-8EDD-61FBF63D8621',
 '5B133248-75A7-4039-88D1-950204394FEA__A2C8CE3C-B93B-468E-83E8-0D408640D672',
 '9210B71B-B4A1-4B40-A96F-291E25D53093__7D325E08-D1FC-4415-89DC-77EA8FCFBF37',
 '8F81D25C-0C3F-49F2-8537-1D589B016E33__0A5CE012-D9F5-49D6-8524-E5A0EF9EC43D',
 'CBCA4E9C-6C7F-4C82-A5E1-35C88FCD9C4F__5E92C744-1BFD-4D26-B9F8-A544D053B2CA',
 '3DF1A374-CF91-4B48-850F-0BA39A43A472__9976D7BB-4BF0-4435-8EDE-9AFD5228737C',
 'A3CA75EC-6CAB-4C11-B44C-7DA247D94097__0C39111F-8600-42D3-8924-7BC862BF3E88',
 'C9671137-DF09-4AFB-B569-A145EE1AAC6F__7FB0767F-C7CE-49DC-886B-B3B3F241F669',
 '1C196272-C5A9-4DF0-AE88-A1A4D428360B__63C7BC2F-3FBC-4C42-8997-3790659360ED',
 '95F5ACB9-43D7-416D-8024-D1D76046E205__FBF3262F-3607-41FF-AE3C-96BEF07797D7',
 '0381C26B-C4DA-4F3C-AAF5-E129A8515FE1__9CE10480-49CA-4EA4-B3DD-CDF6413D5DB3',
 '9F01EFB4-100D-4BE3-8243-1D3454025880__D34F25B5-EDC2-420C-8CEA-1BB19F5EA850',
 '10A605D0-2754-4394-BE34-6B03903AF220__FE5E1485-A673-47F0-8A3B-F310D7E569EE',
 '1F26DC00-3C9D-4E2F-A1A2-CBF53E0CA567__E4B67F7A-246E-46C7-B837-E5130385FAC6',
 'A8994C76-8020-4766-B9AF-013A7D6B3DE7__1381C44E-399E-4051-AE84-937D09987353',
 '6CBBF16F-ABF6-46DB-993E-3188B4141E25__A89411D6-F001-4205-894F-6911D230C88E',
 'F0AEB54D-B031-49D6-8414-DF34AE6B66F1__386B0893-D571-42A3-964C-D99DF16C7BC4',
 'E7ACD7F8-40CA-4F4A-9ED2-4BDB0F2108D2__88B1D600-E7FC-4015-B556-130E087AB27E',
 'E542F3A3-A5B4-4CA9-B5F3-67E9D13388DA__DDE9415E-9A5D-4744-B2A6-932D072DBE62',
 'C1FD39A2-6391-476B-8744-5547BD98A7B6__510B7683-7937-4471-B051-358857A71977',
 '0A8A9399-C0ED-48E3-8B73-814BEAE2E12A__D3FD9511-1F49-497C-994E-2DEA62B773B8',
 '3C9562AC-85DB-4164-80F1-6DD48A358DA1__6EB4F244-C02C-4347-BDA9-69C81B58A355',
 'E04E1660-3AA3-455A-936F-D93B3840FA83__DDE2CBFA-0C1A-4976-9A0D-69E1936A2E3E',
 '4CD2F3ED-239D-434E-A057-634F5813651B__7BB923A9-14BE-48EB-B727-950DD8FDF3C4',
 'FF54B934-6811-4B39-A1C3-FDFF65C35BBE__731E4404-3CAF-43A2-B7C1-2BB30FE9AE40',
 '8597FD9D-EBB4-4939-8FE9-510719BA39A5__DC94742E-DAB5-4EB4-9F1C-A78152C77FF5',
 '0D75E197-F9D1-486A-A9AF-D136F42EE55E__77D9D113-8710-4F06-9A66-1BD40D8DCBA1',
 '31006EE9-0763-4D75-87FA-13D83FDCEBF7__B2202439-2971-4A1D-984E-6D20B36A8891',
 '3265BE48-61DC-4BD3-A892-A3B65C6DE1AF__8867EDBC-127A-4F3D-B8C9-CB55AC0BCFAB',
 'E13E013C-4414-4A2C-949B-AD8443417A57__9E6CFD28-2A6C-4241-8758-D3533B13C143',
 '0275EEED-07C3-4794-BD73-BF07A864E566__3FD6017C-0247-45FD-8E03-7984A87F7247',
 'B90FD8EF-820C-4928-9C55-E5A543BE29E5__EB7D3FA1-BDB9-448C-93B7-6FEA762F1C58',
 '1CC951CA-9E56-43C6-B8D7-C877D8F95E68__74702852-CF9E-41B1-9AF7-D6FFB126B87A',
 '56DC268F-2D6C-4190-BA18-070C2AC5EDB4__D35E9C0D-B8A4-4F3B-8ABC-2BE7ED052841',
 '8AC3C57D-067A-44A5-9A88-2BE20821503D__B8779448-545E-417C-A977-B139B2EC490B',
 '78F00643-D109-483E-84FB-D9B0FE5C927C__0D3364B3-FA6F-4FA2-92C8-357B663E9908',
 'DCBB818F-4B06-48E5-BCD0-66D03B5385EA__EC1B3990-6AEB-43B5-9947-AF496CB830F7',
 '3016EB02-D617-4F9F-8140-1D2FD5271BF5__996D7FCF-BB7E-4C28-B9F5-6978AA7E42F8',
 '4939621C-8341-4A05-91A6-0B70A415BBDA__7D408C3E-1581-48B8-BA2B-EB98867E59EF',
 '2DCF311F-9641-4797-B269-6FF7F352E287__6080E670-83D6-4BBE-AA74-BD72647E3AFB',
 '00FE4C0E-AAE7-4492-A7E9-1951EC286F94__ECD5A12E-09C9-467E-893C-C72C357F6ABB',
 'E6CEF3A2-AEED-4E2B-8BB1-0253FA61ECF3__C4515EE7-84F1-4384-808D-E6F891F4F4D6',
 '9536B8F4-1B55-4584-BF6A-C9BDA0145376__5D1D0112-DE40-4C98-B5E3-EB6087E9FDC1',
 '30E5BA2E-33F7-4A81-A07E-969567194975__D4DFDA0A-AD31-4C9B-A22E-BF701EA627C4',
 '3DEB059B-C863-4CC2-B1AE-D32A965E747E__1C7AE263-11F0-475F-A09B-09B665B7B4D3',
 '0EF4F63E-A3AC-404B-8EAC-59918CA99B2C__BA9C3843-3CBB-42F9-9472-B7EA269C9CBC',
 '2825C8CA-4034-475C-B437-4B8D5CAC8CC6__B9C596CE-8BD9-479A-9462-DDD690A5161C',
 '7B8DD749-EE40-4543-B61D-BF9416D4D0BE__1401E362-A7DE-4840-83C5-77A124739193',
 'F38BB52B-9CA2-48A4-92CD-3FDF29B8C8D2__D2FD2A9F-531F-4DD1-A75B-15B2E8272DD0',
 '4F6D21D8-9EB9-4724-81FC-1DF3048913A7__9C0C4EC6-1320-4833-BFAC-7F2A9FB8DF99',
 'BA135139-EEFA-44C9-9992-0BF73B9672D8__7199FD84-CBD5-42C7-A306-BDB383B7D912',
 'CF0D6F4A-926F-4C9B-9C95-6585C540FA54__05FE5C68-62E8-4EAA-AF7E-08ABD08F439C',
 '8342C661-5848-477C-B29E-835222207D0E__562C839B-50A3-47B8-9A4C-337D150F6173',
 'DD0281B7-BA1B-4537-9E7B-D1D53471994A__8D6B0A5B-3B62-4924-9E35-AFD835E37547',
 '6F5424F4-7D2F-4D87-A926-51835795CB98__47B11BE7-45D7-4E96-960D-6B2A62723FD3',
 '52BBB03E-AAD5-44F4-AD85-F52D5BD01128__F47DAA2B-F8BA-46B0-BDE2-7DD04D8CE6D1',
 'B5F388EE-53CA-4FF1-8E6E-61B102869570__23E8EDD2-0D20-4C11-8649-DDC3D09C6A45',
 '6B23DDC9-4934-4485-8EE4-81A7C18A114E__1F54FF6C-83C4-47F7-8F8E-3FD2C17DE6BE',
 '495C73BD-EA9F-4DBB-A873-55FD49E26B36__B8F90888-0785-4D7A-AE9A-EB3ABE78A48A',
 'A4854F2E-ADE0-4D40-BB4A-DB58C6FD2D0C__E76B2BC2-6864-4461-88BE-F1A7E05569A5',
 'C1FD3911-8EA1-4482-BCCC-CD54AB3BF999__7DBB9BDA-347E-4514-80B9-C5ED799CFAB1',
 '21286BEE-3D99-4C8D-A5B9-3D3F9521E47F__C5374D12-7B4A-46D0-AC0F-25622274A91E',
 '54B01412-9EE2-4022-B1FB-E3D858379BE7__C3F4F151-4844-4A1F-82C1-590B9F182B45',
 'FB2C274A-868E-42A9-A0E1-FFCF7EF2383C__2194A83E-D440-45B2-9081-175E09C5277E',
 '23B33574-C8F3-4733-90F8-854EFC792177__1DCCB3F1-9CB2-40A3-9D12-BF7C043C802A',
 '64E9E80C-123E-4C1F-8B7A-C11E34EBC994__59F8E59A-2FE7-4E20-A81D-2D4126D10210',
 '2302A855-4E31-4A18-AA53-214BD8EEACE4__83038EAC-56AA-4CAA-BC4F-A5BA077EB979',
 '56AEDE40-9396-47EC-AEB0-CD8B8B40A7B6__8B5EA65D-BBAF-491B-B3B9-5CE41BC5D26B',
 '5555B374-3A07-4C50-87C4-279AF07E90B0__FAD84946-9A77-46A9-A729-53FD8BE8121D',
 '9EC68EE3-86BB-419A-841A-594286573D1D__8B439049-3CB9-4A6A-A904-452D22B22E36',
 'A30FAB1B-637F-4F7B-B584-FBBC168B2E8B__ECD22B2E-CDC4-4668-A66D-9D3FACA713A1',
 'E79E0B35-CF4E-4AFD-A174-09382017800A__20F02EAE-6331-474E-993B-8DFC4B3FE091',
 'EEA354D0-26CB-473E-B098-4940F7AB559E__7B8C15B4-09D1-49A6-A469-25369854A102',
 'A654AF87-AC41-4156-9BC5-A1EC15B572D2__45A5F2F8-9138-4A84-891B-656C1CA22AD0',
 '5CBCEACA-573F-4A54-941A-F3B157226E10__4A87363D-E18D-4933-A728-976F5AA64ECD',
 '12FCC5C4-47CE-4CEE-9C0B-5855226445B8__5D138DCF-AA5F-4CD0-B73B-801B8D3CC4F6',
 '7AD9DDA5-A456-44C5-A1EE-B1F25351BF0E__3860EE3A-7E15-4B2E-A961-D30F57A4705E',
 'FA4E2966-A5F2-4305-87F1-7356637A3386__6C56BEEB-0EDF-4CD1-84F0-EFF9C435AA2A',
 'B7482A70-AAD1-47E9-A841-6DA9EEB76D5B__42E8F665-1718-4CE4-A647-E390501168F4',
 '79C623C1-9D42-42A9-8409-5582BF08EA56__809D2FE7-EC2F-46BC-9125-6B309E5C8BB7',
 '9723CF13-5B1F-4F21-93F2-3D99ADEDAE11__CDA54BD6-1EF5-463A-B50B-AB6A08527717',
 'A196DC60-2D71-4D22-ABCE-53332FFC6784__8D8526DA-5AC5-42BC-89D0-3F8E598BF088',
 'FED3812E-97A9-4737-A4F8-D1C57AF01406__06447A19-2979-45B0-989E-39C5AB7C5923',
 '261D7015-BF69-4FCC-B9CD-2390605E35BA__47BED0E7-EE46-4D7E-A255-A7CE57F2D49C',
 '7CE4D132-0DAF-4D0A-A797-692C544146B9__85EE61B6-67DE-46DF-9B10-60EDE7F100D1',
 'E51E69BE-ECEB-4CF5-A4EE-F3D49C99E87C__BBB92208-8A5C-4B84-828F-31622573A07B',
 'B5789BCB-5877-4E06-A867-19A51C0A3EF8__7ECB6ADF-0F30-4D09-A69A-5960E07953B9',
 'AB840F17-55F2-4043-9975-73EE20420D92__4DAF007F-8940-4A3E-AADB-E59276109F3C',
 '3CD3B110-8E11-4C78-B05B-552EC67D6DDD__61E94D23-0986-4575-9E82-8DDB357E7BC5',
 'E12082CC-95D8-4B15-8A0D-FBA91D2D4CD9__F9CB19C8-1976-4E23-9EB2-FF25198FE259',
 'F4D010B7-B6F6-497E-9548-CB240FA836F6__5EBD3014-4F8E-44D8-9386-5DD85BE83B81',
 '942DF13B-B479-437F-8EDD-03CF90921B3D__B058572F-D119-472F-A7DC-17BF154A9F86',
 '47519E91-A5EB-4C07-B405-C9F489FE563D__923320E1-DCCC-43BA-B1C5-F52018F38D02',
 '8E8D170D-581C-4304-9FC1-1376A6844E01__3DBAF909-E876-4640-9C70-8BACFDBD935B',
 '85A415F8-41E7-48E5-AC42-272EF1241921__6D1DDE54-85BC-4D9D-9A8F-0727C3B8C4E3',
 '9A32D480-0D62-4B99-B9C4-A3EDF64FD380__A9612488-03B2-42BC-A36C-090B9E22DC65',
 '05B3E6C8-321B-46C2-9B30-7D753462BE99__1EC6BAA1-34EA-4685-A9E0-9585BB4154C4',
 'A4000FD5-A794-45A5-BEB8-61D2306982AE__272DC108-A3C9-4CE7-A49D-5F2CB5A1EEB4',
 'A603C0DE-88A6-44EB-8998-A3063538C12A__AC2B694A-D64C-40D2-8507-B791008DBC92',
 'DA4A9DC0-9E92-459F-8879-3BA431BA014C__768D913D-C0EC-4DDA-816C-730B48511FF5',
 '7BA94229-597A-4A36-8446-671D06608A9B__659CE1E8-B857-4B30-99CB-0BBC3A21F296',
 '7757231C-98B6-402E-9970-7B4A9EF2231E__5D228169-2D95-4593-B6EC-AB6A9B9835D3',
 '59FE7386-7D41-44E9-BAF9-69C04C97FB9A__19BCF3A2-2F14-46F1-937E-5B988395C8BB',
 'B1C74206-C847-41A3-B046-9979D8E3BF1F__FCF7055C-5B2E-43AA-9287-6D9FA4DD162A',
 'C2EAC64E-EAB7-48C1-A750-45368DAFC169__C9A895CB-F577-44A3-8711-A5912D5409BC',
 '78A23B6D-3FEE-4AD8-A0FF-95B14BAB989C__E762E016-867F-4AA7-BA94-FB63690A0710',
 'E7B942BA-E3A5-46FB-BF08-37860A8399DE__54A59BF7-B9F9-41F3-9971-FDD9D1DD7D3B',
 '8F864B93-96F0-4A97-8B53-81193DD71363__2C1E5467-4A43-4FFF-9D12-5B50E666489D',
 '5E7E9804-C5CD-4173-9F99-11F1C2D4581E__9C584D4C-1DA5-4BFE-86C6-819233628863',
 '553B4A51-E10F-4E35-9B7D-77B264980CCE__311D6735-E622-409D-B842-95F822450838',
 '62A84F8E-DF8B-497E-B236-9F577AC8AFC7__0A543CAF-DEB7-473C-A775-0D47D3AA3B84',
 'A2A48F3E-DB8B-435E-A6B7-DDC304900DA5__5907814F-82ED-440D-8255-34F5985B37E7',
 '568A2A79-2778-4BDC-A509-87AF85ED827A__C0E5711C-5A8A-4A51-AA0B-BBC4BBA97E8B',
 '74394D4D-5070-498D-8D58-EB32F1E1807A__063C50F1-583E-4F7D-9E05-314E8DDEF289',
 '92FE6B01-8F6C-4B62-8700-DD157433989F__CD2BB9EB-81A7-4317-9DEE-C585D30F20AB',
 'EFD5A652-8BF1-471A-A9DD-D59424548E37__AA985F89-7A26-4B6E-9BC2-A929E88A5E16',
 '88040E1E-8D59-43C8-80A3-63D08779864F__76BF626D-EC6A-42D3-A4D5-05227707FB8F',
 'B79BAC94-0412-4C1D-8343-3620603A3300__76E822DF-D60E-4E2D-A5E4-760D3E44454E',
 '5E2CDB76-4959-4420-8D0C-41F35AA87A0D__9C0771FD-A660-4E1B-8EB1-9B3CEDE10CED',
 'CA0EE211-393B-46A4-8964-6F9D5E12F5C3__01A74739-9CE0-4F34-9630-5FD4A730DF21',
 '03E8481A-220C-4FD3-9A20-9726D149E139__44D25AFD-2495-4C92-9EC8-3E7CC89459DF',
 'E1F8E082-1572-4694-AC47-838AD26A0619__B50D2D2D-BBF9-4D92-9325-07CF3691B7A8',
 'FA04ECF8-B232-46A7-9353-F19B2945260B__C065CF1F-B088-42DE-A6C1-6F2F823F894A',
 '6AF322A5-8E41-46DF-8870-9B6A0B495490__4068E3F3-37FA-4D62-B4FA-C00459E00AFB',
 'CE8DD4E1-3CFB-4AB6-9A84-5D67F96D1494__0FA056D4-FDD2-4A23-B7F7-754476297D22',
 '04ADF349-294A-4556-AC66-4729D584E8A9__43FFB03F-73A4-4E26-A0B4-C3B5F063B3B2',
 'E651C119-8922-452E-8B42-4F42129FFEC6__031ABEAF-637D-4150-8A3B-0FF55C17EC4B',
 '21E23205-43AE-4C47-A7C9-E3B57F2C42B0__E6498C05-8C2F-4B2A-BF1A-870867DC29BF',
 'A2CA9CC0-B216-4C41-8069-8F005C8F1B79__E764D8E3-3D75-429C-88C9-CD48E77B867F',
 'F2831783-153D-454D-87B4-378367B385A2__000B2776-12B9-47D9-A9AA-4F05910B96B5',
 '7CD50FDA-28D6-41F4-A4DC-E5B6323842F0__A4198992-D260-476F-8181-B5F25CD0FA1B',
 '8AB48F85-D4E2-4D54-8BFF-D7ED8413182C__134180C9-A842-4D33-8046-6FD86DDAF133',
 '25D558ED-6FA8-4404-A0BF-4B167B813013__C54153A5-301D-4BAA-816B-C3C2D7723DFC',
 '8537B9AF-DA5D-49EC-B4FD-D57C28E6561F__728D7751-09EB-43F0-BBB8-3943D84989C2',
 '5DDA7789-23BF-41AD-9EB2-BF18BBEDABE6__7BEDEA12-0D9C-46A4-B318-3BB1736983B9',
 '5AA324DF-BED1-4ECB-851D-0B65683A7229__98397F10-7D25-4AE3-A14D-C948F3284B17',
 'FF895B4F-10BE-45BA-BC24-977321CC5ED0__5F0DEB7C-A0B0-4A95-87EC-0DBA87CC4EC7',
 '96011B51-4E7B-4087-8590-5F981EE21D80__07D9CAF8-6866-48D6-A3CD-3985AABCBC3C',
 'CA41A6F4-1AA4-405A-9E79-9D42F05A4C3B__D69F0A6B-2F41-416D-9C12-EB216FAFE0B8',
 '7BC13F37-D7F4-4EAA-80DD-69B1CC252E7C__6CEAF0C8-D629-4F71-B92B-359545D590D6',
 '44EB2215-428C-4D49-A627-914B591E37FB__C9007737-09D6-4872-9D06-F5F6978D127E',
 '17FB8E28-1EA8-47A2-97DF-93CEA9DF27F9__2AA53884-171B-4725-83E4-97FAE9F06530',
 '6DBC95EB-6763-4E56-A315-FE6C8E171F7C__2C1919BB-2A65-4F87-83B2-23F04BEE91D1',
 'D839B14E-9F34-44FE-8055-651686E1168D__E63441CC-73E5-4224-A08A-C7355D044C41',
 '6DF28BFD-3868-4C4A-8898-89179F23D636__3821D662-5C5C-4D08-8C6D-F591E66C7A0A',
 '759A1104-914A-499D-A728-5BBAA73DD741__1E515406-4C4B-4303-806D-716E9350FB2F',
 'F9E387DE-0490-495D-BB1D-51A931ED2198__5D24C2D2-201A-42BF-AECA-CBE55655ABF1',
 '942E9624-7156-4932-BB19-4BCC64135CDE__FDDB0A05-56C3-46A2-8745-755748DB1CA0',
 'EA79315E-B87C-40F0-ABF4-D790012DAC15__36D81B0D-A7B8-4C39-BEA7-BF4891C27C66',
 '8B5D025E-A3D8-4576-9B14-ED72D47EE50D__1E25D85E-0CB5-4E86-BF7E-A11BE4097061',
 '3AE85D62-2DDD-4B67-972B-35C39F1559FD__C87543F3-1B29-4CA4-9F46-037C4E3B252F',
 '987AFE8B-6393-420B-9BC1-ED4BCA83932F__1AD8F75C-259F-41D5-A0C1-8B71A6D004C3',
 '31F8FDF0-F901-4D6E-83AC-4DD6DE889FF6__3D9A7E6F-B397-4495-8138-5D2E2BED3CE8',
 '6250B325-8021-46D8-B227-CDAD00DF510E__524B3E76-DBFB-46D2-92F9-E1DBB4AA3B0B',
 '5362E4C8-1C53-4EA7-A91C-1D73D6C8219B__CD7E09DE-2416-4C53-8236-9E44A457D5BF',
 '8B734D79-5BF0-4CA2-9FCC-095D6846BA8B__0F0FE521-5C85-4042-BF4E-D1F440EDC980',
 '81166184-0F95-401E-8203-610223F4AA3C__FBB4FC05-F8DF-48BA-894E-056097B5E502',
 'E5A8AC89-6FF7-43E0-80E9-1B4819AD484B__5CC480DE-BA6E-4F77-A6B3-31777A18D45A',
 '4754AD35-6B7F-4679-BFB5-6B557B952B25__2F1E6653-4E03-4B1A-943E-17A1C6D4F952',
 '635CDEAB-8C67-448F-9E3D-5F779F2A803D__3C626F66-8636-4C2A-839F-F9CC0D7EF3BF',
 '28CDB8B1-0D29-4D8D-AB7D-CB4CE42E430D__CB139B90-BE01-4571-88AF-BB3CE50A4745',
 '33CC543C-7DCC-443A-A259-C3FC287A557A__60B3F829-1CED-421E-86DC-0F8A59679BD5',
 '8AEFC7C7-5F69-4988-A620-814CCB9E9E2C__6B0C3394-5D90-4F16-9286-5121058EB860',
 '8E601B6D-848E-4763-8ECD-698E77865413__7238BC92-3610-4D57-B471-8B29C9E9176E',
 'FBBB2ED6-1D1D-48E3-B5FC-ABD0115482BA__D8FED7AC-B836-4948-9471-131C194642F7',
 'A2432923-2D75-43DF-A226-9500E92298FB__FE924F98-7F83-45E9-8DB8-031F7348D543',
 'BC899544-EDBE-4DB8-B03E-E30E5E4774C6__B22A304E-1DC8-4D23-8929-9FCCC57E3346',
 'C960BBAB-DA98-46FC-B01F-2108E90BA2B7__A2D58174-1C35-41F8-B104-89B4E58C1858',
 'E65B6685-E385-4686-B0C8-BDA677F49A5F__672CF5BB-587D-4AE4-8890-FB60AFBDD62D',
 '5F23A60D-18E9-40F1-813A-B7426D546B3F__EBFD0829-6AFA-4D93-A845-0B0C24025EF4',
 '61DC50C4-6AA2-48FD-97A3-6D657AF536BD__E88E656D-17C9-4F20-8454-AF38B4BFC5C8',
 '2A4A130F-4C55-457B-8C23-3B14793C3603__87753723-D129-480D-9677-F344D709B79D',
 'C0FD144E-FAC4-41F0-AC4D-7B50F82F694D__C79739DA-E9C4-4372-B4D9-8140D2520AE0',
 '7D95C756-B378-46A4-AFB7-A1DA34077797__090BAAC9-D6BF-4ED3-893A-EFFD9FBDDA56',
 'FFEF6F8D-66E0-42F3-B82D-9B55EF637F01__4243A261-686A-472F-AE63-D31B271DD1AB',
 '5A3CFD18-F7B0-4BE7-ACD5-ABAA59160333__C00C36F3-F1C5-4C24-AC97-DB87D5681A67',
 '28BC3572-41C1-466F-850D-5F7E798DCB01__E6AE945D-874C-405D-9FA4-3F63743664AB',
 '0D2B48CC-512F-469D-B93D-CDDF9CB0D39C__BE29D15F-9C5C-457E-831C-2772C22FEFCE',
 'D3D3D421-A327-48B0-BC66-17C4BB1F503F__A6B6E445-91E2-4F6C-BC4D-8BEA2F10987A',
 '87731ADE-3E6E-4787-AAFA-1760086BD57B__C994EF97-FA5C-46B0-88A0-4B94ECCDEB36',
 'D2F252BB-29EC-42CC-A488-2D620B890F23__782EDFEE-E949-4A36-A79A-0AC488F0BB0D',
 '010B77F8-FAFF-4782-8285-55F0C176F8BC__0D03C985-77C5-4022-A6F1-8BC9D68AF46C',
 'B9B6D6EC-5C7D-4E7D-942F-142F28FAC759__C4FD8334-4D87-4393-8D1F-BD4043F8E3E5',
 '93C78C75-BB2C-46D4-A2E9-67C3C124B0C4__829697AC-9D67-4BD6-8CD2-CB663F1A147C',
 '56ECDFA9-3D9F-43E2-BD56-DF52179EA90C__4AEE3C1F-2158-42E5-BCE3-6F9DD4D62B90',
 'CD0135EA-9B85-4421-9B5A-D9BFB36E86AE__B338C7C5-351F-4086-9DF8-CCBED77DC8E5',
 '37C7EB02-8F89-4115-88DE-53BD189E08C8__7D8BC741-9650-41E1-9831-2DC45E4B75D2',
 '0828A012-8E54-4870-9A5C-17BCCD77257E__D88086A2-14F6-4D65-BA61-F9D1B718D446',
 '064C6594-5C4B-458F-9BE9-BBA61349E9C4__5CD72F18-A2D0-4B3B-BF27-F991639E6DB6',
 'CA53F78E-B255-48AD-86C4-03AB9525FA6C__C0CF3DA8-E333-4F16-975A-8BE13CA06B4E',
 '63A195B3-B35C-4647-A4F8-D0CF9E175C32__56427142-C38B-490B-9114-688F84648281',
 '1616FA84-470D-4BA7-BF69-5D4D406C7438__ACFE129E-4468-4062-A680-094E31750CF9',
 '3E7C2DB7-C8D8-4CBD-98D7-F4E910B613C8__C6FBF1D5-760D-497E-B006-39BC7582B7D7',
 '2B5C0154-F1E3-4E2D-80DD-278D21245C74__1C52CB11-CA52-44B8-B0B8-1F74E4FF65A6',

In [36]:
not_in_spine = set(june_keys) - set(spine_keys)

In [37]:
(int_customers[int_customers["customer_id"].isin(df["CustomerCustomerID"].to_list())].shape,
int_vehicles[int_vehicles["customer_id"].isin(df["CustomerCustomerID"].to_list())].shape,
int_vehicles[int_vehicles["customer_vehicle_id"].isin(df["CustomerVehicleID"].to_list())].shape,)

((722954, 20), (724975, 15), (724975, 15))

In [38]:
int_customers_vehicles = pd.merge(
    int_customers,
    int_vehicles,
    on="customer_id",
    how="outer",
    suffixes=["_customer", "_vehicle"]
)

In [39]:
int_customers_vehicles["key"] = int_customers_vehicles["customer_id"] + "__" + int_customers_vehicles["customer_vehicle_id"]

In [40]:
# int_customers_vehicles["is_in_current_database"] = np.where(int_customers_vehicles["key"].isin(june_keys), True, False)
# int_customers_vehicles["is_not_in_current_database"] = np.where(int_customers_vehicles["key"].isin(not_in_spine), True, False)#

In [41]:
int_customers_vehicles.to_csv("int_customers_vehicles.csv", sep=";", header=True, index=False)

In [42]:
june_df = pd.DataFrame(june_keys, columns=["key"])
june_df[["customer_id", "customer_vehicle_id"]] = june_df["key"].str.split("__", expand=True)
june_df["is_key_in_june_db"] = np.where(june_df["key"].isin(spine_keys), True, False)
june_df["is_customer_in_june_db"] = np.where(june_df["customer_id"].isin(int_customers["customer_id"].unique().tolist()), True, False)
june_df["is_vehicle_in_june_db"] = np.where(june_df["customer_vehicle_id"].isin(int_vehicles["customer_vehicle_id"].unique().tolist()), True, False)
june_df.head()

,key,customer_id,customer_vehicle_id,is_key_in_june_db,is_customer_in_june_db,is_vehicle_in_june_db
0,7C91BC19-1D00-4E78-BC20-00E34BF0F603__A903410B...,7C91BC19-1D00-4E78-BC20-00E34BF0F603,A903410B-FE0B-42B1-8457-AAE13D28274A,False,True,True
1,5A709836-8C3C-43E9-9C5E-0130C45A816E__25916B80...,5A709836-8C3C-43E9-9C5E-0130C45A816E,25916B80-ECB5-4995-9DEC-E33007D1EC8C,True,True,True
2,1936F708-B424-4276-B5E8-0001116F66D0__9796EE0B...,1936F708-B424-4276-B5E8-0001116F66D0,9796EE0B-70E9-4044-91F5-097313AA806A,False,True,False
3,1936F708-B424-4276-B5E8-0001116F66D0__6A8970C3...,1936F708-B424-4276-B5E8-0001116F66D0,6A8970C3-50DC-40C4-B2DD-0D644801B1DE,False,True,False
4,1936F708-B424-4276-B5E8-0001116F66D0__BD5105BE...,1936F708-B424-4276-B5E8-0001116F66D0,BD5105BE-26B6-4B4A-8570-152EE1D912BC,True,True,True

In [43]:
june_df.to_csv("june_transactions_hash_info.csv", sep=";", header=True, index=False)

In [44]:
(
    int_customers_vehicles[int_customers_vehicles["customer_id"].isin(df["CustomerCustomerID"].to_list())].shape,
    int_customers_vehicles[int_customers_vehicles["customer_vehicle_id"].isin(df["CustomerVehicleID"].to_list())].shape,
    int_customers_vehicles[int_customers_vehicles["key"].isin(df["key"].to_list())].shape,)

((726781, 35), (726769, 35), (727266, 35))

In [45]:
int_customers_vehicles[int_customers_vehicles["customer_id"].isin(df["CustomerCustomerID"].to_list())].head()

,customer_id,creation_on_customer,modified_on_customer,user_title,customer_name,mobile,mobile2,email,gender,nationality,...,model_year,transmission_type,pms_name,plate_number,code_vin,is_driver_owner,station_brand_vehicle,is_truck,vehicle_brand_level,key
10,00001637-465A-4255-87B8-05E30B8F31AD,2025-06-19,2025-07-24,MR.,MOPER,0537608892,None,None,Male,None,...,2013.0,AUTOMATIC,TOYOTA,8741VBJ,6T1BF9FK9DX479150,True,PE,0.0,HIGH,00001637-465A-4255-87B8-05E30B8F31AD__63284329...
12,00001CA5-294A-4B26-A4A1-A77D7B5B18CC,2024-06-07,2025-08-12,MR.,MR.FAIF,0571317927,None,None,Male,Indian,...,2011.0,AUTOMATIC,HYUNDAI,8123UEB,KMHDT41B5BU252737,True,PE,0.0,OTHER,00001CA5-294A-4B26-A4A1-A77D7B5B18CC__9946561B...
23,0000342D-088A-46C1-A438-A92F18B8E6F9,2024-12-24,2025-06-19,None,SALAM ELITE GENERAL CONTRACTING EST,0510119570,None,None,Male,None,...,2007.0,MANUAL,None,0723TKX,MPAEL33C47H507796,True,PE,0.0,OTHER,0000342D-088A-46C1-A438-A92F18B8E6F9__21093DF1...
51,00006F00-68A6-463A-BE64-C39D67D6B860,2025-08-02,2025-08-02,MR.,MISK DECORATION RAC,0563772788,None,None,Male,None,...,2023.0,AUTOMATIC,HYUNDAI,3654HRR,MF3PB8122PJ053936,True,PE,0.0,OTHER,00006F00-68A6-463A-BE64-C39D67D6B860__496D5E7A...
52,00007206-C3D7-423B-A610-DF222532131F,2021-12-16,2025-06-28,MR.,MR TALAL,0536423306,None,None,Male,Saudi,...,2016.0,AUTOMATIC,MAZDA,4263ZUJ,JM7TB1MA6G0441910,True,PE,0.0,OTHER,00007206-C3D7-423B-A610-DF222532131F__4FC0FA97...

In [46]:
int_customers_vehicles[int_customers_vehicles["key"].isin(df["key"].to_list())].head()

,customer_id,creation_on_customer,modified_on_customer,user_title,customer_name,mobile,mobile2,email,gender,nationality,...,model_year,transmission_type,pms_name,plate_number,code_vin,is_driver_owner,station_brand_vehicle,is_truck,vehicle_brand_level,key
10,00001637-465A-4255-87B8-05E30B8F31AD,2025-06-19,2025-07-24,MR.,MOPER,0537608892,None,None,Male,None,...,2013.0,AUTOMATIC,TOYOTA,8741VBJ,6T1BF9FK9DX479150,True,PE,0.0,HIGH,00001637-465A-4255-87B8-05E30B8F31AD__63284329...
12,00001CA5-294A-4B26-A4A1-A77D7B5B18CC,2024-06-07,2025-08-12,MR.,MR.FAIF,0571317927,None,None,Male,Indian,...,2011.0,AUTOMATIC,HYUNDAI,8123UEB,KMHDT41B5BU252737,True,PE,0.0,OTHER,00001CA5-294A-4B26-A4A1-A77D7B5B18CC__9946561B...
23,0000342D-088A-46C1-A438-A92F18B8E6F9,2024-12-24,2025-06-19,None,SALAM ELITE GENERAL CONTRACTING EST,0510119570,None,None,Male,None,...,2007.0,MANUAL,None,0723TKX,MPAEL33C47H507796,True,PE,0.0,OTHER,0000342D-088A-46C1-A438-A92F18B8E6F9__21093DF1...
51,00006F00-68A6-463A-BE64-C39D67D6B860,2025-08-02,2025-08-02,MR.,MISK DECORATION RAC,0563772788,None,None,Male,None,...,2023.0,AUTOMATIC,HYUNDAI,3654HRR,MF3PB8122PJ053936,True,PE,0.0,OTHER,00006F00-68A6-463A-BE64-C39D67D6B860__496D5E7A...
52,00007206-C3D7-423B-A610-DF222532131F,2021-12-16,2025-06-28,MR.,MR TALAL,0536423306,None,None,Male,Saudi,...,2016.0,AUTOMATIC,MAZDA,4263ZUJ,JM7TB1MA6G0441910,True,PE,0.0,OTHER,00007206-C3D7-423B-A610-DF222532131F__4FC0FA97...

In [47]:
customer_id = "81F8CFE1-3DC9-4B4E-9C69-4F54A3A64ECC"

In [48]:
int_customers_vehicles[int_customers_vehicles["customer_id"] == customer_id]["key"].to_list()

['81F8CFE1-3DC9-4B4E-9C69-4F54A3A64ECC__62EBADB1-C332-43E0-818C-35D86661FA55']

In [49]:
df[df["CustomerCustomerID"] == customer_id]["key"].to_list()

['81F8CFE1-3DC9-4B4E-9C69-4F54A3A64ECC__62EBADB1-C332-43E0-818C-35D86661FA55']

In [50]:
int_customers_vehicles[int_customers_vehicles["customer_id"] == customer_id].T

                                                                    3684173
customer_id                            81F8CFE1-3DC9-4B4E-9C69-4F54A3A64ECC
creation_on_customer                                    2025-02-09 00:00:00
modified_on_customer                                    2025-07-24 00:00:00
user_title                                                             None
customer_name                                                       IBRAHIM
mobile                                                           0555206587
mobile2                                                                None
email                                                                  None
gender                                                                 Male
nationality                                                           Saudi
birth_date                                              1900-01-01 00:00:00
location_name                                                       CR EAST
is_owner                                                              False
is_cash_customer                                                       True
payterm                                                                None
age                                                                     NaN
is_active                                                              True
consent_status                                                          1.0
consent_acquisition_date                                2025-07-24 00:00:00
station_brand_customer                                                   PE
customer_vehicle_id                    62EBADB1-C332-43E0-818C-35D86661FA55
creation_on_vehicle                                     2025-02-09 00:00:00
modified_on_vehicle                                     2025-02-09 00:00:00
maker                                                                TOYOTA
model                                                                 YARIS
model_year                                                           2024.0
transmission_type                                                 AUTOMATIC
pms_name                                                             TOYOTA
plate_number                                                        8899LLR
code_vin                                                  MR2BE9B32R0082177
is_driver_owner                                                       False
station_brand_vehicle                                                    PE
is_truck                                                                0.0
vehicle_brand_level                                                    HIGH
key                       81F8CFE1-3DC9-4B4E-9C69-4F54A3A64ECC__62EBADB1...

In [51]:
# df[df["CustomerID"] == customer_id].T

In [52]:
june_keys[:5]

['7C91BC19-1D00-4E78-BC20-00E34BF0F603__A903410B-FE0B-42B1-8457-AAE13D28274A',
 '5A709836-8C3C-43E9-9C5E-0130C45A816E__25916B80-ECB5-4995-9DEC-E33007D1EC8C',
 '1936F708-B424-4276-B5E8-0001116F66D0__9796EE0B-70E9-4044-91F5-097313AA806A',
 '1936F708-B424-4276-B5E8-0001116F66D0__6A8970C3-50DC-40C4-B2DD-0D644801B1DE',
 '1936F708-B424-4276-B5E8-0001116F66D0__BD5105BE-26B6-4B4A-8570-152EE1D912BC']

In [53]:
spine_keys[:5]

['F2C15320-6631-4AB8-A411-735558AF6ED1__5699B579-284B-4D04-AAB2-85538114C985',
 'E52E3304-54BE-4714-999C-CBB8EA4CC679__4503EB70-84AC-45FB-AD03-F50B760D30EA',
 'F62DC5D6-3BE7-495B-AE0D-C1AC7810B603__9771935F-BB72-427A-8153-BB90B9D81A35',
 '21040B24-953B-4F58-A977-B52FCADC4E46__9315AD3E-4B21-4DB2-A9DA-1510B87A8E3D',
 '374FA0D5-EEEC-4E71-8C81-7162A03EAC1C__6FB40EB3-95DF-4BEE-A29B-2363A2FF0678']

In [54]:
[col for col in spine_keys if col == 'F29365E5-3105-47DF-B6CD-00E1B187656C__F29365E5-3105-47DF-B6CD-00E1B187656C']

[]

In [55]:
df["CustomerCustomerID"].isna().sum(), df["VehicleCustomerID"].isna().sum()

(0, 12)

In [56]:
df["CustomerID"] = df["CustomerCustomerID"]
df["CustomerID"] = np.where(df["CustomerID"].isna(), df["VehicleCustomerID"], df["CustomerID"])

In [57]:
df.shape

(765370, 31)

In [58]:
df["new_mobile"] = df["Mobile"].astype(str).str.zfill(10)
df["new_mobile"] = df["Mobile"].str.replace("^0", "966", regex=True)

In [59]:
df["plate_number"] = df["PlateNumber"].str.zfill(7)

In [60]:
df["_id"] = df["plate_number"] + "__" + df["new_mobile"].astype("str")

In [61]:
len(mobile_list), len(set(mobile_list))

(242363, 218955)

In [62]:
df[(df["Mobile"].isin(mobile_list)) & (df["CustomerModifiedOn"] > "2025-06-01")].drop_duplicates("Mobile").shape

(213496, 34)

In [63]:
len(plate_list), len(set(plate_list))

(63100, 60778)

In [64]:
df[(df["PlateNumber"].isin(plate_list)) & (df["VehicleModifiedOn"] > "2025-06-01")].drop_duplicates("PlateNumber").shape

(9972, 34)

In [65]:
len(id_list), len(set(id_list))

(179216, 169002)

In [66]:
df[(df["_id"].isin(id_list))].drop_duplicates("_id").shape

(162791, 34)

In [67]:
(df["VehicleModifiedOn"] > "2025-06-01").sum()

272440

In [68]:
audit_df[audit_df["mobile"] == 966052254203].T

                                                                   146905
_id                                                 8893JGD__966052254203
plate_number                                                      8893JGD
mobile                                                       966052254203
index                                                              215046
valid_mobile                                                            1
valid_plate                                                             1
valid_id                                                                1
n_customer_id_mobile_db                                                 0
min_customer_creation_on_mobile_db                                    NaN
min_customer_modified_on_mobile_db                                    NaN
n_plate_number_mobile_db                                                0
is_correct_plate_on_mobile_db                                         0.0
n_customer_vehicle_id_plate_db                                          1
min_vehicle_creation_on_plate_db                               2021-03-12
min_vehicle_modified_on_plate_db                               2020-09-25
n_mobile_plate_db                                                       1
is_correct_mobile_on_plate_db                                           0
found_correct_id                                                        0
not_found_correct_id                                                    1
nothing                                                                 0
not_found_correct_id__notvalid_plate_notvalid_m...                      0
not_found_correct_id__valid_plate_notvalid_mobile                       0
not_found_correct_id__notvalid_plate_valid_mobile                       0
not_found_correct_id__valid_id                                          1
not_found_correct_id__exist_mobile_notexist_plate                       0
not_found_correct_id__exist_plate_notexist_mobile                       1
not_found_correct_id__notexist_plate_notexist_m...                      0
not_found_correct_id__exist_plate_exist_mobile                          0

In [69]:
df[df["PlateNumber"] == "8893JGD"].T

                                                               263661
CustomerCustomerID               115ED86B-9445-4D62-9711-59A7B9D92B3D
CustomerCreationOn                                2021-03-12 00:11:18
CustomerModifiedOn                                2025-06-24 18:47:11
UserTitle                                                         Mr.
CustomerName                                              ABDULLAHSIS
Mobile                                                              0
Mobile2                                                          None
Email                                                            None
Gender                                                           Male
Nationality                                                     Saudi
BirthDate                                                        None
LocationName                                                     None
IsOwner                                                         False
IsCashCustomer                                                   True
PayTerm                                                          None
Age                                                               NaN
IsActive                                                         True
CustomerVehicleID                9176DEF9-1B81-4CC8-A311-7D99ECBB7294
VehicleCreationOn                                 2021-03-12 00:11:44
VehicleModifiedOn                                 2020-09-25 00:02:40
VehicleCustomerID                115ED86B-9445-4D62-9711-59A7B9D92B3D
Make                                                              KIA
Model                                                          OPTIMA
ModelYear                                                      2020.0
TransmissionType                                            Automatic
PMSName                                                           KIA
PlateNumber                                                   8893JGD
VIN                                                 KNAGT4145L5350548
IsDriverOwner                                                    True
key                 115ED86B-9445-4D62-9711-59A7B9D92B3D__9176DEF9...
CustomerID                       115ED86B-9445-4D62-9711-59A7B9D92B3D
new_mobile                                                        966
plate_number                                                  8893JGD
_id                                                      8893JGD__966

In [70]:
cursor.execute(f"""
    SELECT 
       a.CustomerID as CustomerCustomerID, a.CreationOn as CustomerCreationOn, a.ModifiedOn as CustomerModifiedOn, UserTitle, CustomerName,
       Mobile, Mobile2, Email, Gender, Nationality, BirthDate,
       LocationName, IsOwner, IsCashCustomer, PayTerm, Age,
       IsActive, CustomerVehicleID, b.CreationOn as VehicleCreationOn, b.ModifiedOn as VehicleModifiedOn,
       b.CustomerID as VehicleCustomerID, Make, Model, ModelYear, TransmissionType,
       PMSName, PlateNumber, VIN, IsDriverOwner
    FROM MACDB.dbo.v_Customer a
    FULL OUTER JOIN MACDB.dbo.v_Vehicle b
    ON a.CUSTOMERID = b.CUSTOMERID
    WHERE 
        PlateNumber = '8893JGD'
""")
rows = cursor.fetchall()

pd.DataFrame.from_records(rows, columns=[col[0] for col in cursor.description])

,CustomerCustomerID,CustomerCreationOn,CustomerModifiedOn,UserTitle,CustomerName,Mobile,Mobile2,Email,Gender,Nationality,...,VehicleModifiedOn,VehicleCustomerID,Make,Model,ModelYear,TransmissionType,PMSName,PlateNumber,VIN,IsDriverOwner
0,115ED86B-9445-4D62-9711-59A7B9D92B3D,2021-03-12 00:11:18,2025-06-24 18:47:11,Mr.,ABDULLAHSIS,0,None,None,Male,Saudi,...,2020-09-25 00:02:40,115ED86B-9445-4D62-9711-59A7B9D92B3D,KIA,OPTIMA,2020,Automatic,KIA,8893JGD,KNAGT4145L5350548,True

In [71]:
len(set(mobile_list) - set(df["Mobile"].to_list()))

5459

In [72]:
cursor = conn.cursor()
cursor.execute("""
SELECT 
   COUNT(*)
  FROM MACDB.dbo.v_Vehicle
  WHERE 
        YEAR(ModifiedOn) = 2025 and
        MONTH(ModifiedOn) = 6
""")
rows = cursor.fetchall()
rows

[(77739,)]

In [73]:
min_date = rows[0][0]
max_date = datetime.date.today()

In [74]:
cursor.description

(('', int, None, 10, 10, 0, True),)

In [92]:
cursor = conn.cursor()

In [76]:
mobile_list = [
"0534868810",
"0534868810",
"0567420577",
"0534868810",
"0568479675",
"0509019295",
"0507784339",
"0590962915",
"0590713214",
"0590713214",
"0590713214",
"0532751873",
"0530596337",
"0530596337",
"0533369046",
"0570650452",
"0577546965",
"0566588717",
"0566588717",
"0590663172",
"0572890264",
"0508982236",
"0565013507",
"0541516056",
"0502983952",
"0594268646",
"0594268646",
"0545211455",
"0508983078",
"0569782772",
"0569782772",
"0569782772",
"0506751752",
"0581175172",
"0593781408",
"0595251898",
"0509089015",
"0580718833",
"0596379556",
"0581175172",
"0548429101",
"0571847620",
"0531916342",
"0556308343",
"0597275824",
"0580043114",
"0557106932",
"0558101320",
"0540994641",
"0501168514",
"0500701965",
"0551327634",
"0557351452",
"0530189132",
"0595251898",
"0502438825",
"0537152881",
"0545639381",
"0593585211",
"0593585211",
"0593563209",
"0593563209",
"0593563209",
"0593563209",
"0502954883",
"0541675325",
"0509698713",
"0566963109",
"0501048877",
"0544168370",
"0554776497",
"0560612786",
"0503631304",
"0554100521",
"0503802158",
"0508169275",
"0509940285",
"0501992184",
"0542658041",
"0540444104",
"0558110532",
"0547093161",
"0591423648",
"0556677243",
"0507221481",
"0502977451",
"0596070573",
"0501974566",
"0599512360",
"0545964972",
"0509901726",
"0599053036",
"0574947960",
"0574947960",
"0564046631",
"0571053120",
"0559499178",
"0552153002",
"0552153002",
"0558478163",
"0597132122",
"0573632586",
"0573632586",
"0542183128",
"0598112233",
"0535407150",
"0535407150",
"0576389319",
"0506821206",
"0504870190",
"0591710119",
"0511762132",
"0532418973",
"0532418973",
"0530085267",
"0549798483",
"0583269400",
"0533088420",
"0509330669",
"0582769203",
"0560074821",
"0560074821",
"0560074821",
"0535510791",
"0535510791",
"0569517998",
"0571127488",
"0571127488",
"0511546549",
"0595924834",
"0594850888",
"0505276744",
"0505276744",
"0539081537",
"0510366354",
"0581424570",
"0564316356",
"0558336741",
"0541956157",
"0533247455",
"0581482931",
"0581482931",
"0595251898",
"0533247455",
"0557345909",
"0502542143",
"0572262603",
"0502542143",
"0502542143",
"0502542143",
"0502542143",
"0559878790",
"0509731200",
"0509731200",
"0570310238",
"0581482931",
"0506215448",
"0561958152",
"0556308343",
"0534372092",
"0590782069",
"0540018375",
"0595251898",
"0538959749",
"0538959749",
"0590436503",
"0502518350",
"0507976759",
"0550629621",
"0570786866",
"0563010779",
"0563010779",
"0563941557",
"0551920222",
"0539018393",
"0557851008",
"0550254836",
"0593575987",
"0504870190",
"0583963353",
"0593332170",
"0537325002",
"0537325002",
"0557832889",
"0595374432",
"0507221481",
"0558559629",
"0501661310",
"0544920657",
"0053587587",
"0545024665",
"0545024665",
"0500355593",
"0509424497",
"0557728285",
"0540666552",
"0500980465",
"0555528127",
"0555455721",
"0555667147",
"0570606724",
"0583644143",
"0560787053",
"0054115187",
"0532415005",
"0533902906",
"0503183332",
"0566576227",
"0560656616",
"0505826554",
"0546024460",
"0506667330",
"0530357505",
"0540734335",
"0540734335",
"0504232591",
"0500200612",
"0555266112",
"0546864775",
"0592870717",
"0592870717",
"0053000455",
"0053000455",
"0505262046",
"0591011333",
"0591011633",
"0505729467",
"0591011633",
"0591011633",
"0509303828",
"0570700561",
"0570700561",
"0570700561",
"0050458514",
"0531516220",
"0531516220",
"0566915831",
"0502259998",
"0595384280",
"0501938306",
"0506767617",
"0534298083",
"0549736229",
"0549736229",
"0500010748",
"0555402804",
"0500447380",
"0591426888",
"0545649077",
"0552983411",
"0056836433",
"0544430804",
"0591042403",
"0532227222",
"0532227222",
"0555575977",
"0551299336",
"0594987979",
"0509406962",
"0544585314",
"0596122744",
"0544194633",
"0551745514",
"0538915196",
"0560350966",
"0500787879",
"0509672232",
"0510133457",
"0503666128",
"0503666128",
"0569297915",
"0500739505",
"0559957116",
"0532061113",
"0500309444",
"0503873565",
"0551911217",
"0531840680",
"0558004787",
"0500939331",
"0533320412",
"0592129202",
"0554485544",
"0550161615",
"0050373775",
"0576867000",
"0532989633",
"0577692826",
"0567235368",
"0551943380",
"0552497190",
"0535182043",
"0535182043",
"0533221831",
"0505148587",
"0504880132",
"0582122536",
"0504733799",
"0554487233",
"0055077744",
"0593441144",
"0566002210",
"0055288897",
"0502887879",
"0505452587",
"0555037774",
"0543440328",
"0543440328",
"0508273457",
"0501556332",
"0583346667",
"0554487233",
"0552035477",
"0504724100",
"0542942477",
"0544696834",
"0534700534",
"0543590240",
"0509919686",
"0509919606",
"0566158150",
"0567070136",
"0055672821",
"0540654635",
"0555346993",
"0555565434",
"0555902690",
"0756253354",
"0562533541",
"0505705409",
"0546329392",
"0556622153",
"0503481110",
"0574146457",
"0582893493",
"0599960005",
"0535522334",
"0534984344",
"0555137516",
"0508755222",
"0551745514",
"0555016621",
"0565843036",
"0565843036",
"0508755222",
"0505440189",
"0567601315",
"0500286100",
"0592279871",
"0541352404",
"0503324051",
"0532389901",
"0503815508",
"0503082819",
"0053053856",
"0053200446",
"0531808863",
"0555529880",
"0543441213",
"0556353535",
"0562993807",
"0546401009",
"0505202894",
"0506236138",
"0598684844",
"0050559541",
"0508755222",
"0596403747",
"0554446942",
"0554446942",
"0502987041",
"0564611101",
"0502987041",
"0568062446",
"0568995505",
"0551534415",
"0552882261",
"0535840265",
"0508517151",
"0530012232",
"0056412004",
"0553366170",
"0551855064",
"0533444343",
"0504191156",
"0544090972",
"0541119617",
"0555913775",
"0555913775",
"0540494415",
"0501201906",
"0500046754",
"0566587634",
"0566609410",
"0530251704",
"0503622216",
"0556136648",
"0500020667",
"0545661144",
"0552459551",
"0593552775",
"0555000185",
"0531065526",
"0558355404",
"0504239415",
"0509322241",
"0504460606",
"0537576746",
"0544875331",
"0502742936",
"0557757892",
"0502743945",
"0562392888",
"0508758281",
"0580071030",
"0532387909",
"0555901265",
"0508152929",
"0555521682",
"0555521682",
"0598684844",
"0598888915",
"0580011252",
"0503623924",
"0502158979",
"0502158979",
"0555631936",
"0505537085",
"0554532326",
"0547365040",
"0594477259",
"0503125648",
"0555512926",
"0555512926",
"0566701999",
"0508755222",
"0505616362",
"0560301010",
"0544039522",
"0507993491",
"0530800878",
"0503193640",
"0556824066",
"0595922249",
"0536750067",
"0505543606",
"0505920231",
"0505920231",
"0053602682",
"0557368291",
"0599444544",
"0599444544",
"0053263674",
"0534655293",
"0546073906",
"0501844636",
"0530539916",
"0536582332",
"0538801931",
"0509963988",
"0560388612",
"0552752550",
"0506640653",
"0560388612",
"0546868767",
"0059482111",
"0560388612",
"0505900778",
"0533973632",
"0567247839",
"0502705344",
"0556297421",
"0557061629",
"0501048877",
"0532167558",
"0532167558",
"0532929914",
"0505428482",
"0565666192",
"0509695649",
"0542998080",
"0558931651",
"0505699034",
"0557696131",
"0534421861",
"0538476957",
"0053000455",
"0507899438",
"0560025287",
"0538831191",
"0543152317",
"0597036352",
"0547199888",
"0551534415",
"0508032650",
"0557465070",
"0555373287",
"0555373287",
"0555517714",
"0552778965",
"0506205901",
"0059995539",
"0059995539",
"0599955393",
"0557209939",
"0544483131",
"0570308725",
"0554784158",
"0503079485",
"0538985811",
"0555777605",
"0555777605",
"0539300462",
"0536466486",
"0544840973",
"0544840973",
"0555255873",
"0598917170",
"0548601865",
"0561141151",
"0563776699",
"0549830919",
"0572181799",
"0509872381",
"0532331191",
"0560388612",
"0503421811",
"0503011557",
"0540009095",
"0570667033",
"0570667033",
"0569995617",
"0554770494",
"0890988008",
"0506431471",
"0502209020",
"0552100442",
"0558092069",
"0560388612",
"0565368886",
"0532385030",
"0532385030",
"0559644430",
"0555585772",
"0570150208",
"0560388612",
"0558737239",
"0554216664",
"0500779299",
"0583020769",
"0500755594",
"0556627181",
"0563584367",
"0570617820",
"0566341166",
"0545363011",
"0536466486",
"0500491145",
"0550695175",
"0502588840",
"0531567776",
"0535370772",
"0554197002",
"0508338283",
"0508338283",
"0543113361",
"0555369432",
"0560022134",
"0540025844",
"0538580589",
"0510654410",
"0507144879",
"0503562698",
"0552984957",
"0538826202",
"0540025844",
"0569650019",
"0541349956",
"0509428939",
"0559585850",
"0532208121",
"0542281696",
"0542111213",
"0569717886",
"0569717886",
"0555534448",
"0569717886",
"0504945836",
"0505496525",
"0550997130",
"0550997130",
"0550997130",
"0505245557",
"0555200463",
"0561731010",
"0534628526",
"0503002719",
"0503002719",
"0557955615",
"0054162088",
"0053587587",
"0554446942",
"0502987041",
"0554446942",
"0556975077",
"0558905624",
"0570101299",
"0550605635",
"0509560097",
"0055521514",
"0538634648",
"0509668362",
"0599053036",
"0590322952",
"0501134594",
"0053734040",
"0567966584",
"0507693999",
"0597888801",
"0565600666",
"0557757892",
"0505441005",
"0583644143",
"0566497370",
"0542484145",
"0560388612",
"0555867667",
"0551259122",
"0505304649",
"0555343218",
"0530333751",
"0508805122",
"0557488887",
"0541034506",
"0549032345",
"0504824511",
"0509942004",
"0509942004",
"0503574895",
"0504408166",
"0504913957",
"0530277340",
"0533403344",
"0554454231",
"0570694394",
"0555147666",
"0501305057",
"0556998021",
"0505860125",
"0534690616",
"0711753772",
"0502619223",
"0598600705",
"0501877567",
"0598482615",
"0508277489",
"0555582286",
"0530026777",
"0546451999",
"0546451999",
"0555677264",
"0547874858",
"0530012007",
"0538688146",
"0556223834",
"0557947083",
"0557947083",
"0557557517",
"0050743364",
"0546537772",
"0547744460",
"0543864804",
"0501275217",
"0535018000",
"0504288565",
"0533558448",
"0533558448",
"0546848205",
"0555803683",
"0504475367",
"0551301363",
"0551301363",
"0532902605",
"0509838104",
"0546848205",
"0546848205",
"0568095980",
"0567926368",
"0583644143",
"0548661196",
"0555609203",
"0551237911",
"0545228054",
"0558270780",
"0555777607",
"0598840943",
"0510574828",
"0555867090",
"0537904036",
"0552956621",
"0503131939",
"0503131939",
"0545322743",
"0568199255",
"0501215217",
"0597172953",
"0556126831",
"0505964589",
"0504518619",
"0544314340",
"0544314340",
"0595008489",
"0554410172",
"0597766399",
"0547129615",
"0505660306",
"0509149944",
"0553737496",
"0531114737",
"0531114737",
"0502210513",
"0055279920",
"0564986207",
"0564986207",
"0504451390",
"0555115032",
"0547451557",
"0500119298",
"0555803335",
"0544469700",
"0552328192",
"0556445256",
"0056574596",
"0505100237",
"0541206950",
"0563077606",
"0503922363",
"0500656062",
"0500656062",
"0534454407",
"0562705897",
"0568457716",
"0505318040",
"0509362518",
"0553190765",
"0055759855",
"0500200887",
"0543244511",
"0566949691",
"0555803335",
"0531501559",
"0533515534",
"0556677465",
"0538002408",
"0558336741",
"0555358184",
"0501913086",
"0594919510",
"0501942335",
"0554245526",
"0509711083",
"0530378874",
"0500729123",
"0544335558",
"0505861881",
"0500424544",
"0555727597",
"0531041218",
"0530360203",
"0530296666",
"0569093123",
"0535311665",
"0504824511",
"0506040659",
"0532693617",
"0553203622",
"0508773735",
"0504550803",
"0539150528",
"0503046433",
"0540982848",
"0553484420",
"0566999831",
"0544360120",
"0557788875",
"0507429823",
"0566437909",
"0538831191",
"0534078030",
"0534078030",
"0534317133",
"0531030306",
"0530024301",
"0538123777",
"0535111270",
"0534717865",
"0547977113",
"0503387758",
"0569990282",
"0501465766",
"0598040509",
"0596883333",
"0550509469",
"0552333331",
"0503864054",
"0534192962",
"0558432290",
"0501603470",
"0597594949",
"0553371891",
"0505154507",
"0507610882",
"0557586964",
"0050530237",
"0050530237",
"0552215114",
"0550975559",
"0550669192",
"0504309123",
"0533521333",
"0511301930",
"0559652009",
"0568522466",
"0564248279",
"0557080339",
"0502256293",
"0505116579",
"0532973323",
"0532973323",
"0532973323",
"0583633333",
"0540800030",
"0531368285",
"0555050530",
"0507513382",
"0551323276",
"0536930127",
"0556396209",
"0550971669",
"0566599880",
"0551777878",
"0570786866",
"0581322080",
"0542715135",
"0504346800",
"0565665559",
"0554723285",
"0504855691",
"0552562163",
"0530468476",
"0556643326",
"0053951665",
"0554549489",
"0554549489",
"0554549489",
"0564545840",
"0599804049",
"0599804049",
"0531627810",
"0591043334",
"0561606254",
"0556778511",
"0532322073",
"0553051070",
"0553763733",
"0538352000",
"0564545840",
"0530310301",
"0565020518",
"0578786870",
"0532311331",
"0505468018",
"0555399552",
"0569071799",
"0567419119",
"0591244475",
"0564248279",
"0509378638",
"0594413220",
"0503622216",
"0559884421",
"0543094879",
"0558014550",
"0540225374",
"0501893106",
"0561028982",
"0545337272",
"0559897869",
"0559897869",
"0558902001",
"0055529359",
"0533369046",
"0540854040",
"0582915236",
"0561999625",
"0505154588",
"0505154588",
"0594990532",
"0583291795",
"0555419328",
"0597885212",
"0558075206",
"0599542739",
"0503365270",
"0565674721",
"0559634105",
"0509084635",
"0560625296",
"0562969233",
"0510708364",
"0534786385",
"0509420216",
"0551459150",
"0559471945",
"0559471945",
"0555451857",
"0580038796",
"0534091248",
"0548230511",
"0503069157",
"0539062492",
"0599542739",
"0541199782",
"0543585899",
"0544747953",
"0507261493",
"0562576126",
"0545055087",
"0532874341",
"0581503747",
"0581503747",
"0532252847",
"0566451382",
"0576582520",
"0545327215",
"0556675223",
"0598822619",
"0564219559",
"0549251258",
"0549251258",
"0545101072",
"0540204694",
"0591122777",
"0561261609",
"0536021832",
"0560500684",
"0546296921",
"0503655557",
"0537171877",
"0510190177",
"0502583276",
"0557245240",
"0507497116",
"0564133481",
"0564133481",
"0598182181",
"0597235959",
"0506394883",
"0532798415",
"0566117601",
"0547279833",
"0533736404",
"0592581372",
"0596070462",
"0535045815",
"0569809845",
"0538097662",
"0538097662",
"0536906527",
"0507422330",
"0550598633",
"0951006171",
"0951006171",
"0564629334",
"0507738771",
"0536174765",
"0509219406",
"0508987264",
"0557093351",
"0557093351",
"0555277157",
"0570690506",
"0505531326",
"0542288837",
"0570191097",
"0570191097",
"0570191097",
"0561539032",
"0507221481",
"0582108060",
"0531686169",
"0531025917",
"0504877790",
"0567560004",
"0590483564",
"0552324651",
"0540770675",
"0507759946",
"0568531734",
"0563458534",
"0572082309",
"0556959513",
"0550889133",
"0508212063",
"0549809000",
"0537530124",
"0549647960",
"0551447662",
"0507951935",
"0507951935",
"0530758341",
"0550005570",
"0543080413",
"0555521042",
"0541212625",
"0504877790",
"0565955115",
"0553557199",
"0538739266",
"0510213313",
"0533138811",
"0566886919",
"0532519265",
"0566395045",
"0530394591",
"0509148516",
"0506890125",
"0551472428",
"0535133474",
"0553190041",
"0533386400",
"0543566644",
"0501894287",
"0501894287",
"0505552430",
"0595539932",
"0504236804",
"0544152210",
"0541199782",
"0599580399",
"0547366428",
"0501602141",
"0505885052",
"0199059790",
"0569647015",
"0541614737",
"0551198887",
"0501454582",
"0507601958",
"0500018507",
"0505205859",
"0594768217",
"0557214020",
"0504902010",
"0500595555",
"0501755566",
"0545065584",
"0580051118",
"0506740268",
"0503572249",
"0503572249",
"0597901990",
"0553818151",
"0540998285",
"0548987087",
"0531179666",
"0531179666",
"0554787481",
"0598927821",
"0555007742",
"0555007742",
"0533094102",
"0534358228",
"0546945566",
"0507160455",
"0530922622",
"0570050465",
"0505422369",
"0556814736",
"0544378108",
"0050016794",
"0567499123",
"0533308588",
"0557174378",
"0564422215",
"0565853403",
"0556055264",
"0593062614",
"0541633010",
"0507709451",
"0509574193",
"0566521053",
"0555525742",
"0054903234",
"0562433104",
"0543512512",
"0538507879",
"0506697067",
"0503471093",
"0507576863",
"0534318675",
"0554838296",
"0559946543",
"0547750041",
"0131231231",
"0553331752",
"0598840943",
"0549570810",
"0506635442",
"0535094197",
"0504844379",
"0509086380",
"0509086380",
"0546856102",
"0502210513",
"0596583880",
"0556756336",
"0556756336",
"0576424228",
"0555542543",
"0556566271",
"0568802011",
"0548153462",
"0548153462",
"0548153462",
"0548153462",
"0505878371",
"0548853278",
"0500053973",
"0536356346",
"0538854522",
"0504687987",
"0549494344",
"0540776532",
"0561934145",
"0594847896",
"0566851987",
"0558553502",
"0500090445",
"0548903923",
"0502391654",
"0502391654",
"0500303396",
"0552683647",
"0594847896",
"0580075720",
"0542900743",
"0559794647",
"0563452934",
"0509529478",
"0551447662",
"0502876249",
"0598322155",
"0556964890",
"0563004196",
"0504107475",
"0565640974",
"0535924489",
"0568386329",
"0506865875",
"0550478070",
"0545221171",
"0553689923",
"0546274464",
"0552560329",
"0542620945",
"0501546077",
]

In [77]:
cursor.execute(f"""
    SELECT 
        *
    FROM MACDB.dbo.v_Invoice a
    INNER JOIN MACDB.dbo.v_Customer b
    ON a.CUSTOMERID = b.CUSTOMERID
    WHERE 
        b.MOBILE IN ({",".join(mobile_list)})
        AND a.InvoiceDate > '2025-05-14'
""")
rows = cursor.fetchall()

df = pd.DataFrame.from_records(rows, columns=[col[0] for col in cursor.description])

In [78]:
df.to_excel("result_consulting.xlsx", engine="openpyxl", index=False)

In [79]:
def get_all_data_from_table(cursor, tablename):

    cursor.execute(f"""
    SELECT 
    TOP 1 *
    FROM MACDB.dbo.{tablename}
    """)
    rows = cursor.fetchall()
    cols = [col[0] for col in cursor.description]
    if "ModifiedOn" in cols:
        cursor.execute(f"""
            SELECT 
                MIN(ModifiedOn)
            FROM MACDB.dbo.{tablename}
        """)
        rows = cursor.fetchall()

        min_date = rows[0][0]
        max_date = "2025-08-01" # datetime.date.today()

        dates_list = pd.date_range(min_date, max_date, freq='1ME')

        tables_result_list = []
        for date in tqdm.tqdm(dates_list):
            cursor.execute(f"""
                SELECT 
                    *
                FROM MACDB.dbo.{tablename}
                WHERE YEAR(ModifiedOn) = {date.year} and Month(ModifiedOn) = {date.month}
            """)
            rows = cursor.fetchall()

            df = pd.DataFrame.from_records(rows, columns=[col[0] for col in cursor.description])
            if df.shape[0] > 0:
                tables_result_list.append(df)

            result_df = pd.concat(tables_result_list).reset_index(drop=True)
    else:
        cursor.execute(f"""
            SELECT 
                *
            FROM MACDB.dbo.{tablename}
        """)
        rows = cursor.fetchall()

        df = pd.DataFrame.from_records(rows, columns=[col[0] for col in cursor.description])

        result_df = df

    return result_df

In [80]:
tablename_dict = {
    "branch_PE": "v_Branch",
    "customer_PE": "v_Customer",
    "vehicle_PE": "v_Vehicle",
    "branch_PAC": "v_PAC_Branch",
    "customer_PAC": "v_PAC_Customer",
    "vehicle_PAC": "v_PAC_Vehicle",
}

In [81]:
for key, value in tablename_dict.items():
    print(key, value)
    try:
        df = get_all_data_from_table(cursor, value)
        df.to_parquet(f"{key}.parquet")
        print(df.shape)
    except pyodbc.ProgrammingError as e:
        print(e)
        continue

branch_PE v_Branch
(1017, 13)
customer_PE v_Customer

 14%|█▍        | 9/65 [01:34<08:08,  8.73s/it]/tmp/ipykernel_1210096/567863462.py:37: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  result_df = pd.concat(tables_result_list).reset_index(drop=True)
 15%|█▌        | 10/65 [01:42<07:54,  8.63s/it]/tmp/ipykernel_1210096/567863462.py:37: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  result_df = pd.concat(tables_result_list).reset_index(drop=True)
 17%|█▋        | 11/65 [01:49<07:06,  7.90s/it]/tmp/ipykernel_1210096/567863462.py:37: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  result_df = pd.concat(tables_result_list).reset_index(drop=True)
 18%|█▊        | 12/65 [01:55<06:32,  7.41s/it]/tmp/ipykernel_1210096/567863462.py:37: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  result_df = pd.concat(tables_result_list).reset_index(drop=True)
 20%|██        | 13/65 [02:02<06:20,  7.32s/it]/tmp/ipykernel_1210096/567863462.py:37: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  result_df = pd.concat(tables_result_list).reset_index(drop=True)
 22%|██▏       | 14/65 [02:09<06:11,  7.28s/it]/tmp/ipykernel_1210096/567863462.py:37: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  result_df = pd.concat(tables_result_list).reset_index(drop=True)
 23%|██▎       | 15/65 [02:17<06:03,  7.27s/it]/tmp/ipykernel_1210096/567863462.py:37: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  result_df = pd.concat(tables_result_list).reset_index(drop=True)
 25%|██▍       | 16/65 [02:26<06:28,  7.93s/it]/tmp/ipykernel_1210096/567863462.py:37: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  result_df = pd.concat(tables_result_list).reset_index(drop=True)
 26%|██▌       | 17/65 [02:33<06:05,  7.61s/it]/tmp/ipykernel_1210096/567863462.py:37: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  result_df = pd.concat(tables_result_list).reset_index(drop=True)
 28%|██▊       | 18/65 [02:40<05:47,  7.39s/it]/tmp/ipykernel_1210096/567863462.py:37: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  result_df = pd.concat(tables_result_list).reset_index(drop=True)
 29%|██▉       | 19/65 [02:47<05:37,  7.33s/it]/tmp/ipykernel_1210096/567863462.py:37: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  result_df = pd.concat(tables_result_list).reset_index(drop=True)
 31%|███       | 20/65 [02:53<05:19,  7.10s/it]/tmp/ipykernel_1210096/567863462.py:37: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  result_df = pd.concat(tables_result_list).reset_index(drop=True)
 32%|███▏      | 21/65 [03:01<05:20,  7.28s/it]/tmp/ipykernel_1210096/567863462.py:37: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  result_df = pd.concat(tables_result_list).reset_index(drop=True)
 34%|███▍      | 22/65 [03:08<05:10,  7.23s/it]/tmp/ipykernel_1210096/567863462.py:37: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  result_df = pd.concat(tables_result_list).reset_index(drop=True)
 35%|███▌      | 23/65 [03:15<05:02,  7.19s/it]/tmp/ipykernel_1210096/567863462.py:37: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  result_df = pd.concat(tables_result_list).reset_index(drop=True)
 37%|███▋      | 24/65 [03:23<04:59,  7.31s/it]/tmp/ipykernel_1210096/567863462.py:37: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  result_df = pd.concat(tables_result_list).reset_index(drop=True)
 38%|███▊      | 25/65 [03:30<04:50,  7.26s/it]/tmp/ipykernel_1210096/567863462.py:37: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  result_df = pd.concat(tables_result_list).reset_index(drop=True)
 40%|████      | 26/65 [03:37<04:41,  7.21s/it]/tmp/ipykernel_1210096/567863462.py:37: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  result_df = pd.concat(tables_result_list).reset_index(drop=True)
 42%|████▏     | 27/65 [03:44<04:32,  7.18s/it]/tmp/ipykernel_1210096/567863462.py:37: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  result_df = pd.concat(tables_result_list).reset_index(drop=True)
 43%|████▎     | 28/65 [03:52<04:26,  7.21s/it]/tmp/ipykernel_1210096/567863462.py:37: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  result_df = pd.concat(tables_result_list).reset_index(drop=True)
 45%|████▍     | 29/65 [03:59<04:21,  7.26s/it]/tmp/ipykernel_1210096/567863462.py:37: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  result_df = pd.concat(tables_result_list).reset_index(drop=True)
 46%|████▌     | 30/65 [04:06<04:14,  7.26s/it]/tmp/ipykernel_1210096/567863462.py:37: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  result_df = pd.concat(tables_result_list).reset_index(drop=True)
 48%|████▊     | 31/65 [04:14<04:09,  7.33s/it]/tmp/ipykernel_1210096/567863462.py:37: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  result_df = pd.concat(tables_result_list).reset_index(drop=True)
 49%|████▉     | 32/65 [04:21<04:02,  7.35s/it]/tmp/ipykernel_1210096/567863462.py:37: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  result_df = pd.concat(tables_result_list).reset_index(drop=True)
 51%|█████     | 33/65 [04:29<03:56,  7.39s/it]/tmp/ipykernel_1210096/567863462.py:37: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  result_df = pd.concat(tables_result_list).reset_index(drop=True)
 52%|█████▏    | 34/65 [04:36<03:49,  7.42s/it]/tmp/ipykernel_1210096/567863462.py:37: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  result_df = pd.concat(tables_result_list).reset_index(drop=True)
 54%|█████▍    | 35/65 [04:44<03:43,  7.46s/it]/tmp/ipykernel_1210096/567863462.py:37: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  result_df = pd.concat(tables_result_list).reset_index(drop=True)
 55%|█████▌    | 36/65 [04:51<03:36,  7.48s/it]/tmp/ipykernel_1210096/567863462.py:37: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  result_df = pd.concat(tables_result_list).reset_index(drop=True)
 57%|█████▋    | 37/65 [04:59<03:30,  7.51s/it]/tmp/ipykernel_1210096/567863462.py:37: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  result_df = pd.concat(tables_result_list).reset_index(drop=True)
 58%|█████▊    | 38/65 [05:06<03:24,  7.56s/it]/tmp/ipykernel_1210096/567863462.py:37: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  result_df = pd.concat(tables_result_list).reset_index(drop=True)
 60%|██████    | 39/65 [05:14<03:18,  7.63s/it]/tmp/ipykernel_1210096/567863462.py:37: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  result_df = pd.concat(tables_result_list).reset_index(drop=True)
 62%|██████▏   | 40/65 [05:22<03:13,  7.73s/it]/tmp/ipykernel_1210096/567863462.py:37: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  result_df = pd.concat(tables_result_list).reset_index(drop=True)
 63%|██████▎   | 41/65 [05:30<03:06,  7.79s/it]/tmp/ipykernel_1210096/567863462.py:37: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  result_df = pd.concat(tables_result_list).reset_index(drop=True)
 65%|██████▍   | 42/65 [05:38<03:00,  7.83s/it]/tmp/ipykernel_1210096/567863462.py:37: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  result_df = pd.concat(tables_result_list).reset_index(drop=True)
 66%|██████▌   | 43/65 [05:46<02:52,  7.83s/it]/tmp/ipykernel_1210096/567863462.py:37: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  result_df = pd.concat(tables_result_list).reset_index(drop=True)
 68%|██████▊   | 44/65 [05:54<02:45,  7.90s/it]/tmp/ipykernel_1210096/567863462.py:37: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  result_df = pd.concat(tables_result_list).reset_index(drop=True)
 69%|██████▉   | 45/65 [06:02<02:38,  7.93s/it]/tmp/ipykernel_1210096/567863462.py:37: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  result_df = pd.concat(tables_result_list).reset_index(drop=True)
 71%|███████   | 46/65 [06:10<02:31,  7.96s/it]/tmp/ipykernel_1210096/567863462.py:37: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  result_df = pd.concat(tables_result_list).reset_index(drop=True)
 72%|███████▏  | 47/65 [06:18<02:23,  8.00s/it]/tmp/ipykernel_1210096/567863462.py:37: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  result_df = pd.concat(tables_result_list).reset_index(drop=True)
 74%|███████▍  | 48/65 [06:26<02:15,  8.00s/it]/tmp/ipykernel_1210096/567863462.py:37: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  result_df = pd.concat(tables_result_list).reset_index(drop=True)
 75%|███████▌  | 49/65 [06:34<02:10,  8.13s/it]/tmp/ipykernel_1210096/567863462.py:37: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  result_df = pd.concat(tables_result_list).reset_index(drop=True)
 77%|███████▋  | 50/65 [06:43<02:03,  8.20s/it]/tmp/ipykernel_1210096/567863462.py:37: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  result_df = pd.concat(tables_result_list).reset_index(drop=True)
 78%|███████▊  | 51/65 [06:51<01:56,  8.33s/it]/tmp/ipykernel_1210096/567863462.py:37: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  result_df = pd.concat(tables_result_list).reset_index(drop=True)
 80%|████████  | 52/65 [07:00<01:49,  8.39s/it]/tmp/ipykernel_1210096/567863462.py:37: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  result_df = pd.concat(tables_result_list).reset_index(drop=True)

(6927164, 19)
vehicle_PE v_Vehicle

100%|██████████| 65/65 [05:48<00:00,  5.37s/it]

(7187403, 12)
branch_PAC v_PAC_Branch
(23, 13)
customer_PAC v_PAC_Customer

 14%|█▍        | 9/65 [00:12<01:04,  1.15s/it]/tmp/ipykernel_1210096/567863462.py:37: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  result_df = pd.concat(tables_result_list).reset_index(drop=True)
100%|██████████| 65/65 [01:07<00:00,  1.03s/it]

(26194, 17)
vehicle_PAC v_PAC_Vehicle

100%|██████████| 65/65 [01:07<00:00,  1.04s/it]

(29550, 12)

In [82]:
import pyodbc
from pathlib import Path

BASE_OUT = Path.cwd()

def get_all_data_from_invoice_table(cursor, tablename, table_items_name):
    out_inv_dir   = BASE_OUT / tablename
    out_items_dir = BASE_OUT / f"{tablename}Items"
    out_inv_dir.mkdir(parents=True, exist_ok=True)
    out_items_dir.mkdir(parents=True, exist_ok=True)
    print(f"[init] Saving invoice parquet to: {out_inv_dir}")
    print(f"[init] Saving items  parquet to: {out_items_dir}")

    cursor.execute(f"""
        SELECT MIN(ModifiedOn) FROM MACDB.dbo.{tablename}
    """)
    _rows = cursor.fetchall()

    min_date = "2025-08-01"
    max_date = "2025-10-01"

    dates_list = pd.date_range(min_date, max_date, freq='1ME')
    print("Processing dates:", dates_list)

    for date in tqdm.tqdm(dates_list):
        cursor.execute(f"""
            SELECT *
            FROM MACDB.dbo.{tablename}
            WHERE YEAR(ModifiedOn) = {date.year}
              AND MONTH(ModifiedOn) = {date.month}
        """)
        rows = cursor.fetchall()
        invoice_df = pd.DataFrame.from_records(rows, columns=[col[0] for col in cursor.description])

        if not invoice_df.empty:
            inv_path = out_inv_dir / f"{date.year}{date.month:02}.parquet"
            print(f"Saving invoice data → {inv_path} ({invoice_df.shape[0]} rows)")
            invoice_df.to_parquet(inv_path)
        else:
            print(f"No invoice rows for {date.year}-{date.month:02}")

        cursor.execute(f"""
            SELECT a.*
            FROM MACDB.dbo.{table_items_name} a
            INNER JOIN (
                SELECT InvoiceID, ModifiedOn
                FROM MACDB.dbo.{tablename}
            ) b ON a.InvoiceID = b.InvoiceID
            WHERE YEAR(b.ModifiedOn) = {date.year}
              AND MONTH(b.ModifiedOn) = {date.month}
        """)
        rows = cursor.fetchall()
        items_df = pd.DataFrame.from_records(rows, columns=[col[0] for col in cursor.description])

        if not items_df.empty:
            items_path = out_items_dir / f"{date.year}{date.month:02}.parquet"
            print(f"Saving items  data → {items_path} ({items_df.shape[0]} rows)")
            items_df.to_parquet(items_path)
        else:
            print(f"No items rows for {date.year}-{date.month:02}")

    return True

In [83]:
tablename_dict = {
    "invoice_PAC": ("v_PAC_Invoice", "v_PAC_InvoiceItems"),
    "invoice_PE": ("v_Invoice", "v_InvoiceItems"),
}

In [84]:
for key, value in tablename_dict.items():
    print(key, value[0], value[1])

invoice_PAC v_PAC_Invoice v_PAC_InvoiceItems
invoice_PE v_Invoice v_InvoiceItems

In [85]:
for key, value in tablename_dict.items():
    print(key, value)
    try:
        get_all_data_from_invoice_table(cursor, value[0], value[1])
    except pyodbc.ProgrammingError as e:
        print(e)
        continue

invoice_PAC ('v_PAC_Invoice', 'v_PAC_InvoiceItems')
[init] Saving invoice parquet to: /home/ammar/petromin/notebooks/v_PAC_Invoice
[init] Saving items  parquet to: /home/ammar/petromin/notebooks/v_PAC_InvoiceItems
Processing dates: DatetimeIndex(['2025-08-31', '2025-09-30'], dtype='datetime64[ns]', freq='ME')

  0%|          | 0/2 [00:00<?, ?it/s]

Saving invoice data → /home/ammar/petromin/notebooks/v_PAC_Invoice/202508.parquet (629 rows)

 50%|█████     | 1/2 [00:06<00:06,  6.37s/it]

Saving items  data → /home/ammar/petromin/notebooks/v_PAC_InvoiceItems/202508.parquet (1997 rows)
Saving invoice data → /home/ammar/petromin/notebooks/v_PAC_Invoice/202509.parquet (186 rows)

100%|██████████| 2/2 [00:12<00:00,  6.11s/it]

Saving items  data → /home/ammar/petromin/notebooks/v_PAC_InvoiceItems/202509.parquet (559 rows)
invoice_PE ('v_Invoice', 'v_InvoiceItems')
[init] Saving invoice parquet to: /home/ammar/petromin/notebooks/v_Invoice
[init] Saving items  parquet to: /home/ammar/petromin/notebooks/v_InvoiceItems

Processing dates: DatetimeIndex(['2025-08-31', '2025-09-30'], dtype='datetime64[ns]', freq='ME')

  0%|          | 0/2 [00:00<?, ?it/s]

Saving invoice data → /home/ammar/petromin/notebooks/v_Invoice/202508.parquet (292105 rows)
Saving items  data → /home/ammar/petromin/notebooks/v_InvoiceItems/202508.parquet (961823 rows)

 50%|█████     | 1/2 [02:15<02:15, 135.04s/it]

Saving invoice data → /home/ammar/petromin/notebooks/v_Invoice/202509.parquet (89673 rows)
Saving items  data → /home/ammar/petromin/notebooks/v_InvoiceItems/202509.parquet (298606 rows)

100%|██████████| 2/2 [02:56<00:00, 88.14s/it]

# Promo

In [93]:
cursor.execute(f"""
    SELECT 
        *
    FROM MACDB.dbo.TMP_PROMOS a
""")
rows = cursor.fetchall()

df = pd.DataFrame.from_records(rows, columns=[col[0] for col in cursor.description])

In [94]:
df

                                         Promo
0                     1 Ltr Synthetic Oil Free
1                  169 SAR Synthetic Oil Promo
2                      180 Synthetic Oil Promo
3                            195 Synthetic Oil
4              20W50 Offer (2013 Models) 3 Let
..                                         ...
170                      Ramadan Mineral Promo
171                    Ramadan Synthetic Promo
172                  SAR 170 Package Synthetic
173  Saudi Foundation Day 2025 Mineral Bottle
174  Saudi Foundation Day 2025 Mineral Bottle

[175 rows x 1 columns]

In [95]:
df.to_parquet(f"tmp_promos.parquet")
df.to_parquet(f"../data/01_raw/raw_promos.parquet")

In [96]:
raw_transactions = pd.read_parquet("../data/01_raw/transactions_origin.parquet", engine="fastparquet")

In [97]:
raw_transactions.head().T

,0,1,2,3,4
InvoiceID,0000054F-98E7-4A1B-85E7-FF505021DB02,0000058D-4FEF-42C4-BF36-9FF2744953D0,0000088D-5070-4C46-AC94-3B619CA713C2,00000A9B-7810-4F8A-93B3-0534EA3C3D8A,00000B21-F29D-4A25-B205-7D1593882D9E
CustomerID,51392616-9B76-4435-8C0E-43C0139BCA1F,AF8F3733-EE8E-493C-AD23-2F15BF80CF16,0A4575B2-347C-490D-ABA2-C220BBA9D600,6B1317C1-CA7B-444E-B58B-958CA5D7C9CA,B7A259AC-0900-4E69-A2EF-78ADC38588BB
CustomerVehicleID,7272896E-F429-47A5-88F8-1195CE25FB9D,151779EE-F4CE-4F5B-9430-393D04006AAE,99A94E11-0B9E-4911-B9EF-6457667AE93F,55587606-5343-492C-B0E0-65BB19D14AF6,77AAD08D-C090-49C5-A7ED-1C41FA5F65DB
BranchID,BBD69E26-7BE0-41D0-BC40-D395C7D1DEDF,6A0C15EA-2F3C-4F05-99AE-8481109A13A1,AC98BF1B-85AD-4745-A759-E7D7652CA5EF,DD10E96C-2886-456A-8B29-45BD94A46281,55D433BA-7267-4E6E-9D9E-2FDDC8DFD143
InvoiceDate,2023-01-28 22:36:40,2021-03-25 14:02:18,2025-04-11 17:20:50,2025-07-27 20:30:48,2024-12-10 18:41:12
ServiceName,Engine Oil change,Engine Oil change,Engine Oil change,Engine Oil change,Engine Oil change
ServiceItemGroupDefaultName,Oil Synthetic,Oil Synthetic,Oil Synthetic,Oil Synthetic,Oil
ServiceItemDefaultName,Petromin Super Synthetic 5w30 - 1L,Petromin Super Synthetic 5w30 - 1L,Petromin A-1 Super Synthetic 5W-30 (6x4 Ltr),Petromin Super Synthetic 5w30 - 1L,Petromin Super 10W30 Engine Oil
ServiceItemCode,PET A-1 SYN,PET A-1 SYN,PET A-1 SYN 5W30 - 6X4,PET A-1 SYN 5W30 1L,BULK10W30
ServicePackageName,PE SAR 180 Synthetic Oil Package,Gold Synthetic Service,199 Synthetic Oil,Panda Synthetic Offer,"Hyundai ELANTRA 1.6L 5k,15k,25k,35k,45k,55k,65..."
sku,Engine Oil change | Oil Synthetic | Petromin S...,Engine Oil change | Oil Synthetic | Petromin S...,Engine Oil change | Oil Synthetic | Petromin A...,Engine Oil change | Oil Synthetic | Petromin S...,Engine Oil change | Oil | Petromin Super 10W30...
IsFleet,0,1,0,0,0
IsPMS,0,0,0,0,1
WorkOrderMileage,87862,152283,156222,39344,355309
PreviousMileage,79919,140643,146566,28182,350226
NewCustomer,0,0,0,0,0
NewVehicle,0,0,0,0,0
Warranty,1,0,0,1,0
ItemBaseQuantity,6.0,4.0,4.0,4.0,4.0
ServiceItemCostAmount,49.3032,18.6668,31.5268,32.0948,27.28
InvoiceTotalDiscountAmount,0.0,0.0,0.0,117.92,0.0
InvoiceBeforeTaxAmount,269.5652,120.0,173.05,150.78,117.39
InvoiceBeforeDiscountAmount,269.5652,120.0,173.05,268.7,117.39
InvoiceTotalAmount,310.0,138.0,199.01,173.4,135.0
InvoiceGrossMargin,220.262,101.3332,141.5232,118.6852,90.11
InvoiceGrossMargin_perc,0.710523,0.734299,0.711136,0.684459,0.667481
hasDiscount,0,0,0,1,0
MileageBetweenVisits,7943,11640,9656,11162,5083
MileageBetweenVisits_perc,0.099388,0.082763,0.065882,0.396068,0.014513