In [1]:
import numpy as np
import pandas as pd

In [ ]:
# for filename in ["raw_customers"]:
#     df = pd.read_parquet(f"../data/01_raw/{filename}.parquet", engine="fastparquet")
#     # df.to_parquet(f"../data/01_raw/{filename}.parquet", engine="fastparquet", index=False)

In [ ]:
# df["Mobile"] = df["Mobile"].str.replace("^966", "0", regex=True)

In [ ]:
# df.to_parquet(f"../data/01_raw/{filename}.parquet", engine="fastparquet", index=False)

:

In [2]:
pd.set_option('display.max_columns', 500)

In [3]:
invoice_df = pd.read_parquet("invoice.parquet", engine="fastparquet")

In [4]:
invoice_df.groupby([invoice_df["InvoiceDate"].dt.year, invoice_df["InvoiceDate"].dt.month],).agg({"InvoiceID": "nunique"})

                         InvoiceID
InvoiceDate InvoiceDate
2020        7                 3640
            8                22152
            9               154621
            10              253775
            11              248996
...                            ...
2025        4               269472
            5               310184
            6               263818
            7               168338
            12                   1

[62 rows x 1 columns]

In [5]:
# TODO: delimit target area, drop fleets? drop new clients?
# TODO: feature - time since first visit
# TODO: feature - time since last visit
# TODO: feature - normalize to see average visit
# TODO: feature - time since last visit
# TODO: feature - Avg amount
# TODO: feature - Avg amount normalized
# TODO: compare mileages, average amount per mileage level, time between level per car

In [6]:
invoice_df.head()

,InvoiceID,InvoiceNumber,ModifiedOn,BranchID,TransCustomerID,CustomerID,CustomerVehicleID,SystemUserID,InvoiceDate,InvoiceDueDate,InvoiceBeforeDiscountAmount,InvoiceDiscountAmount,InvoiceBeforeTaxAmount,InvoiceTaxAmount,InvoiceTotalAmount,InvoiceItemCost,IsFleet,IsPMS,CustomerContractID,CustomerContractType,WorkOrderNumber,WorkOrderStartDate,WorkOrderEndDate,WorkOrderMileage,PreviousMileage,PreviousVisitDate,NewOrExistingCustomer,NewCustomer,NewVehicle,Warranty,PMSID,PMSName,InvoiceType,ServiceType,StationBrand
0,1BBBB3CC-10BF-4739-8296-01185CDE6BD0,M-1333-11169,2023-11-09 16:57:17,A6688563-50F5-4EFB-9BED-DB1661A357A3,9AA9A703-A012-4719-AC81-597B0E0269D8,9AA9A703-A012-4719-AC81-597B0E0269D8,554784BC-8250-414A-8825-579A9868EF22,07A0CD63-5129-4EEF-B8C3-EC7834E268CF,2023-11-09 14:44:12,2023-11-09 14:44:12,170.4348,35.6522,134.7826,20.2174,155.0000,44.8114,0,0,None,None,1333-11360,2023-11-09 14:29:48,2023-11-09 14:44:12,599508,0,1970-01-01 00:00:00,New Customer,1,1,0,None,None,Cash,PE Service,PE
1,85ABD31C-8030-41F1-99B2-01187C718D90,M-1641-12584,2023-11-06 16:41:29,A230DC73-5ECC-46D2-B76C-72F451C46F01,C0091150-3952-4A10-A7C2-9C9BBEB243AA,C0091150-3952-4A10-A7C2-9C9BBEB243AA,22C11DBB-FDE1-4F28-A118-AFA2A9D4CEDD,C5CED42F-77B2-4D21-BFF4-2BB850E1EC5C,2023-11-06 12:33:58,2023-11-06 12:33:58,289.5652,72.5217,217.0435,32.5565,249.6000,49.8784,1,0,52E10671-D0B3-4212-9BC1-526071F2950D,PF,1641-12659,2023-11-06 12:14:41,2023-11-06 12:33:58,266500,256252,2023-09-16 09:49:18,Existing Customer,0,0,0,None,None,Cash,Fleet,PE
2,A5BC2209-2E9D-4C6C-86BB-0118818A18FF,M-1956-32727,2023-11-12 17:01:16,81169A2D-5E1E-48E4-890D-889B41030E6B,63B7F338-AB26-4F47-82D1-930EEA034420,63B7F338-AB26-4F47-82D1-930EEA034420,309AD964-D576-4703-AB4F-1396CC2DB26D,0715F32A-49FB-437A-9B35-600E4E928713,2023-11-12 16:26:13,2023-11-12 16:26:13,459.1304,45.9130,413.2174,61.9826,475.2000,96.5827,0,0,None,None,1956-33188,2023-11-12 16:06:19,2023-11-12 16:26:13,472222,468909,2023-09-28 17:23:37,Existing Customer,0,0,0,None,None,Cash,PE Service,PE
3,6964608E-DEFA-4985-BE79-01188411109C,M-1441-23804,2023-11-29 19:04:32,47C320DF-2254-4202-B50B-2CE6D4867695,78BEA012-73CF-4C0F-9F3A-0D0D173E3E17,78BEA012-73CF-4C0F-9F3A-0D0D173E3E17,058B14B9-9CB4-48A0-AAC1-C3F39C310FB1,1AC4E589-D899-41CA-892F-03A3356EE6D5,2023-11-29 18:57:39,2023-11-29 18:57:39,228.6957,0.0000,228.6957,34.3043,263.0000,57.0536,0,0,None,None,1441-24011,2023-11-29 18:28:24,2023-11-29 18:57:39,19343,14431,2023-11-05 11:54:07,Existing Customer,0,0,1,None,None,Cash,PE Service,PE
4,0B93D792-3086-4F2F-8618-0118A0719885,M-1223-29574,2023-11-06 20:08:11,CB92B106-3C1A-4DE6-A228-92A6DCFE3DD9,098FEC27-3659-481E-8A0A-CA02162F7A18,098FEC27-3659-481E-8A0A-CA02162F7A18,D09A3CFF-E054-4900-8E04-AB39D38193CD,DBFB65C6-4B19-4BCA-994A-5D7C26C1C1A4,2023-11-06 19:57:57,2023-11-06 19:57:57,346.9565,26.0900,320.8665,48.1300,368.9965,75.0000,0,0,230E8C05-D4DD-4792-A203-D3477A0E2636,PE,1223-29993,2023-11-06 19:55:01,2023-11-06 19:57:57,302340,302340,2023-11-06 19:53:40,Existing Customer,0,0,0,None,None,Cash,Partner,PE

In [7]:
invoice_df.isna().mean()

InvoiceID                      0.000000
InvoiceNumber                  0.000000
ModifiedOn                     0.000000
BranchID                       0.000000
TransCustomerID                0.000000
CustomerID                     0.000000
CustomerVehicleID              0.000000
SystemUserID                   0.000000
InvoiceDate                    0.000000
InvoiceDueDate                 0.000281
InvoiceBeforeDiscountAmount    0.000000
InvoiceDiscountAmount          0.000000
InvoiceBeforeTaxAmount         0.000000
InvoiceTaxAmount               0.000000
InvoiceTotalAmount             0.000000
InvoiceItemCost                0.000000
IsFleet                        0.000000
IsPMS                          0.000000
CustomerContractID             0.821180
CustomerContractType           0.000000
WorkOrderNumber                0.000000
WorkOrderStartDate             0.000000
WorkOrderEndDate               0.000000
WorkOrderMileage               0.000000
PreviousMileage                0.000000
PreviousVisitDate              0.014363
NewOrExistingCustomer          0.000000
NewCustomer                    0.000000
NewVehicle                     0.000000
Warranty                       0.000000
PMSID                          0.926064
PMSName                        0.926064
InvoiceType                    0.000000
ServiceType                    0.000000
StationBrand                   0.000000
dtype: float64

In [8]:
(invoice_df["TransCustomerID"] == invoice_df["CustomerID"]).mean()

0.8462386286403842

In [9]:
# filter_owner = invoice_df["IsDriverOwner"] == True

In [10]:
customer_df = invoice_df.groupby("CustomerID").agg(
    n_branches=("BranchID", "nunique"),
    n_invoices=("InvoiceID", "nunique"),
    n_customers=("TransCustomerID", "nunique"),
    n_vehicles=("CustomerVehicleID", "nunique"),
)
customer_df.sort_values(["n_invoices", "n_branches"], ascending=False).head(20)

,n_branches,n_invoices,n_customers,n_vehicles
CustomerID,,,,
3EAFDAFB-6DB8-4839-A44A-5D51CC11D120,176,1510,1,1
DE973556-E0D5-4D5B-8FB9-2E7CAB629DC4,62,1154,1,1
CD945C73-9EB6-4C3F-84B8-6D4EA9599095,68,1098,1,1
AA004ADE-01EE-4C59-B621-002A84CB8C18,148,957,3,100
BFACF570-E061-460C-AFB0-46AB6FA34B7A,24,849,2,1
02EB408F-3036-4D05-BE3E-0026F4429DD5,130,826,4,73
0345D677-A514-4A8B-AF9E-E35666E53FD2,67,806,2,1
8220352B-EDBC-4F6E-9EFD-D5D1B596C9BD,14,793,1,1
4411C86D-0AB8-4792-919E-0017496EF0CB,160,754,3,82
B72F62AE-3B64-4151-A8EC-000BC090FE2E,173,730,3,55
B3859CA4-E4D4-4141-BB0D-7512B5F00F66,2,715,1,1
6AF7A226-79FF-4823-B42F-002237F037FA,145,671,4,52
01400971-99CA-4FEB-BE6C-6D3BFE730453,44,648,1,1
AD447057-CDE8-4D44-93EC-00096B0D44A7,117,632,3,41
68DD8879-16DB-4F04-AB38-9560D45C7D51,50,615,1,1
0F9048FD-62FB-45DC-BB04-5BA98F46FB88,170,603,1,1
78C142C0-92CD-4746-8EE9-53DBFC9C79C2,2,587,1,1
C868CBE1-01A6-40D5-8B69-000F6264957D,149,565,4,40
BCDB5335-8893-4400-85A1-9F32A0CEBDC1,161,548,1,1
E7B76ECA-309C-4868-8A27-9C5387F230D2,48,539,1,1

In [11]:
vehicle_df = invoice_df.groupby("CustomerVehicleID").agg(
    n_branches=("BranchID", "nunique"),
    n_invoices=("InvoiceID", "nunique"),
    n_transcustomers=("TransCustomerID", "nunique"),
    n_customers=("CustomerID", "nunique"),
)
vehicle_df.sort_values(["n_customers"], ascending=False).head(20)

,n_branches,n_invoices,n_transcustomers,n_customers
CustomerVehicleID,,,,
00000065-97BF-444A-9B3D-CBB2B09EA445,1,1,1,1
AA77685D-26FA-4F8C-8193-78226B81CA5F,9,29,2,1
AA77158D-38F3-49BE-9D19-291893983C4F,1,1,1,1
AA772EA9-022B-4A64-B7A7-68E76E497B36,1,1,1,1
AA772FDA-BE1D-4BE3-8887-3387C5205A9F,1,1,1,1
AA7730C8-2716-48DC-9E73-01AB59C4627D,1,1,1,1
AA773359-B306-4D07-B97C-4363B1285A53,3,3,1,1
AA77392A-BA4F-4E2E-B64C-9F645BA2ADF6,6,6,2,1
AA7740BC-8730-4741-9825-798414EA9557,2,3,1,1
AA7748BA-C3D0-4D4C-A6C8-1BEB6CFD09F0,1,1,1,1
AA774C88-7E5E-48EC-8E3F-93DF8AB09C7F,1,1,1,1
AA774EC1-496A-486E-BB27-048B91835FA0,1,1,1,1
AA775117-3613-4BA1-B839-79C84A4E4C0B,1,1,1,1
AA776B5C-9FE3-464A-B4AC-2D47771FD0A5,1,1,1,1
AA779B05-2DFC-4F01-A5A7-849E14236E80,6,6,1,1
AA7776FF-EFF3-41F3-88CC-AF7A17D676EB,1,4,1,1
AA7779A4-547B-4315-9359-EBC914B289B1,1,1,1,1
AA777B20-B56E-4B5D-979A-918A29674F3B,1,1,1,1
AA777F2A-B9DE-4E5D-B596-9B7012A5709F,2,10,1,1
AA77801A-A984-4A25-8810-B9DB9C203FD2,1,1,1,1

In [12]:
branch_df = invoice_df.groupby("BranchID").agg(
    n_invoices=("InvoiceID", "nunique"),
    n_customers=("CustomerID", "nunique"),
    total_revenue=("InvoiceTotalAmount", "sum")
)
branch_df.sort_values(["total_revenue"], ascending=False).head(20)

                                      n_invoices  n_customers  total_revenue
BranchID
5A4C7A0C-D8C1-491C-AAE3-91AAEF1F2F49       87033        38281   2.795824e+07
DFF57243-D6A3-415B-A8CE-C07431DA1C6B       66253        33574   2.634913e+07
EA56C2A0-D061-43DE-A550-546FF6F5436B       65421        35907   2.468718e+07
4771D0E0-6142-4F74-B93C-E5331AAA11A6       71247        27320   2.344474e+07
CE344F25-83A5-44D8-8198-D82A7F2E7CAA       55317        26620   2.243695e+07
1FCCE949-B97D-440C-BE1B-FFB03D0267CE       64285        26640   2.142788e+07
C0C6D0AA-1F16-4331-AF91-CB5517834048       67022        29428   2.061480e+07
BB895E1A-F8DF-4DDC-9402-EC78075254E1       64569        26432   2.025584e+07
D4918402-C81C-4AA4-952B-4CDD49914817       63915        25504   2.022708e+07
CEEFC64C-F2BA-48C9-AF65-1782F56B7D3E       79676        36541   2.006432e+07
6A59311B-F73D-450D-A652-2138139FD04D       63762        33902   1.908184e+07
E750C439-CB35-4A5E-AC2C-FDAB07E891FC       62103        31782   1.875631e+07
A80426BB-750B-4E07-8D37-2FCD6ACEDE6A       46539        21436   1.830992e+07
D41FE965-A901-41B0-9853-9BD05C8F053F       67956        25414   1.826201e+07
13B5BEFF-2DC3-4A51-BB7A-034DAAB0F318       63999        27467   1.824798e+07
631B010D-8D52-44A5-86F0-D063AB87B721       61956        27814   1.815222e+07
096D6728-F791-462F-9EDE-F03C4D485E69       44477        22616   1.776746e+07
85B3A4AC-A0AF-48A2-A306-C39DC2149082       51727        20203   1.769118e+07
611551DF-5D5B-462E-9E9B-0C220A851837       62324        24771   1.733465e+07
FE6D471C-A328-49F1-A769-A2ADD53D24FC       55152        13809   1.685796e+07

# Invoice Items

In [13]:
# del invoice_items_df

In [14]:
invoice_items_df = pd.read_parquet("invoiceitems.parquet", engine="fastparquet")

In [15]:
invoice_df.dtypes

InvoiceID                              object
InvoiceNumber                          object
ModifiedOn                     datetime64[ns]
BranchID                               object
TransCustomerID                        object
CustomerID                             object
CustomerVehicleID                      object
SystemUserID                           object
InvoiceDate                    datetime64[ns]
InvoiceDueDate                 datetime64[ns]
InvoiceBeforeDiscountAmount           float64
InvoiceDiscountAmount                 float64
InvoiceBeforeTaxAmount                float64
InvoiceTaxAmount                      float64
InvoiceTotalAmount                    float64
InvoiceItemCost                       float64
IsFleet                                 int64
IsPMS                                   int64
CustomerContractID                     object
CustomerContractType                   object
WorkOrderNumber                        object
WorkOrderStartDate             datetime64[ns]
WorkOrderEndDate               datetime64[ns]
WorkOrderMileage                        int64
PreviousMileage                         int64
PreviousVisitDate              datetime64[ns]
NewOrExistingCustomer                  object
NewCustomer                             int64
NewVehicle                              int64
Warranty                                int64
PMSID                                  object
PMSName                                object
InvoiceType                            object
ServiceType                            object
StationBrand                           object
dtype: object

In [16]:
invoice_items_df.groupby(["ServiceItemCode"]).agg({
    ""
})

AttributeError: 'SeriesGroupBy' object has no attribute ''

In [17]:
invoice_items_df[invoice_items_df["ServiceName"].str.lower().str.contains("tyre")].head()

,InvoiceID,InvoiceServiceID,ServiceBeforeDiscountAmount,ServiceTotalDiscountAmount,ServiceBeforeTaxAmount,ServiceTaxAmount,ServiceTotalAmount,WithoutExtraServiceBeforeDiscountAmount,WithoutExtraServiceTotalDiscountAmount,WithoutExtraServiceBeforeTaxAmount,WithoutExtraServiceTaxAmount,WithoutExtraServiceTotalAmount,ServiceItemGroupDefaultName,ServiceItemDefaultName,ServiceItemCode,ServiceManufacturerDefaultName,ItemBaseQuantity,ServiceItemCostAmount,ItemBeforeDiscountAmount,ItemTotalDiscountAmount,ItemBeforeTaxAmount,ItemTaxAmount,ItemTotalAmount,WithoutExtraItemBeforeDiscountAmount,WithoutExtraItemTotalDiscountAmount,WithoutExtraItemBeforeTaxAmount,WithoutExtraItemTaxAmount,WithoutExtraItemTotalAmount,ExtraItemBeforeDiscountAmount,ExtraItemTotalDiscountAmount,ExtraItemBeforeTaxAmount,ExtraItemTaxAmount,ExtraItemTotalAmount,InvoiceServiceItemPrice,ServiceName,OilType,ExtraOilQTY,OilCustomer,ServicePackageType,ServicePackageName,ServicePricingType,ServiceGroupName,StationBrand
81,642F1B1C-C6A4-4B14-A702-2761AAE2C337,E5738C43-A1EE-40D3-8274-0B6E8578F4EA,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,Tyres 17 Inch,Nexen 225/55 R17 TL CP643,Nexen-225/55R17,Nexen,1.0,296.0,339.1304,0.0000,339.1304,50.8696,390.0,339.1304,0.0000,339.1304,50.8696,390.0,0.0,0.0,0.0,0.0,0.0,0.0,Tyre Sales 17 Inch,,0.0,0,None,None,LaborOnly,REVOLVE,PE
116,BB0C6295-5ADB-4738-911E-F30B8CB70640,298103E3-2BB9-40F5-A8E0-4FC169AC121A,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,Tyres 19 Inch,Nexen-235/55R19 105W TL NFeraSU1,Nexen-235/55R19,Nexen,1.0,335.0,455.6522,113.9130,341.7391,51.2609,393.0,455.6522,113.9130,341.7391,51.2609,393.0,0.0,0.0,0.0,0.0,0.0,0.0,Tyre Sales 19 Inch,,0.0,0,None,None,LaborOnly,REVOLVE,PE
132,7A77FBD3-D177-4031-BB14-AFFE84E6D085,9BCDBC77-DE35-4A48-ACCD-7749F2FFBF00,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,Tyres 15 Inch,Nexen 195/65 R15 TL CP672,Nexen-195/65R15,Nexen,1.0,188.0,233.0435,23.3043,209.7391,31.4609,241.2,233.0435,23.3043,209.7391,31.4609,241.2,0.0,0.0,0.0,0.0,0.0,0.0,Tyre Sales 15 Inch,,0.0,0,None,None,LaborOnly,REVOLVE,PE
202,B500025A-6ADE-4A2B-A7E6-AFF95DDA0684,F3CE75CE-8DA0-4FF5-9767-33D9232D9AA7,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,Tyres 14 Inch,Nexen-185/70 R14 TL CP661,Nexen-185/70R14,Nexen,1.0,155.0,199.1304,19.9130,179.2174,26.8826,206.1,199.1304,19.9130,179.2174,26.8826,206.1,0.0,0.0,0.0,0.0,0.0,0.0,Tyre Sales 14 Inch,,0.0,0,None,None,LaborOnly,REVOLVE,PE
219,642F1B1C-C6A4-4B14-A702-2761AAE2C337,FBD59047-9D15-40A9-A5BC-419491FF3A4B,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,Tyres 17 Inch,Nexen 225/55 R17 TL CP643,Nexen-225/55R17,Nexen,1.0,296.0,339.1304,0.0000,339.1304,50.8696,390.0,339.1304,0.0000,339.1304,50.8696,390.0,0.0,0.0,0.0,0.0,0.0,0.0,Tyre Sales 17 Inch,,0.0,0,None,None,LaborOnly,REVOLVE,PE

In [18]:
invoice_id = "642F1B1C-C6A4-4B14-A702-2761AAE2C337"

display(invoice_df[invoice_df["InvoiceID"] == invoice_id])
display(invoice_items_df[invoice_items_df["InvoiceID"] == invoice_id])

,InvoiceID,InvoiceNumber,ModifiedOn,BranchID,TransCustomerID,CustomerID,CustomerVehicleID,SystemUserID,InvoiceDate,InvoiceDueDate,InvoiceBeforeDiscountAmount,InvoiceDiscountAmount,InvoiceBeforeTaxAmount,InvoiceTaxAmount,InvoiceTotalAmount,InvoiceItemCost,IsFleet,IsPMS,CustomerContractID,CustomerContractType,WorkOrderNumber,WorkOrderStartDate,WorkOrderEndDate,WorkOrderMileage,PreviousMileage,PreviousVisitDate,NewOrExistingCustomer,NewCustomer,NewVehicle,Warranty,PMSID,PMSName,InvoiceType,ServiceType,StationBrand
38308,642F1B1C-C6A4-4B14-A702-2761AAE2C337,M-50008-47797,2023-11-15 04:20:12,CFA12D3E-C63C-4D5C-B9F2-899BF5560431,45C47696-1AFE-4151-B753-7C0B239E42BF,9AFEC418-0E77-41BA-A47A-2B83A7C924A6,320C63C8-2F8C-43D8-849E-9B78B24F6B44,D19FD20F-01F8-4D9A-9AEC-FD9AF01C0B1F,2023-11-14 14:14:53,2024-01-13 14:14:53,1017.3913,0.0,1017.3913,152.6087,1170.0,888.0,0,0,59C293D1-78DF-430A-921E-5DC4DAAD8C39,PE,50008-48766,2023-11-14 13:59:35,2023-11-14 14:14:53,229740,221500,2023-06-25 23:11:39,Existing Customer,0,0,0,None,None,Credit,Partner,PE

,InvoiceID,InvoiceServiceID,ServiceBeforeDiscountAmount,ServiceTotalDiscountAmount,ServiceBeforeTaxAmount,ServiceTaxAmount,ServiceTotalAmount,WithoutExtraServiceBeforeDiscountAmount,WithoutExtraServiceTotalDiscountAmount,WithoutExtraServiceBeforeTaxAmount,WithoutExtraServiceTaxAmount,WithoutExtraServiceTotalAmount,ServiceItemGroupDefaultName,ServiceItemDefaultName,ServiceItemCode,ServiceManufacturerDefaultName,ItemBaseQuantity,ServiceItemCostAmount,ItemBeforeDiscountAmount,ItemTotalDiscountAmount,ItemBeforeTaxAmount,ItemTaxAmount,ItemTotalAmount,WithoutExtraItemBeforeDiscountAmount,WithoutExtraItemTotalDiscountAmount,WithoutExtraItemBeforeTaxAmount,WithoutExtraItemTaxAmount,WithoutExtraItemTotalAmount,ExtraItemBeforeDiscountAmount,ExtraItemTotalDiscountAmount,ExtraItemBeforeTaxAmount,ExtraItemTaxAmount,ExtraItemTotalAmount,InvoiceServiceItemPrice,ServiceName,OilType,ExtraOilQTY,OilCustomer,ServicePackageType,ServicePackageName,ServicePricingType,ServiceGroupName,StationBrand
81,642F1B1C-C6A4-4B14-A702-2761AAE2C337,E5738C43-A1EE-40D3-8274-0B6E8578F4EA,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,Tyres 17 Inch,Nexen 225/55 R17 TL CP643,Nexen-225/55R17,Nexen,1.0,296.0,339.1304,0.0,339.1304,50.8696,390.0,339.1304,0.0,339.1304,50.8696,390.0,0.0,0.0,0.0,0.0,0.0,0.0,Tyre Sales 17 Inch,,0.0,0,None,None,LaborOnly,REVOLVE,PE
219,642F1B1C-C6A4-4B14-A702-2761AAE2C337,FBD59047-9D15-40A9-A5BC-419491FF3A4B,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,Tyres 17 Inch,Nexen 225/55 R17 TL CP643,Nexen-225/55R17,Nexen,1.0,296.0,339.1304,0.0,339.1304,50.8696,390.0,339.1304,0.0,339.1304,50.8696,390.0,0.0,0.0,0.0,0.0,0.0,0.0,Tyre Sales 17 Inch,,0.0,0,None,None,LaborOnly,REVOLVE,PE
657264,642F1B1C-C6A4-4B14-A702-2761AAE2C337,C5387E5A-47CB-4565-9E9E-A5745BA519F5,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,Tyres 17 Inch,Nexen 225/55 R17 TL CP643,Nexen-225/55R17,Nexen,1.0,296.0,339.1304,0.0,339.1304,50.8696,390.0,339.1304,0.0,339.1304,50.8696,390.0,0.0,0.0,0.0,0.0,0.0,0.0,Tyre Sales 17 Inch,,0.0,0,None,None,LaborOnly,REVOLVE,PE

In [19]:
invoice_items_df[invoice_items_df["ItemBaseQuantity"] > 0].head()

,InvoiceID,InvoiceServiceID,ServiceBeforeDiscountAmount,ServiceTotalDiscountAmount,ServiceBeforeTaxAmount,ServiceTaxAmount,ServiceTotalAmount,WithoutExtraServiceBeforeDiscountAmount,WithoutExtraServiceTotalDiscountAmount,WithoutExtraServiceBeforeTaxAmount,WithoutExtraServiceTaxAmount,WithoutExtraServiceTotalAmount,ServiceItemGroupDefaultName,ServiceItemDefaultName,ServiceItemCode,ServiceManufacturerDefaultName,ItemBaseQuantity,ServiceItemCostAmount,ItemBeforeDiscountAmount,ItemTotalDiscountAmount,ItemBeforeTaxAmount,ItemTaxAmount,ItemTotalAmount,WithoutExtraItemBeforeDiscountAmount,WithoutExtraItemTotalDiscountAmount,WithoutExtraItemBeforeTaxAmount,WithoutExtraItemTaxAmount,WithoutExtraItemTotalAmount,ExtraItemBeforeDiscountAmount,ExtraItemTotalDiscountAmount,ExtraItemBeforeTaxAmount,ExtraItemTaxAmount,ExtraItemTotalAmount,InvoiceServiceItemPrice,ServiceName,OilType,ExtraOilQTY,OilCustomer,ServicePackageType,ServicePackageName,ServicePricingType,ServiceGroupName,StationBrand
1,28D7E7D3-FCD0-439E-B690-C7CA67A576BF,835ADBC8-F892-4B18-8FEC-4B9DD67E7BCC,0.0000,0.0,0.0000,0.0000,0.0,0.0000,0.0,0.0000,0.0000,0.0,Toyota-Oil Filters,Toyota-Oil Filters,TOYO 90915-YZZD4,OEM,1.0,15.0447,42.6087,0.0000,42.6087,6.3913,49.0,42.6087,0.0000,42.6087,6.3913,49.0,0.0,0.0,0.0,0.0,0.0,0.0,Oil Filter Service,,0.0,1,PMS,"Toyota Fortuner GGN 155 &165 5K,15K , 25K ,35K...",LaborAndItems,PE,PE
2,8F250508-C083-4F40-B6C9-EB989754B3C9,BD9AFB1F-411F-4946-846A-CFFA64148774,0.0000,0.0,0.0000,0.0000,0.0,0.0000,0.0,0.0000,0.0000,0.0,Nissan-Oil Filters,Oil Filter,NN1520865F0E,OEM,1.0,14.4600,42.6087,17.0435,25.5652,3.8348,29.4,42.6087,17.0435,25.5652,3.8348,29.4,0.0,0.0,0.0,0.0,0.0,0.0,Oil Filter Service,,0.0,1,PMS,"Nissan Kicks P15 New 20K,60K, .. K.M",LaborAndItems,PE,PE
4,ECE39076-C677-4583-9631-1DD60B15E381,9CDDF0CB-1B51-4A1C-A221-95C7FCE1E904,0.0000,0.0,0.0000,0.0000,0.0,0.0000,0.0,0.0000,0.0000,0.0,Nissan-Miscellaneous,Brake Cleaner Spray,PMS Brake Cleaner Spray,OEM,1.0,9.6383,19.1304,7.6522,11.4783,1.7217,13.2,19.1304,7.6522,11.4783,1.7217,13.2,0.0,0.0,0.0,0.0,0.0,0.0,Parking Brake - Adjust,,0.0,1,PMS,"Altima L34 (2.5L) 10K , 30K ,50K , 70K , 90K …KM",LaborAndItems,PE,PE
5,9FABCF63-8945-4C5B-BFF0-8D5322DF5DC9,EA53F90F-6966-4416-89A0-D1DF9F035EEB,0.0000,0.0,0.0000,0.0000,0.0,0.0000,0.0,0.0000,0.0000,0.0,Oil Filters,Oil Filter,15208-31U01B,OEM,1.0,17.5383,44.3478,17.7391,26.6087,3.9913,30.6,44.3478,17.7391,26.6087,3.9913,30.6,0.0,0.0,0.0,0.0,0.0,0.0,OEM Oil Filter Service,,0.0,0,None,None,LaborOnly,PE,PE
6,2C938061-7569-458D-A918-3546E5159221,6C5ACD80-57D4-4026-A1D2-097AA82F122D,15.6522,0.0,15.6522,2.3478,18.0,15.6522,0.0,15.6522,2.3478,18.0,Oil,Petromin Super 10W30 Engine Oil,BULK10W30,Petromin,3.5,18.1300,70.0000,0.0000,70.0000,10.5000,80.5,70.0000,0.0000,70.0000,10.5000,80.5,0.0,0.0,0.0,0.0,0.0,0.0,Engine Oil change,,0.0,1,Cash Customer,Standard Care,LaborOnly,PE,PE

In [20]:
display(invoice_df[invoice_df["InvoiceID"] == "0000054F-98E7-4A1B-85E7-FF505021DB02"])
display(invoice_items_df[invoice_items_df["InvoiceID"] == "0000054F-98E7-4A1B-85E7-FF505021DB02"])

,InvoiceID,InvoiceNumber,ModifiedOn,BranchID,TransCustomerID,CustomerID,CustomerVehicleID,SystemUserID,InvoiceDate,InvoiceDueDate,InvoiceBeforeDiscountAmount,InvoiceDiscountAmount,InvoiceBeforeTaxAmount,InvoiceTaxAmount,InvoiceTotalAmount,InvoiceItemCost,IsFleet,IsPMS,CustomerContractID,CustomerContractType,WorkOrderNumber,WorkOrderStartDate,WorkOrderEndDate,WorkOrderMileage,PreviousMileage,PreviousVisitDate,NewOrExistingCustomer,NewCustomer,NewVehicle,Warranty,PMSID,PMSName,InvoiceType,ServiceType,StationBrand
547801,0000054F-98E7-4A1B-85E7-FF505021DB02,M-1600-6455,2023-01-29 03:20:59,BBD69E26-7BE0-41D0-BC40-D395C7D1DEDF,51392616-9B76-4435-8C0E-43C0139BCA1F,51392616-9B76-4435-8C0E-43C0139BCA1F,7272896E-F429-47A5-88F8-1195CE25FB9D,9DE400AB-4766-4CC0-B3A1-04DC6B61EBD5,2023-01-28 22:36:40,2023-01-28 22:36:40,305.2174,35.6522,269.5652,40.4348,310.0,56.499,0,0,None,None,1600-6510,2023-01-28 22:00:56,2023-01-28 22:36:40,87862,79919,2022-12-13 09:13:41,Existing Customer,0,0,1,None,None,Cash,PE Service,PE

,InvoiceID,InvoiceServiceID,ServiceBeforeDiscountAmount,ServiceTotalDiscountAmount,ServiceBeforeTaxAmount,ServiceTaxAmount,ServiceTotalAmount,WithoutExtraServiceBeforeDiscountAmount,WithoutExtraServiceTotalDiscountAmount,WithoutExtraServiceBeforeTaxAmount,WithoutExtraServiceTaxAmount,WithoutExtraServiceTotalAmount,ServiceItemGroupDefaultName,ServiceItemDefaultName,ServiceItemCode,ServiceManufacturerDefaultName,ItemBaseQuantity,ServiceItemCostAmount,ItemBeforeDiscountAmount,ItemTotalDiscountAmount,ItemBeforeTaxAmount,ItemTaxAmount,ItemTotalAmount,WithoutExtraItemBeforeDiscountAmount,WithoutExtraItemTotalDiscountAmount,WithoutExtraItemBeforeTaxAmount,WithoutExtraItemTaxAmount,WithoutExtraItemTotalAmount,ExtraItemBeforeDiscountAmount,ExtraItemTotalDiscountAmount,ExtraItemBeforeTaxAmount,ExtraItemTaxAmount,ExtraItemTotalAmount,InvoiceServiceItemPrice,ServiceName,OilType,ExtraOilQTY,OilCustomer,ServicePackageType,ServicePackageName,ServicePricingType,ServiceGroupName,StationBrand
1504069,0000054F-98E7-4A1B-85E7-FF505021DB02,0D09A67B-1CE1-4E55-AF99-07199CDDCA43,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,Oil Synthetic,Petromin Super Synthetic 5w30 - 1L,PET A-1 SYN,Petromin,6.0,49.3032,269.5652,0.0000,269.5652,40.4348,310.0,179.710134,0.0000,179.710134,26.956534,206.666667,89.855066,0.0,89.855066,13.478266,103.333333,0.0,Engine Oil change,,2.0,1,Cash Customer,PE SAR 180 Synthetic Oil Package,LaborAndItems,PE,PE
1567819,0000054F-98E7-4A1B-85E7-FF505021DB02,51EA8C02-ABAC-4FE6-8AC6-6545F301FE84,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,Oil Filters,Oil Filter,M3614,MIGHTY,1.0,7.1958,35.6522,35.6522,0.0000,0.0000,0.0,35.652200,35.6522,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,0.0,Mighty Oil Filter Service,,0.0,0,None,None,LaborOnly,PE,PE

In [21]:
invoice_items_df["ItemBaseQuantity"] = np.where(invoice_items_df["ServiceItemGroupDefaultName"].isnull(), 1, invoice_items_df["ItemBaseQuantity"])
invoice_items_df["ServiceItemDefaultName"] = np.where(invoice_items_df["ServiceItemGroupDefaultName"].isnull(), "Service", invoice_items_df["ServiceItemDefaultName"])
invoice_items_df["ServiceItemGroupDefaultName"] = np.where(invoice_items_df["ServiceItemGroupDefaultName"].isnull(), "Service", invoice_items_df["ServiceItemGroupDefaultName"])
invoice_items_df["ServiceItemCode"] = np.where(invoice_items_df["ServiceItemGroupDefaultName"].isnull(), "Service", invoice_items_df["ServiceItemCode"])
invoice_items_df["sku"] = invoice_items_df["ServiceName"] + " | " +  invoice_items_df["ServiceItemGroupDefaultName"] + " | " + invoice_items_df["ServiceItemDefaultName"] + " | " + invoice_items_df["ServiceItemCode"] + " | " + invoice_items_df["ServicePackageName"] 
invoice_items_df["InvoiceTotalAmount"] = invoice_items_df["ServiceTotalAmount"] + invoice_items_df["ItemTotalAmount"]
invoice_items_df["InvoiceBeforeTaxAmount"] = invoice_items_df["ServiceBeforeTaxAmount"] + invoice_items_df["ItemBeforeTaxAmount"]
invoice_items_df["InvoiceBeforeDiscountAmount"] = invoice_items_df["ServiceBeforeDiscountAmount"] + invoice_items_df["ItemBeforeDiscountAmount"]
invoice_items_df["InvoiceTotalDiscountAmount"] = invoice_items_df["ServiceTotalDiscountAmount"] + invoice_items_df["ItemTotalDiscountAmount"]
invoice_items_df["InvoiceGrossMargin"] = invoice_items_df["InvoiceBeforeTaxAmount"] - invoice_items_df["ServiceItemCostAmount"]

In [22]:
set(invoice_df.columns).intersection(set(invoice_items_df.columns))

{'InvoiceBeforeDiscountAmount',
 'InvoiceBeforeTaxAmount',
 'InvoiceID',
 'InvoiceTotalAmount',
 'StationBrand'}

In [23]:
invoice_cols = ["InvoiceID", "CustomerID", "CustomerVehicleID", "BranchID", "InvoiceDate", "IsFleet", "IsPMS", "WorkOrderMileage", "PreviousMileage", "NewCustomer", "NewVehicle", "Warranty"]
invoice_items_cols = ["InvoiceID", "ServiceName", "ServiceItemGroupDefaultName", "ServiceItemDefaultName", "ServiceItemCode", "ServicePackageName", "sku", "ItemBaseQuantity", "ServiceItemCostAmount", "InvoiceTotalDiscountAmount", "InvoiceBeforeDiscountAmount", 'InvoiceBeforeTaxAmount', 'InvoiceTotalAmount', "InvoiceGrossMargin"]

In [24]:
invoice_df["InvoiceID"] = invoice_df["InvoiceID"].astype("string")
invoice_items_df["InvoiceID"] = invoice_items_df["InvoiceID"].astype("string")

In [25]:
# 3m
invoice_df.shape, invoice_df.drop_duplicates().shape, invoice_df.drop(columns="StationBrand").drop_duplicates().shape, invoice_df.drop_duplicates(subset=invoice_cols).shape

((16202548, 35), (16202548, 35), (16202548, 34), (16202526, 35))

In [26]:
# 10m
invoice_items_df.shape, invoice_items_df.drop_duplicates().shape, invoice_items_df.drop(columns="StationBrand").drop_duplicates().shape, invoice_items_df.drop_duplicates(subset=invoice_items_cols).shape

((48413226, 49), (48413226, 49), (48413226, 48), (48080891, 49))

In [27]:
# 2m
transactions_df = pd.merge(
    invoice_df[invoice_cols],
    invoice_items_df[invoice_items_cols],
    on="InvoiceID",
    how="inner"
)

In [28]:
# 2m
transactions_df.shape, transactions_df.drop_duplicates().shape

((48413287, 25), (48080891, 25))

In [ ]:
# 5m
transactions_grouped_df = transactions_df.drop_duplicates().groupby(
    ["InvoiceID", "CustomerID", "CustomerVehicleID", "BranchID", "InvoiceDate", "ServiceName", "ServiceItemGroupDefaultName", "ServiceItemDefaultName", "ServiceItemCode", "ServicePackageName", "sku"],
    as_index=False
).agg({
    "IsFleet": "max",
    "IsPMS": "max",
    "WorkOrderMileage": "max",
    "PreviousMileage": "max",
    "NewCustomer": "max",
    "NewVehicle": "max",
    "Warranty": "max",
    "ItemBaseQuantity": "sum",
    "ServiceItemCostAmount": "sum",
    "InvoiceTotalDiscountAmount": "sum",
    "InvoiceBeforeTaxAmount": "sum",
    "InvoiceBeforeDiscountAmount": "sum",
    "InvoiceTotalAmount": "sum",
    "InvoiceGrossMargin": "sum",
})

In [30]:
transactions_grouped_df["InvoiceGrossMargin_perc"] = transactions_grouped_df["InvoiceGrossMargin"] / transactions_grouped_df["InvoiceTotalAmount"]
transactions_grouped_df["InvoiceGrossMargin_perc"] = np.where(transactions_grouped_df["InvoiceGrossMargin_perc"].isnull(), 0, transactions_grouped_df["InvoiceGrossMargin_perc"])
transactions_grouped_df["hasDiscount"] = np.where(transactions_grouped_df["InvoiceTotalDiscountAmount"] > 0, 1, 0)

In [31]:
transactions_grouped_df["MileageBetweenVisits"] = transactions_grouped_df["WorkOrderMileage"] - transactions_grouped_df["PreviousMileage"]
transactions_grouped_df["MileageBetweenVisits_perc"] = transactions_grouped_df["MileageBetweenVisits"] / transactions_grouped_df["PreviousMileage"]

In [32]:
invoice_id = "642F1B1C-C6A4-4B14-A702-2761AAE2C337"

display(invoice_df[invoice_df["InvoiceID"] == invoice_id])
display(invoice_items_df[invoice_items_df["InvoiceID"] == invoice_id])
display(transactions_grouped_df[transactions_grouped_df["InvoiceID"] == invoice_id])

,InvoiceID,InvoiceNumber,ModifiedOn,BranchID,TransCustomerID,CustomerID,CustomerVehicleID,SystemUserID,InvoiceDate,InvoiceDueDate,InvoiceBeforeDiscountAmount,InvoiceDiscountAmount,InvoiceBeforeTaxAmount,InvoiceTaxAmount,InvoiceTotalAmount,InvoiceItemCost,IsFleet,IsPMS,CustomerContractID,CustomerContractType,WorkOrderNumber,WorkOrderStartDate,WorkOrderEndDate,WorkOrderMileage,PreviousMileage,PreviousVisitDate,NewOrExistingCustomer,NewCustomer,NewVehicle,Warranty,PMSID,PMSName,InvoiceType,ServiceType,StationBrand
38308,642F1B1C-C6A4-4B14-A702-2761AAE2C337,M-50008-47797,2023-11-15 04:20:12,CFA12D3E-C63C-4D5C-B9F2-899BF5560431,45C47696-1AFE-4151-B753-7C0B239E42BF,9AFEC418-0E77-41BA-A47A-2B83A7C924A6,320C63C8-2F8C-43D8-849E-9B78B24F6B44,D19FD20F-01F8-4D9A-9AEC-FD9AF01C0B1F,2023-11-14 14:14:53,2024-01-13 14:14:53,1017.3913,0.0,1017.3913,152.6087,1170.0,888.0,0,0,59C293D1-78DF-430A-921E-5DC4DAAD8C39,PE,50008-48766,2023-11-14 13:59:35,2023-11-14 14:14:53,229740,221500,2023-06-25 23:11:39,Existing Customer,0,0,0,None,None,Credit,Partner,PE

,InvoiceID,InvoiceServiceID,ServiceBeforeDiscountAmount,ServiceTotalDiscountAmount,ServiceBeforeTaxAmount,ServiceTaxAmount,ServiceTotalAmount,WithoutExtraServiceBeforeDiscountAmount,WithoutExtraServiceTotalDiscountAmount,WithoutExtraServiceBeforeTaxAmount,WithoutExtraServiceTaxAmount,WithoutExtraServiceTotalAmount,ServiceItemGroupDefaultName,ServiceItemDefaultName,ServiceItemCode,ServiceManufacturerDefaultName,ItemBaseQuantity,ServiceItemCostAmount,ItemBeforeDiscountAmount,ItemTotalDiscountAmount,ItemBeforeTaxAmount,ItemTaxAmount,ItemTotalAmount,WithoutExtraItemBeforeDiscountAmount,WithoutExtraItemTotalDiscountAmount,WithoutExtraItemBeforeTaxAmount,WithoutExtraItemTaxAmount,WithoutExtraItemTotalAmount,ExtraItemBeforeDiscountAmount,ExtraItemTotalDiscountAmount,ExtraItemBeforeTaxAmount,ExtraItemTaxAmount,ExtraItemTotalAmount,InvoiceServiceItemPrice,ServiceName,OilType,ExtraOilQTY,OilCustomer,ServicePackageType,ServicePackageName,ServicePricingType,ServiceGroupName,StationBrand,sku,InvoiceTotalAmount,InvoiceBeforeTaxAmount,InvoiceBeforeDiscountAmount,InvoiceTotalDiscountAmount,InvoiceGrossMargin
81,642F1B1C-C6A4-4B14-A702-2761AAE2C337,E5738C43-A1EE-40D3-8274-0B6E8578F4EA,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,Tyres 17 Inch,Nexen 225/55 R17 TL CP643,Nexen-225/55R17,Nexen,1.0,296.0,339.1304,0.0,339.1304,50.8696,390.0,339.1304,0.0,339.1304,50.8696,390.0,0.0,0.0,0.0,0.0,0.0,0.0,Tyre Sales 17 Inch,,0.0,0,None,None,LaborOnly,REVOLVE,PE,NaN,390.0,339.1304,339.1304,0.0,43.1304
219,642F1B1C-C6A4-4B14-A702-2761AAE2C337,FBD59047-9D15-40A9-A5BC-419491FF3A4B,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,Tyres 17 Inch,Nexen 225/55 R17 TL CP643,Nexen-225/55R17,Nexen,1.0,296.0,339.1304,0.0,339.1304,50.8696,390.0,339.1304,0.0,339.1304,50.8696,390.0,0.0,0.0,0.0,0.0,0.0,0.0,Tyre Sales 17 Inch,,0.0,0,None,None,LaborOnly,REVOLVE,PE,NaN,390.0,339.1304,339.1304,0.0,43.1304
657264,642F1B1C-C6A4-4B14-A702-2761AAE2C337,C5387E5A-47CB-4565-9E9E-A5745BA519F5,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,Tyres 17 Inch,Nexen 225/55 R17 TL CP643,Nexen-225/55R17,Nexen,1.0,296.0,339.1304,0.0,339.1304,50.8696,390.0,339.1304,0.0,339.1304,50.8696,390.0,0.0,0.0,0.0,0.0,0.0,0.0,Tyre Sales 17 Inch,,0.0,0,None,None,LaborOnly,REVOLVE,PE,NaN,390.0,339.1304,339.1304,0.0,43.1304

Empty DataFrame
Columns: [InvoiceID, CustomerID, CustomerVehicleID, BranchID, InvoiceDate, ServiceName, ServiceItemGroupDefaultName, ServiceItemDefaultName, ServiceItemCode, ServicePackageName, sku, IsFleet, IsPMS, WorkOrderMileage, PreviousMileage, NewCustomer, NewVehicle, Warranty, ItemBaseQuantity, ServiceItemCostAmount, InvoiceTotalDiscountAmount, InvoiceBeforeTaxAmount, InvoiceBeforeDiscountAmount, InvoiceTotalAmount, InvoiceGrossMargin, InvoiceGrossMargin_perc, hasDiscount, MileageBetweenVisits, MileageBetweenVisits_perc]
Index: []

In [33]:
transactions_grouped_df.head()

,InvoiceID,CustomerID,CustomerVehicleID,BranchID,InvoiceDate,ServiceName,ServiceItemGroupDefaultName,ServiceItemDefaultName,ServiceItemCode,ServicePackageName,sku,IsFleet,IsPMS,WorkOrderMileage,PreviousMileage,NewCustomer,NewVehicle,Warranty,ItemBaseQuantity,ServiceItemCostAmount,InvoiceTotalDiscountAmount,InvoiceBeforeTaxAmount,InvoiceBeforeDiscountAmount,InvoiceTotalAmount,InvoiceGrossMargin,InvoiceGrossMargin_perc,hasDiscount,MileageBetweenVisits,MileageBetweenVisits_perc
0,0000054F-98E7-4A1B-85E7-FF505021DB02,51392616-9B76-4435-8C0E-43C0139BCA1F,7272896E-F429-47A5-88F8-1195CE25FB9D,BBD69E26-7BE0-41D0-BC40-D395C7D1DEDF,2023-01-28 22:36:40,Engine Oil change,Oil Synthetic,Petromin Super Synthetic 5w30 - 1L,PET A-1 SYN,PE SAR 180 Synthetic Oil Package,Engine Oil change | Oil Synthetic | Petromin S...,0,0,87862,79919,0,0,1,6.0,49.3032,0.0,269.5652,269.5652,310.00,220.2620,0.710523,0,7943,0.099388
1,0000058D-4FEF-42C4-BF36-9FF2744953D0,AF8F3733-EE8E-493C-AD23-2F15BF80CF16,151779EE-F4CE-4F5B-9430-393D04006AAE,6A0C15EA-2F3C-4F05-99AE-8481109A13A1,2021-03-25 14:02:18,Engine Oil change,Oil Synthetic,Petromin Super Synthetic 5w30 - 1L,PET A-1 SYN,Gold Synthetic Service,Engine Oil change | Oil Synthetic | Petromin S...,1,0,152283,140643,0,0,0,4.0,18.6668,0.0,120.0000,120.0000,138.00,101.3332,0.734299,0,11640,0.082763
2,0000088D-5070-4C46-AC94-3B619CA713C2,0A4575B2-347C-490D-ABA2-C220BBA9D600,99A94E11-0B9E-4911-B9EF-6457667AE93F,AC98BF1B-85AD-4745-A759-E7D7652CA5EF,2025-04-11 17:20:50,Engine Oil change,Oil Synthetic,Petromin A-1 Super Synthetic 5W-30 (6x4 Ltr),PET A-1 SYN 5W30 - 6X4,199 Synthetic Oil,Engine Oil change | Oil Synthetic | Petromin A...,0,0,156222,146566,0,0,0,4.0,31.5268,0.0,173.0500,173.0500,199.01,141.5232,0.711136,0,9656,0.065882
3,00000B21-F29D-4A25-B205-7D1593882D9E,B7A259AC-0900-4E69-A2EF-78ADC38588BB,77AAD08D-C090-49C5-A7ED-1C41FA5F65DB,55D433BA-7267-4E6E-9D9E-2FDDC8DFD143,2024-12-10 18:41:12,Engine Oil change,Oil,Petromin Super 10W30 Engine Oil,BULK10W30,"Hyundai ELANTRA 1.6L 5k,15k,25k,35k,45k,55k,65...",Engine Oil change | Oil | Petromin Super 10W30...,0,1,355309,350226,0,0,0,4.0,27.2800,0.0,117.3900,117.3900,135.00,90.1100,0.667481,0,5083,0.014513
4,00000B21-F29D-4A25-B205-7D1593882D9E,B7A259AC-0900-4E69-A2EF-78ADC38588BB,77AAD08D-C090-49C5-A7ED-1C41FA5F65DB,55D433BA-7267-4E6E-9D9E-2FDDC8DFD143,2024-12-10 18:41:12,Oil Filter Service,Hyundai-Oil Filters,Engine Oil Filter,HYUN 26300-35505,"Hyundai ELANTRA 1.6L 5k,15k,25k,35k,45k,55k,65...",Oil Filter Service | Hyundai-Oil Filters | Eng...,0,1,355309,350226,0,0,0,1.0,11.9554,0.0,39.1300,39.1300,45.00,27.1746,0.603880,0,5083,0.014513

In [34]:
transactions_grouped_df[["InvoiceID", "sku"]].duplicated().sum()

0

In [35]:
transactions_grouped_df[transactions_grouped_df[["InvoiceID", "sku"]].duplicated()].head()

Empty DataFrame
Columns: [InvoiceID, CustomerID, CustomerVehicleID, BranchID, InvoiceDate, ServiceName, ServiceItemGroupDefaultName, ServiceItemDefaultName, ServiceItemCode, ServicePackageName, sku, IsFleet, IsPMS, WorkOrderMileage, PreviousMileage, NewCustomer, NewVehicle, Warranty, ItemBaseQuantity, ServiceItemCostAmount, InvoiceTotalDiscountAmount, InvoiceBeforeTaxAmount, InvoiceBeforeDiscountAmount, InvoiceTotalAmount, InvoiceGrossMargin, InvoiceGrossMargin_perc, hasDiscount, MileageBetweenVisits, MileageBetweenVisits_perc]
Index: []

In [36]:
display(transactions_grouped_df[transactions_grouped_df["InvoiceID"] == "003E4109-6387-4AA5-9DFC-F99637C71A4D"])
display(invoice_df[invoice_df["InvoiceID"] == "003E4109-6387-4AA5-9DFC-F99637C71A4D"])
display(invoice_items_df[invoice_items_df["InvoiceID"] == "003E4109-6387-4AA5-9DFC-F99637C71A4D"])

,InvoiceID,CustomerID,CustomerVehicleID,BranchID,InvoiceDate,ServiceName,ServiceItemGroupDefaultName,ServiceItemDefaultName,ServiceItemCode,ServicePackageName,sku,IsFleet,IsPMS,WorkOrderMileage,PreviousMileage,NewCustomer,NewVehicle,Warranty,ItemBaseQuantity,ServiceItemCostAmount,InvoiceTotalDiscountAmount,InvoiceBeforeTaxAmount,InvoiceBeforeDiscountAmount,InvoiceTotalAmount,InvoiceGrossMargin,InvoiceGrossMargin_perc,hasDiscount,MileageBetweenVisits,MileageBetweenVisits_perc
16799,003E4109-6387-4AA5-9DFC-F99637C71A4D,54F782F6-CE55-4AA2-B342-4140898F567B,E766FEFD-23D5-4951-AFF4-2BC37E398FF2,1407D6E1-FEA5-49E2-AE3B-BF89C1F79817,2022-09-30 19:54:04,Engine Oil change,Oil Synthetic,Petromin Super Synthetic 5w30 - 1L,PET A-1 SYN,Golden Discount Synthetic,Engine Oil change | Oil Synthetic | Petromin S...,0,0,123654,123456,0,0,0,4.0,30.780,0.0000,0.0000,0.0000,0.00,-30.7800,-inf,0,198,0.001604
16800,003E4109-6387-4AA5-9DFC-F99637C71A4D,54F782F6-CE55-4AA2-B342-4140898F567B,E766FEFD-23D5-4951-AFF4-2BC37E398FF2,1407D6E1-FEA5-49E2-AE3B-BF89C1F79817,2022-09-30 19:54:04,Engine Oil change,Oil Synthetic,Petromin Super Synthetic 5w30 - 1L,PET A-1 SYN,Golden Discount Synthetic 170,Engine Oil change | Oil Synthetic | Petromin S...,0,0,123654,123456,0,0,0,9.0,69.255,33.6957,235.8695,269.5652,271.25,166.6145,0.614247,1,198,0.001604

,InvoiceID,InvoiceNumber,ModifiedOn,BranchID,TransCustomerID,CustomerID,CustomerVehicleID,SystemUserID,InvoiceDate,InvoiceDueDate,InvoiceBeforeDiscountAmount,InvoiceDiscountAmount,InvoiceBeforeTaxAmount,InvoiceTaxAmount,InvoiceTotalAmount,InvoiceItemCost,IsFleet,IsPMS,CustomerContractID,CustomerContractType,WorkOrderNumber,WorkOrderStartDate,WorkOrderEndDate,WorkOrderMileage,PreviousMileage,PreviousVisitDate,NewOrExistingCustomer,NewCustomer,NewVehicle,Warranty,PMSID,PMSName,InvoiceType,ServiceType,StationBrand
6938727,003E4109-6387-4AA5-9DFC-F99637C71A4D,M-2074-1062,2022-09-30 21:50:59,1407D6E1-FEA5-49E2-AE3B-BF89C1F79817,54F782F6-CE55-4AA2-B342-4140898F567B,54F782F6-CE55-4AA2-B342-4140898F567B,E766FEFD-23D5-4951-AFF4-2BC37E398FF2,96885E57-CE30-4A29-908A-D4E9423E20E7,2022-09-30 19:54:04,2022-09-30 19:54:04,269.5652,33.6957,235.8696,35.3804,271.25,100.035,0,0,None,None,2074-1061,2022-09-30 19:53:17,2022-09-30 19:54:04,123654,123456,2022-09-30 19:44:15,Existing Customer,0,0,0,None,None,Cash,PE Service,PE

,InvoiceID,InvoiceServiceID,ServiceBeforeDiscountAmount,ServiceTotalDiscountAmount,ServiceBeforeTaxAmount,ServiceTaxAmount,ServiceTotalAmount,WithoutExtraServiceBeforeDiscountAmount,WithoutExtraServiceTotalDiscountAmount,WithoutExtraServiceBeforeTaxAmount,WithoutExtraServiceTaxAmount,WithoutExtraServiceTotalAmount,ServiceItemGroupDefaultName,ServiceItemDefaultName,ServiceItemCode,ServiceManufacturerDefaultName,ItemBaseQuantity,ServiceItemCostAmount,ItemBeforeDiscountAmount,ItemTotalDiscountAmount,ItemBeforeTaxAmount,ItemTaxAmount,ItemTotalAmount,WithoutExtraItemBeforeDiscountAmount,WithoutExtraItemTotalDiscountAmount,WithoutExtraItemBeforeTaxAmount,WithoutExtraItemTaxAmount,WithoutExtraItemTotalAmount,ExtraItemBeforeDiscountAmount,ExtraItemTotalDiscountAmount,ExtraItemBeforeTaxAmount,ExtraItemTaxAmount,ExtraItemTotalAmount,InvoiceServiceItemPrice,ServiceName,OilType,ExtraOilQTY,OilCustomer,ServicePackageType,ServicePackageName,ServicePricingType,ServiceGroupName,StationBrand,sku,InvoiceTotalAmount,InvoiceBeforeTaxAmount,InvoiceBeforeDiscountAmount,InvoiceTotalDiscountAmount,InvoiceGrossMargin
20625885,003E4109-6387-4AA5-9DFC-F99637C71A4D,BBE02783-002F-4674-8C67-BD64258C38BE,-215.6522,-26.9565,-188.6957,-28.3043,-217.0,-215.6522,-26.9565,-188.6957,-28.3043,-217.0,Oil Synthetic,Petromin Super Synthetic 5w30 - 1L,PET A-1 SYN,Petromin,9.0,69.255,485.2174,60.6522,424.5652,63.6848,488.25,215.652178,26.956534,188.695645,28.304356,217.0,269.565222,33.695666,235.869555,35.380444,271.25,0.0,Engine Oil change,,5.0,1,Cash Customer,Golden Discount Synthetic 170,LaborAndItems,PE,PE,Engine Oil change | Oil Synthetic | Petromin S...,271.25,235.8695,269.5652,33.6957,166.6145
20628204,003E4109-6387-4AA5-9DFC-F99637C71A4D,B5FA5EBD-BB0C-4327-9564-D76511F28B72,-215.6522,0.0000,-215.6522,-32.3478,-248.0,-215.6522,0.0000,-215.6522,-32.3478,-248.0,Oil Synthetic,Petromin Super Synthetic 5w30 - 1L,PET A-1 SYN,Petromin,4.0,30.780,215.6522,0.0000,215.6522,32.3478,248.00,215.652200,0.000000,215.652200,32.347800,248.0,0.000000,0.000000,0.000000,0.000000,0.00,0.0,Engine Oil change,,0.0,1,Cash Customer,Golden Discount Synthetic,LaborAndItems,PE,PE,Engine Oil change | Oil Synthetic | Petromin S...,0.00,0.0000,0.0000,0.0000,-30.7800

In [37]:
transactions_grouped_df.groupby(["InvoiceDate"]).agg({"InvoiceID": "nunique"})

                     InvoiceID
InvoiceDate
2020-07-11 09:17:21          1
2020-07-11 10:37:13          1
2020-07-11 10:47:09          1
2020-07-11 14:39:20          1
2020-07-11 16:21:47          1
...                        ...
2025-07-18 01:54:31          1
2025-07-18 01:58:00          1
2025-07-18 01:59:39          1
2025-07-18 02:09:24          1
2025-07-18 02:19:11          1

[13371122 rows x 1 columns]

In [38]:
transactions_grouped_df["InvoiceDate"].min(), transactions_grouped_df["InvoiceDate"].max()

(Timestamp('2020-07-11 09:17:21'), Timestamp('2025-07-18 02:19:11'))

In [39]:
# 
transactions_grouped_df.to_parquet("../data/01_raw/transactions_origin.parquet", engine="fastparquet", index=False)

In [ ]:
# del invoice_items_df

In [1]:
1+1

2

In [ ]:
invoice_items_df.head()

,InvoiceID,InvoiceServiceID,ServiceBeforeDiscountAmount,ServiceTotalDiscountAmount,ServiceBeforeTaxAmount,ServiceTaxAmount,ServiceTotalAmount,WithoutExtraServiceBeforeDiscountAmount,WithoutExtraServiceTotalDiscountAmount,WithoutExtraServiceBeforeTaxAmount,...,InvoiceServiceItemPrice,ServiceName,OilType,ExtraOilQTY,OilCustomer,ServicePackageType,ServicePackageName,ServicePricingType,ServiceGroupName,StationBrand
0,D9599391-F121-400E-A587-E1593AA1965A,EA931374-3F82-40A6-92B4-D536C4884E35,8.6957,0.0,8.6957,1.3043,10.0,8.6957,0.0,8.6957,...,NaN,Service Charges 10 SAR,,0.0,1,Cash Customer,99 Mineral Oil NOT used,LaborOnly,PE,PE
1,28D7E7D3-FCD0-439E-B690-C7CA67A576BF,835ADBC8-F892-4B18-8FEC-4B9DD67E7BCC,0.0000,0.0,0.0000,0.0000,0.0,0.0000,0.0,0.0000,...,0.0,Oil Filter Service,,0.0,1,PMS,"Toyota Fortuner GGN 155 &165 5K,15K , 25K ,35K...",LaborAndItems,PE,PE
2,8F250508-C083-4F40-B6C9-EB989754B3C9,BD9AFB1F-411F-4946-846A-CFFA64148774,0.0000,0.0,0.0000,0.0000,0.0,0.0000,0.0,0.0000,...,0.0,Oil Filter Service,,0.0,1,PMS,"Nissan Kicks P15 New 20K,60K, .. K.M",LaborAndItems,PE,PE
3,78893C57-D960-49F5-9930-419E264D96BA,D15F489B-F9B1-4A6D-8412-25BC99F3DFBA,8.6957,0.0,8.6957,1.3043,10.0,8.6957,0.0,8.6957,...,NaN,Service Charges 10 SAR,,0.0,1,Cash Customer,99 Mineral Oil NOT used,LaborOnly,PE,PE
4,ECE39076-C677-4583-9631-1DD60B15E381,9CDDF0CB-1B51-4A1C-A221-95C7FCE1E904,0.0000,0.0,0.0000,0.0000,0.0,0.0000,0.0,0.0000,...,0.0,Parking Brake - Adjust,,0.0,1,PMS,"Altima L34 (2.5L) 10K , 30K ,50K , 70K , 90K …KM",LaborAndItems,PE,PE

In [ ]:
invoice_items_df.iloc[3]

InvoiceID                                  78893C57-D960-49F5-9930-419E264D96BA
InvoiceServiceID                           D15F489B-F9B1-4A6D-8412-25BC99F3DFBA
ServiceBeforeDiscountAmount                                              8.6957
ServiceTotalDiscountAmount                                                  0.0
ServiceBeforeTaxAmount                                                   8.6957
ServiceTaxAmount                                                         1.3043
ServiceTotalAmount                                                         10.0
WithoutExtraServiceBeforeDiscountAmount                                  8.6957
WithoutExtraServiceTotalDiscountAmount                                      0.0
WithoutExtraServiceBeforeTaxAmount                                       8.6957
WithoutExtraServiceTaxAmount                                             1.3043
WithoutExtraServiceTotalAmount                                             10.0
ServiceItemGroupDefaultName                                                None
ServiceItemDefaultName                                                     None
ServiceItemCode                                                            None
ServiceManufacturerDefaultName                                             None
ItemBaseQuantity                                                            NaN
ServiceItemCostAmount                                                       NaN
ItemBeforeDiscountAmount                                                    0.0
ItemTotalDiscountAmount                                                     0.0
ItemBeforeTaxAmount                                                         0.0
ItemTaxAmount                                                               0.0
ItemTotalAmount                                                             0.0
WithoutExtraItemBeforeDiscountAmount                                        0.0
WithoutExtraItemTotalDiscountAmount                                         0.0
WithoutExtraItemBeforeTaxAmount                                             0.0
WithoutExtraItemTaxAmount                                                   0.0
WithoutExtraItemTotalAmount                                                 0.0
ExtraItemBeforeDiscountAmount                                               0.0
ExtraItemTotalDiscountAmount                                                0.0
ExtraItemBeforeTaxAmount                                                    0.0
ExtraItemTaxAmount                                                          0.0
ExtraItemTotalAmount                                                        0.0
InvoiceServiceItemPrice                                                     NaN
ServiceName                                              Service Charges 10 SAR
OilType
ExtraOilQTY                                                                 0.0
OilCustomer                                                                   1
ServicePackageType                                                Cash Customer
ServicePackageName                                      99 Mineral Oil NOT used
ServicePricingType                                                    LaborOnly
ServiceGroupName                                                             PE
StationBrand                                                                 PE
Name: 3, dtype: object

In [ ]:
invoice_items_df.isna().mean()

InvoiceID                                  0.000000
InvoiceServiceID                           0.000000
ServiceBeforeDiscountAmount                0.000000
ServiceTotalDiscountAmount                 0.000000
ServiceBeforeTaxAmount                     0.000000
ServiceTaxAmount                           0.000000
ServiceTotalAmount                         0.000000
WithoutExtraServiceBeforeDiscountAmount    0.000000
WithoutExtraServiceTotalDiscountAmount     0.000000
WithoutExtraServiceBeforeTaxAmount         0.000000
WithoutExtraServiceTaxAmount               0.000000
WithoutExtraServiceTotalAmount             0.000000
ServiceItemGroupDefaultName                0.130160
ServiceItemDefaultName                     0.130160
ServiceItemCode                            0.130160
ServiceManufacturerDefaultName             0.141144
ItemBaseQuantity                           0.130160
ServiceItemCostAmount                      0.130160
ItemBeforeDiscountAmount                   0.000000
ItemTotalDiscountAmount                    0.000000
ItemBeforeTaxAmount                        0.000000
ItemTaxAmount                              0.000000
ItemTotalAmount                            0.000000
WithoutExtraItemBeforeDiscountAmount       0.000000
WithoutExtraItemTotalDiscountAmount        0.000000
WithoutExtraItemBeforeTaxAmount            0.000000
WithoutExtraItemTaxAmount                  0.000000
WithoutExtraItemTotalAmount                0.000000
ExtraItemBeforeDiscountAmount              0.000000
ExtraItemTotalDiscountAmount               0.000000
ExtraItemBeforeTaxAmount                   0.000000
ExtraItemTaxAmount                         0.000000
ExtraItemTotalAmount                       0.000000
InvoiceServiceItemPrice                    0.130160
ServiceName                                0.000000
OilType                                    0.000000
ExtraOilQTY                                0.000000
OilCustomer                                0.000000
ServicePackageType                         0.529198
ServicePackageName                         0.529198
ServicePricingType                         0.000000
ServiceGroupName                           0.000000
StationBrand                               0.000000
dtype: float64

In [ ]:
invoice_items_df["InvoiceID"].nunique(),invoice_items_df["InvoiceServiceID"].nunique(), invoice_items_df.shape

(14921938, 42113450, (44155279, 43))

In [38]:
invoice_df[invoice_df["InvoiceID"].str.lower() == "801802bf-0db3-4b8c-ac24-010197659750"].iloc[0]

InvoiceID                      801802BF-0DB3-4B8C-AC24-010197659750
InvoiceNumber                                          M-1903-15606
ModifiedOn                                      2023-08-12 08:21:05
BranchID                       5065B612-EB63-459E-9AAE-64C3DF03C24A
TransCustomerID                82D1E015-EE13-44DC-B8B8-339F28E1EBBB
CustomerID                     82D1E015-EE13-44DC-B8B8-339F28E1EBBB
CustomerVehicleID              7D6D35D9-4BE9-4009-9E30-19571D3CD3E5
SystemUserID                   7AD9F79A-44F4-4D3B-949B-D5F5911C9301
InvoiceDate                                     2023-08-10 21:58:02
InvoiceDueDate                                  2023-08-10 21:58:02
InvoiceBeforeDiscountAmount                                 166.087
InvoiceDiscountAmount                                           0.0
InvoiceBeforeTaxAmount                                      166.087
InvoiceTaxAmount                                             24.913
InvoiceTotalAmount                                            191.0
InvoiceItemCost                                             52.5959
IsFleet                                                           0
IsPMS                                                             0
CustomerContractID                                             None
CustomerContractType                                           None
WorkOrderNumber                                          1903-15818
WorkOrderStartDate                              2023-08-10 21:22:39
WorkOrderEndDate                                2023-08-10 21:58:02
WorkOrderMileage                                             215253
PreviousMileage                                              211258
PreviousVisitDate                               2023-07-25 09:01:33
NewOrExistingCustomer                             Existing Customer
NewCustomer                                                       0
NewVehicle                                                        0
Warranty                                                          0
PMSID                                                          None
PMSName                                                        None
InvoiceType                                                    Cash
ServiceType                                              PE Service
StationBrand                                                     PE
Name: 16, dtype: object

In [45]:
invoice_items_df[invoice_items_df["InvoiceID"].str.lower() == "801802bf-0db3-4b8c-ac24-010197659750"]

,InvoiceID,InvoiceServiceID,ServiceBeforeDiscountAmount,ServiceTotalDiscountAmount,ServiceBeforeTaxAmount,ServiceTaxAmount,ServiceTotalAmount,WithoutExtraServiceBeforeDiscountAmount,WithoutExtraServiceTotalDiscountAmount,WithoutExtraServiceBeforeTaxAmount,WithoutExtraServiceTaxAmount,WithoutExtraServiceTotalAmount,ServiceItemGroupDefaultName,ServiceItemDefaultName,ServiceItemCode,ServiceManufacturerDefaultName,ItemBaseQuantity,ServiceItemCostAmount,ItemBeforeDiscountAmount,ItemTotalDiscountAmount,ItemBeforeTaxAmount,ItemTaxAmount,ItemTotalAmount,WithoutExtraItemBeforeDiscountAmount,WithoutExtraItemTotalDiscountAmount,WithoutExtraItemBeforeTaxAmount,WithoutExtraItemTaxAmount,WithoutExtraItemTotalAmount,ExtraItemBeforeDiscountAmount,ExtraItemTotalDiscountAmount,ExtraItemBeforeTaxAmount,ExtraItemTaxAmount,ExtraItemTotalAmount,InvoiceServiceItemPrice,ServiceName,OilType,ExtraOilQTY,OilCustomer,ServicePackageType,ServicePackageName,ServicePricingType,ServiceGroupName,StationBrand
4055950,801802BF-0DB3-4B8C-AC24-010197659750,284CDE04-F531-4EF7-B082-33864BA71E7F,10.4348,0.0,10.4348,1.5652,12.0,10.4348,0.0,10.4348,1.5652,12.0,None,None,None,None,NaN,NaN,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,Oil Filter - Customer Own,,0.0,0,None,None,LaborOnly,PE,PE
4057331,801802BF-0DB3-4B8C-AC24-010197659750,8B7C4EB2-8074-4C0A-BBC3-B55235E70A63,15.6522,0.0,15.6522,2.3478,18.0,15.6522,0.0,15.6522,2.3478,18.0,Oil,Petromin Fleet Master LD 15W40 CH4,PETFLEET15W40 -24X1,Petromin,7.0,52.5959,140.0,0.0,140.0,21.0,161.0,80.0,0.0,80.0,12.0,92.0,60.0,0.0,60.0,9.0,69.0,0.0,Engine Oil change,,3.0,1,Cash Customer,Check UP Petromin Oils,LaborOnly,PE,PE
44035404,801802BF-0DB3-4B8C-AC24-010197659750,284CDE04-F531-4EF7-B082-33864BA71E7F,10.4348,0.0,10.4348,1.5652,12.0,10.4348,0.0,10.4348,1.5652,12.0,None,None,None,None,NaN,NaN,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,Oil Filter - Customer Own,,0.0,0,None,None,LaborOnly,PE,PAC
44035405,801802BF-0DB3-4B8C-AC24-010197659750,8B7C4EB2-8074-4C0A-BBC3-B55235E70A63,15.6522,0.0,15.6522,2.3478,18.0,15.6522,0.0,15.6522,2.3478,18.0,Oil,Petromin Fleet Master LD 15W40 CH4,PETFLEET15W40 -24X1,Petromin,7.0,52.5959,140.0,0.0,140.0,21.0,161.0,80.0,0.0,80.0,12.0,92.0,60.0,0.0,60.0,9.0,69.0,0.0,Engine Oil change,,3.0,1,Cash Customer,Check UP Petromin Oils,LaborOnly,PE,PAC

In [50]:
invoice_items_df[invoice_items_df["ServiceItemGroupDefaultName"].isnull()].head()

,InvoiceID,InvoiceServiceID,ServiceBeforeDiscountAmount,ServiceTotalDiscountAmount,ServiceBeforeTaxAmount,ServiceTaxAmount,ServiceTotalAmount,WithoutExtraServiceBeforeDiscountAmount,WithoutExtraServiceTotalDiscountAmount,WithoutExtraServiceBeforeTaxAmount,WithoutExtraServiceTaxAmount,WithoutExtraServiceTotalAmount,ServiceItemGroupDefaultName,ServiceItemDefaultName,ServiceItemCode,ServiceManufacturerDefaultName,ItemBaseQuantity,ServiceItemCostAmount,ItemBeforeDiscountAmount,ItemTotalDiscountAmount,ItemBeforeTaxAmount,ItemTaxAmount,ItemTotalAmount,WithoutExtraItemBeforeDiscountAmount,WithoutExtraItemTotalDiscountAmount,WithoutExtraItemBeforeTaxAmount,WithoutExtraItemTaxAmount,WithoutExtraItemTotalAmount,ExtraItemBeforeDiscountAmount,ExtraItemTotalDiscountAmount,ExtraItemBeforeTaxAmount,ExtraItemTaxAmount,ExtraItemTotalAmount,InvoiceServiceItemPrice,ServiceName,OilType,ExtraOilQTY,OilCustomer,ServicePackageType,ServicePackageName,ServicePricingType,ServiceGroupName,StationBrand
0,D9599391-F121-400E-A587-E1593AA1965A,EA931374-3F82-40A6-92B4-D536C4884E35,8.6957,0.0,8.6957,1.3043,10.0,8.6957,0.0,8.6957,1.3043,10.0,None,None,None,None,NaN,NaN,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,Service Charges 10 SAR,,0.0,1,Cash Customer,99 Mineral Oil NOT used,LaborOnly,PE,PE
3,78893C57-D960-49F5-9930-419E264D96BA,D15F489B-F9B1-4A6D-8412-25BC99F3DFBA,8.6957,0.0,8.6957,1.3043,10.0,8.6957,0.0,8.6957,1.3043,10.0,None,None,None,None,NaN,NaN,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,Service Charges 10 SAR,,0.0,1,Cash Customer,99 Mineral Oil NOT used,LaborOnly,PE,PE
16,E209AEFA-82C8-412D-BC31-91F93C3819F7,2B0966B4-B666-4B1A-A291-D91890F731F8,8.6957,0.0,8.6957,1.3043,10.0,8.6957,0.0,8.6957,1.3043,10.0,None,None,None,None,NaN,NaN,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,Service Charges 10 SAR,,0.0,1,Cash Customer,199 Synthetic Oil,LaborOnly,PE,PE
20,198BFE15-F26A-4B62-8C69-A15AB52BF435,78DCE829-1ACD-406D-89E2-FDB8AF1FF47C,0.0000,0.0,0.0000,0.0000,0.0,0.0000,0.0,0.0000,0.0000,0.0,None,None,None,None,NaN,NaN,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,"Lubricate Locks, Hinges and Latches",,0.0,1,PMS,"Hyundai ELANTRA 1.6L 5k,15k,25k,35k,45k,55k,65...",LaborAndItems,PE,PE
24,0F034381-AEC5-4277-B18B-C1BEFE146EE3,5F57B2E9-E027-4587-A4E4-1D684AC4264F,8.6957,0.0,8.6957,1.3043,10.0,8.6957,0.0,8.6957,1.3043,10.0,None,None,None,None,NaN,NaN,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,Service Charges 10 SAR,,0.0,1,Cash Customer,199 Synthetic Oil,LaborOnly,PE,PE

In [55]:
invoice_df[invoice_df["InvoiceID"] == "198BFE15-F26A-4B62-8C69-A15AB52BF435"]

,InvoiceID,InvoiceNumber,ModifiedOn,BranchID,TransCustomerID,CustomerID,CustomerVehicleID,SystemUserID,InvoiceDate,InvoiceDueDate,InvoiceBeforeDiscountAmount,InvoiceDiscountAmount,InvoiceBeforeTaxAmount,InvoiceTaxAmount,InvoiceTotalAmount,InvoiceItemCost,IsFleet,IsPMS,CustomerContractID,CustomerContractType,WorkOrderNumber,WorkOrderStartDate,WorkOrderEndDate,WorkOrderMileage,PreviousMileage,PreviousVisitDate,NewOrExistingCustomer,NewCustomer,NewVehicle,Warranty,PMSID,PMSName,InvoiceType,ServiceType,StationBrand
176481,198BFE15-F26A-4B62-8C69-A15AB52BF435,M-1072-11244,2023-11-26 18:37:51,01E7599A-E311-45B2-BA7D-15BF3AE149DC,041A5A50-4718-4732-B94E-6DD171DB2535,041A5A50-4718-4732-B94E-6DD171DB2535,E6FCA217-8B2A-40CC-BAB5-A3FEEFCFB485,2D4842CB-9784-4C3C-A57E-0E37D3093BDF,2023-11-26 18:31:33,2023-11-26 18:31:33,303.4783,0.0,303.4783,45.5217,349.0,54.5744,0,1,None,None,1072-11521,2023-11-26 18:01:26,2023-11-26 18:31:33,55860,44652,2023-10-02 10:23:38,Existing Customer,0,0,1,473B1B48-3F64-46BC-969D-A54ED98AB85C,HYUNDAI,Cash,PMS,PE

In [56]:
invoice_items_df[invoice_items_df["InvoiceID"] == "198BFE15-F26A-4B62-8C69-A15AB52BF435"]

,InvoiceID,InvoiceServiceID,ServiceBeforeDiscountAmount,ServiceTotalDiscountAmount,ServiceBeforeTaxAmount,ServiceTaxAmount,ServiceTotalAmount,WithoutExtraServiceBeforeDiscountAmount,WithoutExtraServiceTotalDiscountAmount,WithoutExtraServiceBeforeTaxAmount,WithoutExtraServiceTaxAmount,WithoutExtraServiceTotalAmount,ServiceItemGroupDefaultName,ServiceItemDefaultName,ServiceItemCode,ServiceManufacturerDefaultName,ItemBaseQuantity,ServiceItemCostAmount,ItemBeforeDiscountAmount,ItemTotalDiscountAmount,ItemBeforeTaxAmount,ItemTaxAmount,ItemTotalAmount,WithoutExtraItemBeforeDiscountAmount,WithoutExtraItemTotalDiscountAmount,WithoutExtraItemBeforeTaxAmount,WithoutExtraItemTaxAmount,WithoutExtraItemTotalAmount,ExtraItemBeforeDiscountAmount,ExtraItemTotalDiscountAmount,ExtraItemBeforeTaxAmount,ExtraItemTaxAmount,ExtraItemTotalAmount,InvoiceServiceItemPrice,ServiceName,OilType,ExtraOilQTY,OilCustomer,ServicePackageType,ServicePackageName,ServicePricingType,ServiceGroupName,StationBrand
20,198BFE15-F26A-4B62-8C69-A15AB52BF435,78DCE829-1ACD-406D-89E2-FDB8AF1FF47C,0.0000,0.0,0.0000,0.0000,0.0,0.0000,0.0,0.0000,0.0000,0.0,None,None,None,None,NaN,NaN,0.0000,0.0,0.0000,0.0000,0.0,0.0000,0.0,0.0000,0.0000,0.0,0.0,0.0,0.0,0.0,0.0,NaN,"Lubricate Locks, Hinges and Latches",,0.0,1,PMS,"Hyundai ELANTRA 1.6L 5k,15k,25k,35k,45k,55k,65...",LaborAndItems,PE,PE
100497,198BFE15-F26A-4B62-8C69-A15AB52BF435,B8FA79FB-AB67-4211-BB96-ADF12467D50E,0.0000,0.0,0.0000,0.0000,0.0,0.0000,0.0,0.0000,0.0000,0.0,Hyundai-Oil Filters,Hyundai --- Engine Oil Filter,HYUN 26350-2M000,HYUNDAI,1.0,22.2728,68.6957,0.0,68.6957,10.3043,79.0,68.6957,0.0,68.6957,10.3043,79.0,0.0,0.0,0.0,0.0,0.0,0.0,Oil Filter Service,,0.0,1,PMS,"Hyundai ELANTRA 1.6L 5k,15k,25k,35k,45k,55k,65...",LaborAndItems,PE,PE
356965,198BFE15-F26A-4B62-8C69-A15AB52BF435,79E75D49-2A43-4E9D-9116-8188086E89A5,8.6957,0.0,8.6957,1.3043,10.0,8.6957,0.0,8.6957,1.3043,10.0,Oil Synthetic,Petromin Super Synthetic 5w30 - 1L,PET A-1 SYN,Petromin,4.0,32.3016,226.0870,0.0,226.0870,33.9130,260.0,226.0870,0.0,226.0870,33.9130,260.0,0.0,0.0,0.0,0.0,0.0,0.0,Engine Oil change,,0.0,1,PMS,"Hyundai ELANTRA 1.6L 5k,15k,25k,35k,45k,55k,65...",LaborAndItems,PE,PE

In [54]:
invoice_items_df[invoice_items_df["ServiceItemGroupDefaultName"].isnull()]["ServiceName"].value_counts()

ServiceName
Service Charges 10 SAR                 1990649
Multipoint Inspection                   785727
Lubricate Locks, Hinges and Latches     700041
Filter Installation                     498191
Silver Service Charges                  452268
                                        ...
Grease Service (Large)                       1
Coolant Service                              1
Syarah Headlight Polishing                   1
AC Delco Filters                             1
A/C Leak test Sedan                          1
Name: count, Length: 234, dtype: int64

In [ ]:
service_df = df["ServiceName"].value_counts(100).reset_index()
service_df.head()

                 ServiceName  proportion
0          Engine Oil change    0.309515
1         Oil Filter Service    0.153143
2  Mighty Oil Filter Service    0.068653
3             Top Up Service    0.068398
4     OEM Oil Filter Service    0.053897

In [25]:
service_df["acc"] = service_df["proportion"].cumsum()
service_df.head(10)

                 ServiceName  proportion       acc
0          Engine Oil change    0.309515  0.309515
1         Oil Filter Service    0.153143  0.462659
2  Mighty Oil Filter Service    0.068653  0.531311
3             Top Up Service    0.068398  0.599709
4     OEM Oil Filter Service    0.053897  0.653606
5     Service Charges 10 SAR    0.045083  0.698688
6        Air Filter services    0.032975  0.731663
7                      EXTRA    0.031566  0.763229
8  Cabin Air Filter Services    0.024921  0.788150
9      Multipoint Inspection    0.017795  0.805945

In [27]:
service_agg_df = df.groupby("ServiceName", as_index=False).agg(
    revenue = ("ServiceBeforeTaxAmount", "sum"),
    events = ("ServiceBeforeTaxAmount", "count")
)

service_agg_df["rev_proportion"] = service_agg_df["revenue"] / service_agg_df["revenue"].sum()
service_agg_df["events_proportion"] = service_agg_df["events"] / service_agg_df["events"].sum()

service_agg_df.sort_values("revenue", ascending=False).head(10)

,ServiceName,revenue,events,rev_proportion,events_proportion
116,Engine Oil change,2.298282e+08,13666735,0.561504,0.309515
206,Power Steering Services,3.796786e+07,136240,0.092761,0.003085
262,Transmission Service Small,2.218030e+07,146621,0.054190,0.003321
21,AC Quick Gas Refill Service Small Cars,2.217294e+07,258633,0.054172,0.005857
239,Service Charges 10 SAR,1.728090e+07,1990649,0.042220,0.045083
261,Transmission Service Large,1.174193e+07,204125,0.028687,0.004623
18,AC Quick Gas Refill Service SUV,1.080748e+07,83096,0.026404,0.001882
114,Engine Coolant - Change,1.046923e+07,100610,0.025578,0.002279
79,Differential Service - Rear,8.892180e+06,61994,0.021725,0.001404
243,Silver Service Charges,5.894951e+06,452268,0.014402,0.010243

In [7]:
transactions_grouped_df = pd.read_parquet("../data/01_raw/transactions_origin.parquet", engine="fastparquet")

In [9]:
transactions_grouped_df.columns

Index(['InvoiceID', 'CustomerID', 'CustomerVehicleID', 'BranchID',
       'InvoiceDate', 'ServiceName', 'ServiceItemGroupDefaultName',
       'ServiceItemDefaultName', 'sku', 'IsFleet', 'IsPMS', 'WorkOrderMileage',
       'PreviousMileage', 'NewCustomer', 'NewVehicle', 'Warranty',
       'ItemBaseQuantity', 'ServiceItemCostAmount',
       'InvoiceTotalDiscountAmount', 'InvoiceBeforeTaxAmount',
       'InvoiceTotalAmount', 'InvoiceGrossMargin', 'InvoiceGrossMargin_perc',
       'hasDiscount', 'MileageBetweenVisits', 'MileageBetweenVisits_perc'],
      dtype='object')

In [12]:
service_agg_df = transactions_grouped_df.groupby(["ServiceItemGroupDefaultName", "ServiceName"], as_index=False).agg(
    revenue = ("InvoiceBeforeTaxAmount", "sum"),
    events = ("InvoiceBeforeTaxAmount", "count")
)

service_agg_df["rev_proportion"] = service_agg_df["revenue"] / service_agg_df["revenue"].sum()
service_agg_df["events_proportion"] = service_agg_df["events"] / service_agg_df["events"].sum()

service_agg_df["revenue_rank"] = service_agg_df["revenue"].rank(method="dense", ascending=False)
service_agg_df["events_rank"] = service_agg_df["events"].rank(method="dense", ascending=False)

service_agg_df.sort_values("revenue", ascending=False).head(10)

,ServiceItemGroupDefaultName,ServiceName,revenue,events,rev_proportion,events_proportion,revenue_rank,events_rank
1220,Oil Synthetic,Engine Oil change,1.116351e+09,4708146,0.311318,0.107667,1.0,3.0
1148,Oil,Engine Oil change,9.253666e+08,8871793,0.258058,0.202881,2.0,1.0
125,BATTERIES,Battery Services,1.955690e+08,716904,0.054538,0.016394,3.0,12.0
498,Engine Flush,Engine Flush,1.683930e+08,567163,0.046960,0.012970,4.0,16.0
1205,Oil Filters,Oil Filter Service,1.393917e+08,5198385,0.038872,0.118877,5.0,2.0
268,Cabin Air Filters,Cabin Air Filter Services,8.399908e+07,642546,0.023425,0.014694,6.0,14.0
548,Fuel Injection,Fuel Injection Services,8.293116e+07,294765,0.023127,0.006741,7.0,27.0
1695,Transmission Fluid,Transmission Service Large,6.993501e+07,203803,0.019503,0.004661,8.0,34.0
78,Air Filters,Air Filter services,6.414371e+07,924448,0.017888,0.021140,9.0,9.0
1696,Transmission Fluid,Transmission Service Small,4.982402e+07,145827,0.013894,0.003335,10.0,36.0

In [13]:
service_agg_df.sort_values("revenue", ascending=False).head(30)

,ServiceItemGroupDefaultName,ServiceName,revenue,events,rev_proportion,events_proportion,revenue_rank,events_rank
1220,Oil Synthetic,Engine Oil change,1.116351e+09,4708146,0.311318,0.107667,1.0,3.0
1148,Oil,Engine Oil change,9.253666e+08,8871793,0.258058,0.202881,2.0,1.0
125,BATTERIES,Battery Services,1.955690e+08,716904,0.054538,0.016394,3.0,12.0
498,Engine Flush,Engine Flush,1.683930e+08,567163,0.046960,0.012970,4.0,16.0
1205,Oil Filters,Oil Filter Service,1.393917e+08,5198385,0.038872,0.118877,5.0,2.0
268,Cabin Air Filters,Cabin Air Filter Services,8.399908e+07,642546,0.023425,0.014694,6.0,14.0
548,Fuel Injection,Fuel Injection Services,8.293116e+07,294765,0.023127,0.006741,7.0,27.0
1695,Transmission Fluid,Transmission Service Large,6.993501e+07,203803,0.019503,0.004661,8.0,34.0
78,Air Filters,Air Filter services,6.414371e+07,924448,0.017888,0.021140,9.0,9.0
1696,Transmission Fluid,Transmission Service Small,4.982402e+07,145827,0.013894,0.003335,10.0,36.0
1201,Oil Filters,OEM Oil Filter Service,4.249889e+07,1044044,0.011852,0.023875,11.0,8.0
44,Additives,Power Steering Services,3.795927e+07,135985,0.010586,0.003110,12.0,40.0
1611,Toyota-Oil Filters,OEM Oil Filter Service,3.615088e+07,802523,0.010081,0.018352,13.0,10.0
1200,Oil Filters,Mighty Oil Filter Service,3.021925e+07,3017002,0.008427,0.068993,14.0,4.0
1215,Oil Synthetic,EXTRA,3.005660e+07,394011,0.008382,0.009010,15.0,21.0
1615,Toyota-Oil Filters,Oil Filter Service,2.959914e+07,584831,0.008254,0.013374,16.0,15.0
1550,Toyota-Air Filters,Air Filter services,2.312034e+07,131656,0.006448,0.003011,17.0,42.0
1088,Normal-AC Service,AC Quick Gas Refill Service Small Cars,2.100315e+07,243629,0.005857,0.005571,18.0,28.0
1582,Toyota-Cabin Air Filters,Cabin Air Filter Services,2.083318e+07,135708,0.005810,0.003103,19.0,41.0
1726,Tyres 17 Inch,Tyre Sales 17 Inch,2.056078e+07,19374,0.005734,0.000443,20.0,85.0
414,Coolants,Engine Coolant - Change,1.962031e+07,100374,0.005472,0.002295,21.0,50.0
1143,Oil,EXTRA,1.832422e+07,480375,0.005110,0.010985,22.0,19.0
1458,Service,Service Charges 10 SAR,1.722350e+07,1983672,0.004803,0.045363,23.0,5.0
757,Hyundai-Oil Filters,OEM Oil Filter Service,1.488306e+07,370752,0.004150,0.008478,24.0,22.0
759,Hyundai-Oil Filters,Oil Filter Service,1.438168e+07,353898,0.004011,0.008093,25.0,25.0
1737,Tyres 18 Inch,Tyre Sales 18 Inch,1.275332e+07,9496,0.003557,0.000217,26.0,104.0
732,Hyundai-Cabin Air Filters,Cabin Air Filter Services,1.226992e+07,112687,0.003422,0.002577,27.0,47.0
575,Gear Oil,Differential Service - Rear,1.187452e+07,61115,0.003311,0.001398,28.0,61.0
1713,Tyres 15 Inch,Tyre Sales 15 Inch,1.162354e+07,17887,0.003241,0.000409,29.0,86.0
1720,Tyres 16 Inch,Tyre Sales 16 Inch,1.153635e+07,13505,0.003217,0.000309,30.0,95.0

In [25]:
group_filter = service_agg_df["ServiceItemGroupDefaultName"].str.lower().str.contains("additives")
service_agg_df[group_filter]["ServiceItemGroupDefaultName"].value_counts()

ServiceItemGroupDefaultName
Additives    45
Name: count, dtype: int64