In [1]:
import numpy as np
import pandas as pd

In [2]:
# df = pd.read_parquet("vehicle.parquet", engine="fastparquet")
df = pd.read_parquet("../data/01_raw/raw_vehicles.parquet", engine="fastparquet")

In [3]:
cols = df.columns.values.tolist()
cols.remove("StationBrand")

In [4]:
df.drop_duplicates(subset=cols).shape, df.shape

((7112572, 15), (7112572, 15))

In [5]:
df = df.drop_duplicates(subset=cols)

In [6]:
df["Make"] = df["Make"].str.lower()
df["is_truck"] = df["Make"].str.contains("truck").fillna(False).astype("int")
df["Make"] = (
    df["Make"]
    .str.replace("-", " ")
    .str.replace(".", "")
    .str.replace("cherry", "chery")
    .str.replace("chevorlet", "chevrolet")
    .str.replace("chevrolete", "chevrolet")
    .str.replace("cheverolet", "chevrolet")
    .str.replace("dihatsu", "daihatsu")
    .str.replace("daihatzu", "daihatsu")
    .str.replace("emegrand", "emgrand")
    .str.replace("great wall", "gwm")
    .str.replace("gelly", "geely")
    .str.replace("hino 300", "hino")
    .str.replace("300 hino", "hino")
    .str.replace("hyudai", "hyundai")
    .str.replace("hyundia", "hyundai")
    .str.replace("hundai", "hyundai")
    .str.replace("izusu", "isuzu")
    .str.replace("izuzu", "isuzu")
    .str.replace("infinitiy nissan", "infiniti")
    .str.replace("infinity nissan", "infiniti")
    .str.replace("range rover", "land rover")
    .str.replace("masda", "mazda")
    .str.replace("mazda6", "mazda")
    .str.replace("mazda 6", "mazda")
    .str.replace("mercedez", "mercedes")
    .str.replace("mitshubishi", "mitsubishi")
    .str.replace("mitsubushi", "mitsubishi")
    .str.replace("mitzubishi", "mitsubishi")
    .str.replace("mitsubitshi", "mitsubishi")
    .str.replace("mitsubitsi", "mitsubishi")
    .str.replace("pajero", "mitsubishi")
    .str.replace("nisan", "nissan")
    .str.replace("nissan diesel", "nissan")
    .str.replace("peugeut", "peugeot")
    .str.replace("duster", "renault")
    .str.replace("renult", "renault")
    .str.replace("renualt", "renault")
    .str.replace("ZUSUKI", "suzuki")
    .str.replace("suzuki dzire", "suzuki")
    .str.replace("camry", "toyota")
    .str.replace("toyata", "toyota")
    .str.replace("toyoya", "toyota")
    .str.replace("zxauto", "zx auto")
    .str.replace("benz", "")
    .str.replace("bens", "")
    .str.replace("(china)", "")
    .str.replace("trucks", "")
    .str.rstrip()
    .str.lstrip()
)

/var/folders/3r/sqxygt_d4gs0bc8yhzxh19vw0000gp/T/ipykernel_48832/3053555377.py:2: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df["is_truck"] = df["Make"].str.contains("truck").fillna(False).astype("int")

In [7]:
x = df.Make.value_counts()
x[x > 5000].sum() / x.sum(), x[(x <= 5000) & (x > 1000)].sum() / x.sum()

(0.9877414022154333, 0.006581175635942)

In [77]:
x[x > 5000]

Make
toyota        2232649
hyundai       1200435
nissan         539151
ford           463622
chevrolet      400371
kia            388261
gmc            245361
honda          217447
lexus          213365
mazda          200750
isuzu          128524
mitsubishi     120359
mercury         76904
mercedes        66230
dodge           49093
mg              47095
suzuki          45104
renault         40737
changan         33742
geely           33303
jeep            29615
chrysler        23709
bmw             22272
daihatsu        18747
cadillac        18383
infiniti        17918
volvo           15302
chery           14736
lincoln         13560
peugeot         12299
haval           10246
audi             9569
land rover       9124
volkswagen       9032
gac              5312
porsche          5146
fiat             5036
Name: count, dtype: int64

In [8]:
df["Model"] = df["Model"].str.lower().str.rstrip().str.lstrip()

df["Model"] = (
    df["Model"]
    .str.replace("-", " ")
    .str.replace(".", "")
    .str.replace("mazda3", "3")
    .str.replace("mazda 3", "3")
    .str.replace("mg 5", "5")
    .str.replace("mg 6", "6")
    .str.replace("6 (gl)", "6")
    .str.replace("mazda6", "6")
    .str.replace("mazda 6", "6")
    .str.replace("emgrand7", "7")
    .str.replace("emgrand8", "8")
    .str.replace("accord + coup? v", "accord")
    .str.replace("cr v", "crv")
    .str.replace("camry (asv50)", "camry")
    .str.replace("camry (axvh71)", "camry")
    .str.replace("carry", "camry")
    .str.replace("corola", "corolla")
    .str.replace("corolla im", "corolla")
    .str.replace("corolla (zre171)", "corolla")
    .str.replace("corrola", "corolla")
    .str.replace("corrolla", "corolla")
    .str.replace("mazda cx 5", "cx 5")
    .str.replace("mazda cx 9", "cx 9")
    .str.replace("cx 9 (tc)", "cx 9")
    .str.replace("d max (sa)", "d max")
    .str.replace("d max", "dmax")
    .str.replace("elantra coupe", "elantra")
    .str.replace("elantra gt", "elantra")
    .str.replace("elantra (g4n)", "elantra")
    .str.replace("elantra (g4f)", "elantra")
    .str.replace("elentra", "elantra")
    .str.replace("elantra1", "elantra")
    .str.replace("es 350", "es350")
    .str.replace("es 300", "es300")
    .str.replace("expedition el", "expedition")
    .str.replace("expidetion", "expedition")
    .str.replace("expedetion", "expedition")
    .str.replace("expedation", "expedition")
    .str.replace("explorer i", "explorer")
    .str.replace("expidition", "expedition")
    .str.replace("escalade esv", "escalade")
    .str.rstrip()
    .str.lstrip()
)

df["Model"] = (
    df["Model"]
    .str.replace("f 150", "f150")
    .str.replace("f150 pickup", "f150")
    .str.replace("fotuner", "fortuner")
    .str.replace("fortuner ggn 155 &165", "fortuner")
    .str.replace("fortuner (ggn155,ggn165)", "fortuner")
    .str.replace("fortuner (sa)", "fortuner")
    .str.replace("fortuner (tgn156,tgn166)", "fortuner")
    .str.replace("gs 350", "gs350")
    .str.replace("gs 430", "gs430")
    .str.replace("h 1", "h1")
    .str.replace("hi ace", "hiace")
    .str.replace("hiace (sa)", "hiace")
    .str.replace("hiace (trh201)", "hiace")
    .str.replace("hiace van", "hiace")
    .str.replace("hiace trh 201", "hiace")
    .str.replace("hi lux", "hilux")
    .str.replace("hillux", "hilux")
    .str.replace("hilux (sa)", "hilux")
    .str.replace("hilux (tgn111)", "hilux")
    .str.replace("hilux (tgn121)", "hilux")
    .str.replace("hilux (tgn126)", "hilux")
    .str.replace("hilux (trh201)", "hilux")
    .str.rstrip()
    .str.lstrip()
)

df["Model"] = (
    df["Model"]
    .str.replace("l 200", "l200")
    .str.replace("triton (l200)", "l200")
    .str.replace("landcruiser", "land cruiser")
    .str.replace("land cruiser (urj202)", "land cruiser")
    .str.replace("land crusier", "land cruiser")
    .str.replace("land cruiser (urj200)", "land cruiser")
    .str.replace("land cruiser (sa)", "land cruiser")
    .str.replace("land cruiser / land cruiser prado", "land cruiser prado")
    .str.replace("land cruiser / prado", "land cruiser prado")
    .str.replace("ls 400", "ls400")
    .str.replace("ls 430", "ls430")
    .str.replace("lx 470", "lx470")
    .str.replace("lx 570", "lx570")
    .str.replace("ls 460", "ls460")
    .str.replace("navara (4x4)", "navara")
    .str.replace("navara (d23)", "navara")
    .str.replace("navara (d40)", "navara")
    .str.rstrip()
    .str.lstrip()
)

df["Model"] = (
    df["Model"]
    .str.replace("patrol(y62)", "patrol")
    .str.replace("patrol (y61)", "patrol")
    .str.replace("patrol (y62)", "patrol")
    .str.replace("patrol (y62) (vk56de)", "patrol")
    .str.replace("patrol (vk56de)", "patrol")
    .str.replace("patrol (new)", "patrol")
    .str.replace("patrol new", "patrol")
    .str.replace("patrol gr ii", "patrol")
    .str.replace("patrol safari", "patrol")
    .str.replace("patrol pickup (sa)", "patrol")
    .str.replace("patrol i", "patrol")
    .str.replace("patrol ii", "patrol")
    .str.replace("patrol 4x4", "patrol")
    .str.replace("patrol gr (sa)", "patrol")
    .str.replace("patrol suv (sa)", "patrol")
    .str.replace("patrol platinum", "patrol")
    .str.replace("nissan patrol", "patrol")
    .str.replace("pic up", "pick up")
    .str.replace("rav 4", "rav4")
    .str.replace("santafe", "santa fe")
    .str.replace("santa fe xl", "santa fe")
    .str.replace("sierra 1500 pickup", "sierra 1500")
    .str.replace("sierra 1500 hd", "sierra 1500")
    .str.replace("sierra 2500 pickup", "sierra 2500")
    .str.replace("sierra 2500 hd", "sierra 2500")
    .str.replace("silverado 1500 pickup", "silverado 1500")
    .str.replace("sunny (b15)", "sunny")
    .str.replace("sunny (n17)", "sunny")
    .str.replace("taunus", "taurus")
    .str.replace("taurus x", "taurus")
    .str.replace("tauros", "taurus")
    .str.replace("trail blazer", "trailblazer")
    .str.replace("trailblazer ext", "trailblazer")
    .str.replace("x trail (t31)", "xtrail")
    .str.replace("x trail (t32)", "xtrail")
    .str.replace("x trail", "xtrail")
    .str.replace("yaris i / yaris verso (p1)", "yaris")
    .str.replace("yaris ia", "yaris")
    .str.replace("yaris (ncp151)", "yaris")
    .str.replace("yaris & yaris sedan", "yaris")
    .str.replace("yariz", "yaris")
    .str.replace("^denali$", "yukon denali", regex=True)
    .str.replace("yukon denali xl", "yukon denali")
    .str.replace("yukon xl denali", "yukon denali")
    .str.replace("yukon 1500", "yukon")
    .str.replace("yukon xl 1500", "yukon xl")
    .str.replace("yukon xl 2500", "yukon xl")
    .str.replace("yukonxl", "yukon xl")
    .str.replace("yukon yukon", "yukon")
    .str.replace("mg zs", "zs")
    .str.replace("zst", "zs")
    .str.rstrip()
    .str.lstrip()
)

In [80]:
x = df.Model.value_counts()
x[x > 5000].sum() / x.sum(), x[(x <= 5000) & (x > 1000)].sum() / x.sum()

(0.8728882876959213, 0.061273254652628104)

In [86]:
x[x.index.str.contains("ela")].iloc[0:50]

Model
elantra                             346743
elantra iii (md)                       147
elantra touring                        132
elatra                                 119
range rover velar                      118
elantra (md,ud)                        107
elantra gls                             51
elanta                                  50
elantra ii / elantra tagaz (xd2)        39
tugeela                                 24
elantra yuedong                         23
freelander                              21
elantr                                  20
elantara                                19
elantra 20                              19
zelas                                   19
velaster                                18
elanra                                  17
elamtra                                 16
elantra:avante                          16
elanrta                                 10
tugela                                   9
celario                                  8
elantea                                  8
elantra i40                              7
touring elantra                          7
elantar                                  6
elantra/touring                          6
elantre                                  5
velar                                    4
elantran                                 4
elanatra                                 4
eelantra                                 4
elanntra                                 3
elantra i30                              3
elantraf                                 3
elantra6t1bf9fkxdx468044                 3
pony elantra                             3
delani                                   3
elantra  touring                         3
elantrta                                 3
jumper i (relay)                         2
elanrtra                                 2
celato                                   2
elantra turing                           2
elantra(touring)                         2
elantra 2015                             2
elantra touning                          2
cadelac                                  2
elabntra                                 2
Name: count, dtype: int64

In [88]:
x[x > 3000].tail(50)

Model
cs75              5232
alsvin            5173
terios            5102
s350              5052
cressida          5018
h6                4896
veloster          4882
cx 3              4787
figo              4601
echo              4538
mountaineer       4439
                  4424
range rover       4420
grand i10         4412
grand carnival    4389
safari            4368
eado              4230
ls460l            4138
tiida             4125
sonet             3971
symbol            3932
highlander        3922
silverado 1500    3856
camaro            3746
apv               3711
x terra           3709
previa            3654
partner           3650
outlander         3592
pajero sport      3571
terrain           3516
cs95              3496
xterra            3488
ecosport          3380
baleno            3360
versa             3340
ls400             3317
730li             3305
cx 30             3229
fh12              3223
city              3213
fx35              3211
is350             3203
datsun            3187
inova             3173
mirage            3107
cayenne           3096
jolion            3090
cherokee          3078
challenger        3013
Name: count, dtype: int64

In [182]:
filter_contains = x.reset_index()["Model"].str.contains("co")
x.reset_index()[filter_contains].head(30)

                Model   count
1             corolla  356831
8              accord  162102
134           coaster    5251
176          ecosport    3380
221           compass    2215
228           coolray    2033
325     genesis coupe    1238
339    coolray   sx11    1173
352          colorado    1099
363          corvette    1054
477     corolla cross     660
493            cooper     630
505            escort     610
530             copen     548
558         accord vi     501
615       continental     425
649              eeco     389
695         commander     331
723  accord crosstour     314
748           country     298
761             acord     291
814         discovery     253
845    town & country     238
860          accord i     233
863             coupe     232
900          commuter     215
927              colt     206
928         eco sport     205
936       corolla xli     203
965         econoline     193

In [62]:
x[x <= 100].iloc[0:50]

Model
57s                 100
discovery sport     100
c10                 100
4 tuner             100
mdx                 100
exp                 100
d50                 100
astro van            99
camrey               99
rewarad np           99
lancruiser           99
b50                  99
ga3s                 98
superb               98
grand marquez        98
sierra 2500          98
c3                   98
rx                   98
2004                 98
x trail ii (t31)     97
c65                  97
ranger pickup        97
falcon               97
ct hybrid            97
a250                 97
ghost                96
e55 amg              96
ud series            96
patfinder            96
x2                   96
f pace               96
mg360                96
landcruizer          96
1100                 95
i 290                95
jmc                  95
lumina ltz           95
stafe                95
370 z                95
terius               95
elntra               95
wingle 6             95
venza                95
mrv                  95
crosstour            94
isuzu reward         94
diamante             94
laguna i             94
x9 landwind (sa)     94
jac                  94
Name: count, dtype: int64

In [9]:
maker_map = {
    # Very High
    "porsche": "very_high",
    "lamborghini": "very_high",
    "maserati": "very_high",
    "bmw": "very_high",
    "volvo": "very_high",
    "jaguar": "very_high",
    "mercedez": "very_high",
    "chrysler": "very_high",
    "dodge": "very_high",
    "audi": "very_high",
    # High
    "toyota": "high",
    "byd": "high",
    "honda": "high",
    "lexus": "high",
    "jeep": "high",
    "gmc": "high",
    "lincoln": "high",
    "chevrolet trucks": "high",
    "ford trucks": "high",
    "gmc trucks": "high",
    "lincoln": "high",
    # Medium
    "volkswagen": "medium",
    "chevrolet": "medium",
    "fiat": "medium",
    "ford": "medium",
    "nissan": "medium",
    "mitsubishi": "medium",
    "ford": "medium",
    "mercury": "medium",
    # Low
    "pegout": "low",
    "renault": "low",
    "suzuki": "low",
    "chevrolet": "low",
    "chevrolet": "low",
    # Very Low
    "jac": "very_low",
    "chery": "very_low",
}

In [10]:
df["vehicle_brand_level"] = df["Make"].map(maker_map)
df["vehicle_brand_level"] = df["vehicle_brand_level"].replace(np.nan, "other")

In [11]:
df.head()

,CustomerVehicleID,CreationOn,ModifiedOn,CustomerID,Make,Model,ModelYear,TransmissionType,PMSName,PlateNumber,VIN,IsDriverOwner,StationBrand,is_truck,vehicle_brand_level
0,918FE112-E062-4A56-8033-000001BFCEC6,2021-03-12 00:11:44,2020-03-26 11:55:24,40AA5E88-1966-4494-B3FE-54112BF3F479,chevrolet,suburban,2013.0,Automatic,None,5340AAJ,1GNSC8E07DR219313,False,PE,0,low
1,1B4AA1DD-1E18-4990-AB45-000002BF3307,2021-03-12 00:11:44,2020-03-26 11:55:24,E1EAFA23-0ADC-4AFA-A774-4E27CDA23AA9,lexus,ls400,1998.0,Automatic,TOYOTA,0068LAZ,JTB530F20W0115484,False,PE,0,high
2,8752306B-7FD4-4ABB-8E52-00002A049E37,2021-03-12 00:11:44,2020-03-26 11:55:24,22B51812-64A4-44F1-A5AD-F6850639C800,toyota,hilux,2016.0,Automatic,TOYOTA,8412SBB,MR0HX8CD3G0902343,False,PE,0,high
3,CECB08B1-73B0-44A7-B19F-00002BE80CC8,2021-03-12 00:11:44,2020-03-26 11:55:24,C54F5632-2621-4BD5-8040-6CF1A92BA3DA,hyundai,accent,2009.0,Automatic,HYUNDAI,9261RKA,KMHCM41A89U326551,False,PE,0,other
4,286358CB-BE12-40D8-A428-0000425C16D7,2021-03-12 00:11:44,2020-03-26 11:55:24,7B7E7432-17D1-4F57-BE02-D0CD61CEE722,hyundai,elantra,2017.0,Automatic,HYUNDAI,4470UAD,KMHD741F4HU156825,False,PE,0,other

In [11]:
df["PlateNumber"] = df["PlateNumber"].str.zfill(7)

In [12]:
df["PlateNumber"].str.len().value_counts()

PlateNumber
7     7078274
8       17893
10       5587
9        4223
11       2423
17       1572
12        845
13        804
18        438
16        318
14         87
15         59
20         37
19          4
24          3
25          3
23          2
Name: count, dtype: int64

In [14]:
df.to_parquet("../data/01_raw/raw_vehicles.parquet", engine="fastparquet", index=False) #, mode="overwrite")

In [7]:
df.head()

,CustomerVehicleID,CreationOn,ModifiedOn,CustomerID,Make,Model,ModelYear,TransmissionType,PMSName,PlateNumber,VIN,IsDriverOwner,StationBrand
0,918FE112-E062-4A56-8033-000001BFCEC6,2021-03-12 00:11:44,2020-03-26 11:55:24,40AA5E88-1966-4494-B3FE-54112BF3F479,CHEVROLET,SUBURBAN,2013.0,Automatic,None,5340AAJ,1GNSC8E07DR219313,False,PE
1,1B4AA1DD-1E18-4990-AB45-000002BF3307,2021-03-12 00:11:44,2020-03-26 11:55:24,E1EAFA23-0ADC-4AFA-A774-4E27CDA23AA9,LEXUS,LS400,1998.0,Automatic,TOYOTA,0068LAZ,JTB530F20W0115484,False,PE
2,8752306B-7FD4-4ABB-8E52-00002A049E37,2021-03-12 00:11:44,2020-03-26 11:55:24,22B51812-64A4-44F1-A5AD-F6850639C800,TOYOTA,HILLUX,2016.0,Automatic,TOYOTA,8412SBB,MR0HX8CD3G0902343,False,PE
3,CECB08B1-73B0-44A7-B19F-00002BE80CC8,2021-03-12 00:11:44,2020-03-26 11:55:24,C54F5632-2621-4BD5-8040-6CF1A92BA3DA,HYUNDAI,ACCENT,2009.0,Automatic,HYUNDAI,9261RKA,KMHCM41A89U326551,False,PE
4,286358CB-BE12-40D8-A428-0000425C16D7,2021-03-12 00:11:44,2020-03-26 11:55:24,7B7E7432-17D1-4F57-BE02-D0CD61CEE722,HYUNDAI,Elantra,2017.0,Automatic,HYUNDAI,4470UAD,KMHD741F4HU156825,False,PE

In [8]:
df.isna().mean()

CustomerVehicleID    0.000000e+00
CreationOn           0.000000e+00
ModifiedOn           0.000000e+00
CustomerID           0.000000e+00
Make                 1.863230e-06
Model                1.863230e-06
ModelYear            1.447300e-03
TransmissionType     5.338298e-03
PMSName              3.964958e-01
PlateNumber          0.000000e+00
VIN                  1.433254e-07
IsDriverOwner        0.000000e+00
StationBrand         0.000000e+00
dtype: float64

In [ ]:
filter_owner = df["IsDriverOwner"] == True

0.3351729215807526

In [7]:
df["TransmissionType"].value_counts(100)

TransmissionType
Automatic                                 0.963622
Manual                                    0.031167
 Continous Variable Transmission (CVT)    0.004848
Automated Manual                          0.000206
Dual Clutch                               0.000156
Name: proportion, dtype: float64

In [9]:
df["ModelYear"].value_counts(100).reset_index().head(5)

   ModelYear  proportion
0     2016.0    0.092472
1     2015.0    0.089036
2     2013.0    0.078212
3     2014.0    0.070424
4     2012.0    0.057276

In [10]:
df["ModelYear"].min(), df["ModelYear"].max()

(0.0, 8007.0)

In [30]:
df["Make"] = df["Make"].str.lower()
df["Make"] = df["Make"].str.replace("-", " ").str.replace("benz", "").str.replace("bens", "").str.rstrip().str.lstrip()

In [44]:
df[["Make"]].value_counts().reset_index().head(20) #.to_excel("vehicle_info.xlsx", engine="openpyxl")

                Make    count
0             toyota  2205729
1            hyundai  1184027
2             nissan   528600
3               ford   410314
4                kia   382210
5          chevrolet   354868
6              honda   215895
7              lexus   210911
8              mazda   196827
9                gmc   194212
10             isuzu   123979
11        mitsubishi   117461
12           mercury    76719
13          mercedes    64367
14        gmc trucks    49629
15       ford trucks    48714
16                mg    45089
17             dodge    44459
18            suzuki    42632
19  chevrolet trucks    41564

In [21]:
client_df = df["CustomerID"].value_counts().reset_index()
client_df.head(5)

                             CustomerID  count
0  AA004ADE-01EE-4C59-B621-002A84CB8C18    100
1  6CC22E7C-A0F7-43F4-B383-6A423C449F81     90
2  4411C86D-0AB8-4792-919E-0017496EF0CB     78
3  02EB408F-3036-4D05-BE3E-0026F4429DD5     69
4  B72F62AE-3B64-4151-A8EC-000BC090FE2E     57

In [22]:
client_df.shape

(6971876, 2)

In [27]:
n_clients_gt_0 = client_df[client_df["count"] > 0].shape[0]
n_clients_gt_1 = client_df[client_df["count"] > 1].shape[0]
n_clients_gt_2 = client_df[client_df["count"] > 2].shape[0]
n_clients_gt_10 = client_df[client_df["count"] > 10].shape[0]

print(f"{n_clients_gt_0} has more than 0 car")
print(f"{n_clients_gt_1} has more than 1 car")
print(f"{n_clients_gt_2} has more than 2 car")
print(f"{n_clients_gt_10} has more than 10 car")

6971876 has more than 0 car
29820 has more than 1 car
669 has more than 2 car
117 has more than 10 car