In [1]:
import numpy as np
import pandas as pd

In [18]:
housing_material_df = pd.read_csv('../data/01_raw/census/BuildingMaterialofResidentialHousingbyRegionGovernorateandTypeofHousingCSV.csv')
dependency_ratio_df = pd.read_csv('../data/01_raw/census/DependencyRatioandDependentsbyRegionGovernorateandNationalityCSV.csv')
dwellings_df = pd.read_csv('../data/01_raw/census/DwellingsbyRegionGovernorateandCityCSV.csv')
household_ownership_df = pd.read_csv('../data/01_raw/census/HouseOwnershipbyRegionGovernorateandTypeofHousingCSV.csv')
household_df = pd.read_csv('../data/01_raw/census/HouseholdsbyRegionGovernorateNationalityandGenderofHeadofHouseholdCSV.csv')
household_size_df = pd.read_csv('../data/01_raw/census/HouseholdSizebyRegionGovernorateandNationalityofHeadofHouseholdCSV.csv')
household_members_df = pd.read_csv('../data/01_raw/census/NumberofHouseholdMembersbyRegionGovernorateNationalityandGenderofHeadofHouseholdCSV.csv')
household_rooms_df = pd.read_csv('../data/01_raw/census/NumberofRoomsbyRoomTypeRegionGovernorateandTypeofHousingCSV.csv')
household_type_df = pd.read_csv('../data/01_raw/census/PreferredHousingTypeofHouseholdsbyRegionGovernorateNationalityandGenderofHeadofHouseholdCSV.csv')
household_tenure_df = pd.read_csv('../data/01_raw/census/TenurebyRegionGovernorateandTypeofHousingCSV.csv')

In [19]:
df_list = [
    housing_material_df,
    dwellings_df,
    dependency_ratio_df,
    household_df,
    household_members_df,
    household_rooms_df,
    household_size_df,
    household_tenure_df,
    household_type_df,
    household_ownership_df
]

In [20]:
for df in df_list:
    display(df)

,Building Material,Governorate,Housing Type,Region,Housing Units
0,Block/brick,Al Aqiq,Apartment in a Multi-Story Building,Al Bahah,7
1,Block/brick,Al Aqiq,Apartment in a Traditional House,Al Bahah,135
2,Block/brick,Al Aqiq,Apartment in a Villa,Al Bahah,10
3,Block/brick,Al Aqiq,Floor in a Traditional House,Al Bahah,69
4,Block/brick,Al Aqiq,Floor in a Villa,Al Bahah,15
...,...,...,...,...,...
4772,Stone,Umluj,Apartment in a Multi-Story Building,Tabuk,1
4773,Stone,Umluj,Apartment in a Traditional House,Tabuk,1
4774,Stone,Umluj,Floor in a Traditional House,Tabuk,2
4775,Stone,Umluj,Other,Tabuk,1
4776,Stone,Umluj,Traditional House,Tabuk,20

,"City (5,000+ inhabitants)",Dwelling type,Governorate,Region,Dwellings
0,Abha,Commercial,Abha,Aseer,7575
1,Abha,Other,Abha,Aseer,48260
2,Abha,Public housing,Abha,Aseer,146
3,Abha,Residential,Abha,Aseer,86070
4,Abha,Work camp,Abha,Aseer,27
...,...,...,...,...,...
1938,Zahran Aljanub,Other,Zahran Al Janub,Aseer,4027
1939,Zahran Aljanub,Public housing,Zahran Al Janub,Aseer,34
1940,Zahran Aljanub,Residential,Zahran Al Janub,Aseer,5165
1941,Zahran Aljanub,Work camp,Zahran Al Janub,Aseer,66
1942,Tudo,Tudo,Tudo,Tudo,Tudo

,Governorate,Nationality,Region,Children dependency ratio,Children,Dependency ratio,Elderly dependency ratio,Elderly,Working age
0,Abha,Saudi,Aseer,54.396873,96852,60.842923,6.446051,11477,178047
1,Abha,Non-Saudi,Aseer,6.385807,8070,7.511830,1.126023,1423,126374
2,Abu Arish,Saudi,Jazan,56.790528,48540,63.232404,6.441876,5506,85472
3,Abu Arish,Non-Saudi,Jazan,12.060314,5023,14.149199,2.088886,870,41649
4,Ad Dair,Saudi,Jazan,55.969554,14045,64.106958,8.137403,2042,25094
...,...,...,...,...,...,...,...,...,...
295,Yadamah,Non-Saudi,Najran,3.935860,108,5.357143,1.421283,39,2744
296,Yanbu,Saudi,Al Madinah Al Munawwarah,61.451067,81403,65.946493,4.495425,5955,132468
297,Yanbu,Non-Saudi,Al Madinah Al Munawwarah,8.344214,10672,9.310617,0.966403,1236,127897
298,Zahran Al Janub,Saudi,Aseer,68.336673,9207,75.573369,7.236696,975,13473
299,Zahran Al Janub,Non-Saudi,Aseer,4.132437,332,5.103311,0.970874,78,8034

     Gender Governorate Nationality    Region  Households
0    Female     Al Aqiq       Saudi  Al Bahah        1247
1    Female     Al Aqiq   Non-Saudi  Al Bahah          53
2    Female    Al Bahah       Saudi  Al Bahah        1883
3    Female    Al Bahah   Non-Saudi  Al Bahah         752
4    Female   Al Hajrah       Saudi  Al Bahah         538
..      ...         ...         ...       ...         ...
595    Male       Tabuk   Non-Saudi     Tabuk       50017
596    Male       Tayma       Saudi     Tabuk        4880
597    Male       Tayma   Non-Saudi     Tabuk        3155
598    Male       Umluj       Saudi     Tabuk        8697
599    Male       Umluj   Non-Saudi     Tabuk        5074

[600 rows x 5 columns]

,City 5000+,Gender,Governorate,Household Size (group),Nationality,Region,Households
0,Abha,Female,Abha,1,Saudi,Aseer,2744
1,Abha,Female,Abha,1,Non-Saudi,Aseer,1719
2,Abha,Male,Abha,1,Saudi,Aseer,4358
3,Abha,Male,Abha,1,Non-Saudi,Aseer,11968
4,Abu Ajram,Female,Dawamat Al Jandal,1,Saudi,Al Jawf,4
...,...,...,...,...,...,...,...
16622,Yanbu,Male,Yanbu,10+,Non-Saudi,Al Madinah Al Munawwarah,680
16623,Zahran Aljanub,Female,Zahran Al Janub,10+,Saudi,Aseer,9
16624,Zahran Aljanub,Female,Zahran Al Janub,10+,Non-Saudi,Aseer,3
16625,Zahran Aljanub,Male,Zahran Al Janub,10+,Saudi,Aseer,277
16626,Zahran Aljanub,Male,Zahran Al Janub,10+,Non-Saudi,Aseer,57

,Governorate,Housing Type,Number of Rooms,Region,Room Type,Total of Rooms
0,Al Aqiq,Apartment in a Multi-Story Building,1,Al Bahah,Number of Bathrooms,690
1,Al Aqiq,Apartment in a Multi-Story Building,2,Al Bahah,Number of Bathrooms,1161
2,Al Aqiq,Apartment in a Multi-Story Building,3,Al Bahah,Number of Bathrooms,557
3,Al Aqiq,Apartment in a Multi-Story Building,4,Al Bahah,Number of Bathrooms,51
4,Al Aqiq,Apartment in a Multi-Story Building,5,Al Bahah,Number of Bathrooms,6
...,...,...,...,...,...,...
27089,Umluj,Villa,2,Tabuk,Number of Other rooms,292
27090,Umluj,Villa,3,Tabuk,Number of Other rooms,267
27091,Umluj,Villa,4,Tabuk,Number of Other rooms,131
27092,Umluj,Villa,5,Tabuk,Number of Other rooms,108
27093,Umluj,Villa,6 or More,Tabuk,Number of Other rooms,116

,City,Gender,Governorate,Nationality,Region,Average Household Size
0,Abha,Female,Abha,Non-Saudi,Aseer,1.88
1,Abha,Male,Abha,Non-Saudi,Aseer,2.57
2,Abha,Female,Abha,Saudi,Aseer,3.32
3,Abha,Male,Abha,Saudi,Aseer,4.96
4,Abu Ajram,Female,Dawamat Al Jandal,Non-Saudi,Al Jawf,1.90
...,...,...,...,...,...,...
1996,Zahran Aljanub,Female,Zahran Al Janub,Non-Saudi,Aseer,2.10
1997,Zahran Aljanub,Male,Zahran Al Janub,Non-Saudi,Aseer,2.73
1998,Zahran Aljanub,Female,Zahran Al Janub,Saudi,Aseer,3.62
1999,Zahran Aljanub,Male,Zahran Al Janub,Saudi,Aseer,5.56
2000,Tudo,Tudo,Tudo,Tudo,Tudo,Tudo

,Building Material,Governorate,Nationality,Ownership Subtype,Ownership Type,Region,Type of housing unit,Houses
0,Block/brick,Al Aqiq,Non Saudi,Provided by a Family Member,Housing Provided by,Al Bahah,Apartment in a Multi-Story Building,1
1,Block/brick,Al Aqiq,Non Saudi,Provided by a Family Member,Housing Provided by,Al Bahah,Apartment in a Traditional House,3
2,Block/brick,Al Aqiq,Non Saudi,Provided by a Family Member,Housing Provided by,Al Bahah,Others,1
3,Block/brick,Al Aqiq,Non Saudi,Provided by a Family Member,Housing Provided by,Al Bahah,Traditional House,4
4,Block/brick,Al Aqiq,Saudi,Provided by a Family Member,Housing Provided by,Al Bahah,Apartment in a Traditional House,5
...,...,...,...,...,...,...,...,...
37187,Stone,Umluj,Non Saudi,Rented,Rented,Tabuk,Apartment in a Multi-Story Building,1
37188,Stone,Umluj,Non Saudi,Rented,Rented,Tabuk,Apartment in a Traditional House,1
37189,Stone,Umluj,Non Saudi,Rented,Rented,Tabuk,Floor in a Traditional House,2
37190,Stone,Umluj,Non Saudi,Rented,Rented,Tabuk,Traditional House,4
37191,Stone,Umluj,Saudi,Rented,Rented,Tabuk,Traditional House,1

,Gender,Governorate,Housing Type,Nationality,Region,Housing Units
0,Female,Al Aqiq,Apartment in a Multi-Story Building,Saudi,Al Bahah,319
1,Female,Al Aqiq,Apartment in a Multi-Story Building,Non-Saudi,Al Bahah,19
2,Female,Al Bahah,Apartment in a Multi-Story Building,Saudi,Al Bahah,1145
3,Female,Al Bahah,Apartment in a Multi-Story Building,Non-Saudi,Al Bahah,565
4,Female,Al Hajrah,Apartment in a Multi-Story Building,Saudi,Al Bahah,100
...,...,...,...,...,...,...
4686,Male,Tabuk,Villa,Non-Saudi,Tabuk,1656
4687,Male,Tayma,Villa,Saudi,Tabuk,985
4688,Male,Tayma,Villa,Non-Saudi,Tabuk,89
4689,Male,Umluj,Villa,Saudi,Tabuk,749
4690,Male,Umluj,Villa,Non-Saudi,Tabuk,169

,Building material,Governorate,Ownership Subtype,Ownership type,Region,Type of housing unit,Houses
0,Block/brick,Al Madinah Al Munawwarah,Other,Not Owning a house,Al Madinah Al Munawwarah,Apartment in a Multi-Story Building,1
1,Block/brick,Al Ula,Other,Not Owning a house,Al Madinah Al Munawwarah,Apartment in a Multi-Story Building,1
2,Block/brick,Buraydah,Other,Not Owning a house,Al Qaseem,Apartment in a Multi-Story Building,1
3,Block/brick,Ar Riyadh,Other,Not Owning a house,Ar Riyadh,Apartment in a Multi-Story Building,2
4,Block/brick,Abha,Other,Not Owning a house,Aseer,Apartment in a Multi-Story Building,1
...,...,...,...,...,...,...,...
26361,Stone,Ad Dammam,Mortgage status undefined,Owning a House,Eastern Region,Villa,1
26362,Stone,Ar Riyadh,Owned with Mortgage or Loan,Owning a House,Ar Riyadh,Villa,2
26363,Stone,Al Harjah,Owned without Mortgage or Loan,Owning a House,Aseer,Villa,1
26364,Stone,Al Ahsa,Owned without Mortgage or Loan,Owning a House,Eastern Region,Villa,1
26365,Stone,Al Khafji,Owned without Mortgage or Loan,Owning a House,Eastern Region,Villa,1

In [27]:
household_ownership_df.pivot_table(index="Governorate", values="Houses", columns=["Building material", "Ownership type", "Type of housing unit"], aggfunc="sum")

Building material                            Block/brick  \
Ownership type                        Not Owning a house
Type of housing unit Apartment in a Multi-Story Building
Governorate
Abha                                                26.0
Abu Arish                                           17.0
Ad Dair                                              4.0
Ad Dammam                                           90.0
Ad Darb                                             12.0
...                                                  ...
Wadi Ad Dawasir                                      5.0
Wadi Al Fara                                         NaN
Yadamah                                              1.0
Yanbu                                               30.0
Zahran Al Janub                                      3.0

Building material                                                           \
Ownership type
Type of housing unit Apartment in a Traditional House Apartment in a Villa
Governorate
Abha                                           1256.0                139.0
Abu Arish                                       828.0                 18.0
Ad Dair                                         165.0                  4.0
Ad Dammam                                      1612.0               2144.0
Ad Darb                                         378.0                  9.0
...                                               ...                  ...
Wadi Ad Dawasir                                 583.0                 31.0
Wadi Al Fara                                     21.0                  2.0
Yadamah                                         254.0                  3.0
Yanbu                                           800.0                230.0
Zahran Al Janub                                 183.0                  5.0

Building material                                                           \
Ownership type
Type of housing unit Floor in a Traditional House Floor in a Villa  Others
Governorate
Abha                                        340.0            304.0   547.0
Abu Arish                                   209.0             33.0   278.0
Ad Dair                                      79.0              9.0    78.0
Ad Dammam                                   763.0           1642.0  1733.0
Ad Darb                                     118.0             27.0    83.0
...                                           ...              ...     ...
Wadi Ad Dawasir                             124.0             55.0   358.0
Wadi Al Fara                                 30.0              5.0    23.0
Yadamah                                      23.0              3.0     5.0
Yanbu                                       427.0            215.0   338.0
Zahran Al Janub                              38.0             15.0    70.0

Building material                               \
Ownership type
Type of housing unit Traditional House   Villa
Governorate
Abha                            3374.0   293.0
Abu Arish                       4873.0    89.0
Ad Dair                          574.0     3.0
Ad Dammam                       2672.0  2548.0
Ad Darb                         1951.0    23.0
...                                ...     ...
Wadi Ad Dawasir                 1285.0    78.0
Wadi Al Fara                     992.0     1.0
Yadamah                          517.0     7.0
Yanbu                           3658.0   437.0
Zahran Al Janub                  256.0    17.0

Building material                                         \
Ownership type                            Owning a House
Type of housing unit Apartment in a Multi-Story Building
Governorate
Abha                                                 5.0
Abu Arish                                            3.0
Ad Dair                                              2.0
Ad Dammam                                           23.0
Ad Darb                                              2.0
...                                                  ...
Wadi Ad Dawasir                                      1.0
Wadi Al Fara                                         NaN
Yadamah                                              NaN
Yanbu                                               10.0
Zahran Al Janub                                      1.0

Building material                                      ...              Stone  \
Ownership type                                         ... Not Owning a house
Type of housing unit Apartment in a Traditional House  ...  Traditional House
Governorate                                            ...
Abha                                            165.0  ...              150.0
Abu Arish                                       191.0  ...               51.0
Ad Dair                                          62.0  ...               41.0
Ad Dammam                                       188.0  ...              116.0
Ad Darb                                          56.0  ...               26.0
...                                               ...  ...                ...
Wadi Ad Dawasir                                  94.0  ...               27.0
Wadi Al Fara                                     10.0  ...                5.0
Yadamah                                         108.0  ...                3.0
Yanbu                                           107.0  ...               36.0
Zahran Al Janub                                  22.0  ...               17.0

Building material                                               \
Ownership type                                  Owning a House
Type of housing unit Villa Apartment in a Multi-Story Building
Governorate
Abha                   NaN                                 NaN
Abu Arish              NaN                                 NaN
Ad Dair                NaN                                 NaN
Ad Dammam              5.0                                 NaN
Ad Darb                NaN                                 NaN
...                    ...                                 ...
Wadi Ad Dawasir        NaN                                 NaN
Wadi Al Fara           NaN                                 NaN
Yadamah                NaN                                 NaN
Yanbu                  NaN                                 NaN
Zahran Al Janub        NaN                                 NaN

Building material                                                           \
Ownership type
Type of housing unit Apartment in a Traditional House Apartment in a Villa
Governorate
Abha                                              2.0                  NaN
Abu Arish                                         2.0                  NaN
Ad Dair                                           4.0                  NaN
Ad Dammam                                         8.0                  NaN
Ad Darb                                           1.0                  NaN
...                                               ...                  ...
Wadi Ad Dawasir                                   2.0                  NaN
Wadi Al Fara                                      NaN                  NaN
Yadamah                                           2.0                  NaN
Yanbu                                             NaN                  NaN
Zahran Al Janub                                   5.0                  NaN

Building material                                                          \
Ownership type
Type of housing unit Floor in a Traditional House Floor in a Villa Others
Governorate
Abha                                          2.0              NaN    1.0
Abu Arish                                     4.0              NaN    3.0
Ad Dair                                       6.0              NaN    1.0
Ad Dammam                                    19.0              NaN   22.0
Ad Darb                                       1.0              NaN    2.0
...                                           ...              ...    ...
Wadi Ad Dawasir                               1.0              NaN    1.0
Wadi Al Fara                                  NaN              NaN    2.0
Yadamah                                       NaN              NaN    NaN
Yanbu                                         3.0              NaN    4.0
Zahran Al Janub                               NaN              NaN    NaN

Building material
Ownership type
Type of housing unit Traditional House Villa
Governorate
Abha                              71.0   NaN
Abu Arish                         44.0   NaN
Ad Dair                          143.0   NaN
Ad Dammam                         34.0   1.0
Ad Darb                           38.0   NaN
...                                ...   ...
Wadi Ad Dawasir                    8.0   NaN
Wadi Al Fara                       9.0   NaN
Yadamah                           10.0   NaN
Yanbu                             16.0   NaN
Zahran Al Janub                   35.0   NaN

[150 rows x 79 columns]

In [13]:
household_type_df

,Gender,Governorate,Housing Type,Nationality,Region,Housing Units
0,Female,Al Aqiq,Apartment in a Multi-Story Building,Saudi,Al Bahah,319
1,Female,Al Aqiq,Apartment in a Multi-Story Building,Non-Saudi,Al Bahah,19
2,Female,Al Bahah,Apartment in a Multi-Story Building,Saudi,Al Bahah,1145
3,Female,Al Bahah,Apartment in a Multi-Story Building,Non-Saudi,Al Bahah,565
4,Female,Al Hajrah,Apartment in a Multi-Story Building,Saudi,Al Bahah,100
...,...,...,...,...,...,...
4686,Male,Tabuk,Villa,Non-Saudi,Tabuk,1656
4687,Male,Tayma,Villa,Saudi,Tabuk,985
4688,Male,Tayma,Villa,Non-Saudi,Tabuk,89
4689,Male,Umluj,Villa,Saudi,Tabuk,749
4690,Male,Umluj,Villa,Non-Saudi,Tabuk,169

In [ ]:
hou