In [1]:
import numpy as np
import pandas as pd

In [4]:
df = pd.read_csv("forecast_mileage_model_july.csv")

In [5]:
df.head()

,branch_id,customer_last_transaction_id,mobile,_observ_end_dt,_id,customer_current_mileage,oil_last_mileage,oil_synthetic_last_mileage,customer_last_current_mileage,customer_run_mileage,...,churn_probability,churn_bucket,Month_Wave,Launch Date,is_toyota,is_due_mineral_synthetic,is_on_warranty_period,is_pms_final_flag,active_client,new_waves
0,DD4580FD-2D61-4EDA-84A0-7A51D42F7030,00204AAF-13F0-47D7-BC81-C1ED0629754A,966500028566,2025-07-31,3692GHD__966500028566,NaN,NaN,80606.0,80606.0,NaN,...,0.832862,0.80 - 0.85,June_Wave 2,2025-06-19,0,0,1,0,1,June_Wave 2
1,87DA6475-C20E-4F5C-93B0-F1D2C1643C96,00231F7B-A0D5-4186-A0A9-4B0250D30983,966504504551,2025-07-31,8132LSR__966504504551,NaN,NaN,10247.0,10247.0,NaN,...,0.787670,0.75 - 0.80,June_Wave 2,2025-06-19,0,0,1,0,1,June_Wave 2
2,44ECF8FC-5F0F-404C-B1D4-65BD0FB2E0BC,0029720E-95B2-4E3A-9115-5937D6B6A888,966568615619,2025-07-31,3329JKR__966568615619,NaN,NaN,4047.0,4047.0,NaN,...,0.782642,0.75 - 0.80,April_Wave 3,2025-05-08,1,0,1,0,1,April_Wave 3
3,01D07F68-67A3-42F1-B2E5-694028D89272,002E5276-394A-485B-9A12-91A0953E16B6,966569876340,2025-07-31,7029ZLB__966569876340,NaN,329456.0,NaN,329456.0,NaN,...,0.835211,0.80 - 0.85,June_Wave 2,2025-06-19,1,1,0,0,1,June_Wave 2
4,4C7DD475-F229-4E8B-BE39-B20178383778,00350025-9871-4F69-8786-611D91FC21E1,966536938242,2025-07-31,3445EZJ__966536938242,NaN,335979.0,NaN,335979.0,NaN,...,0.737625,0.70 - 0.75,May_L&G Wave,2025-05-13,1,1,0,0,1,May_L&G Wave

In [ ]:
# CSV 1
### Vehicles Table

# | Field Name | Type | Required | Notes |
# |------------|------|----------|-------|
# | license_plate | VARCHAR(20) | YES | Primary Key |
# | make | VARCHAR(50) | YES | |
# | model | VARCHAR(50) | YES | |
# | year | INTEGER | YES | |
# | vin | VARCHAR(17) | YES | |
# | mileage | INTEGER | YES | |
# | last_service | DATE | YES | |
# | owner | VARCHAR(100) | YES | |
# | picture | VARCHAR(255) | NO | Will use placeholders initially |
# | created_at | TIMESTAMP | YES | Auto-generated |
# | updated_at | TIMESTAMP | YES | Auto-updated |

In [8]:
[col for col in df.columns]

['branch_id',
 'customer_last_transaction_id',
 'mobile',
 '_observ_end_dt',
 '_id',
 'customer_current_mileage',
 'oil_last_mileage',
 'oil_synthetic_last_mileage',
 'customer_last_current_mileage',
 'customer_run_mileage',
 'customer_mileage_per_day',
 'customer_filled_mileage_per_day',
 'customer_avg_mileage_per_day',
 'customer_last_mileage_per_day',
 'oil_last_transaction_dt',
 'oil_synthetic_last_transaction_dt',
 'customer_last_transaction_dt',
 'customer_days_since_last_trx',
 'customer_mileage_delta',
 'customer_mileage_forecast',
 'customer_mileage_last_forecast',
 'delta_last_mineral_oil_change',
 'delta_last_synthetic_oil_change',
 'last_delta_last_mineral_oil_change',
 'last_delta_last_synthetic_oil_change',
 'customer_mineral_oil',
 'customer_synthetic_oil',
 'is_due_mineral_oil',
 'is_due_synthetic_oil',
 'floor_last_delta_last_mineral_oil_change',
 'floor_delta_last_mineral_oil_change',
 'nationality',
 'maker',
 'model',
 'model_year',
 'month_avg_mileage_per_day_mean_past_11_next_0_months',
 'month_net_sales',
 'month_distinct_transactions',
 'pms_month_net_sales',
 'pms_month_distinct_transactions',
 'promo_month_net_sales',
 'promo_month_distinct_transactions',
 'all_packages',
 'first_visit_dt',
 'months_since_first_visit',
 'months_since_last_visit',
 'total_number_of_visits',
 'total_number_of_promo_visits',
 'total_number_of_pms_visits',
 'total_number_of_visits_last_12_months',
 'total_number_of_promo_visits_last_12_months',
 'total_number_of_pms_visits_last_12_months',
 'total_revenue',
 'total_promo_revenue',
 'total_pms_revenue',
 'total_revenue_last_12_months',
 'total_promo_revenue_last_12_months',
 'total_pms_revenue_last_12_months',
 'expected_number_of_visits_mineral_oil',
 'expected_number_of_visits_synthetic_oil',
 'is_new_joiner',
 'is_loyal',
 'is_potential_loyal',
 'is_uncommited',
 'is_lost',
 'is_gone',
 'is_promo_hunter',
 'is_full_price',
 'is_mixed_price',
 'is_due_cabin_ac_filter',
 'is_due_air_filter',
 'is_due_fuel_additive',
 'is_due_brake_fluid',
 'is_due_coolant',
 'is_due_differential_oil',
 'is_due_fuel_filter',
 'is_due_spark_plugs',
 'is_due_atf',
 'is_due_cvt_oil',
 'is_due_drive_belt',
 'is_due_canister',
 'is_due_timing_belt',
 'is_due_power_steering_pump_belt',
 'is_due_atf_filter',
 'is_due_pms',
 'is_due_tires',
 'is_due_engine_flush',
 'is_due_battery',
 'is_due_ac_services',
 'is_due_headlight_polishing',
 'is_due_suspension',
 'expected_revenue_cabin_ac_filter',
 'expected_revenue_air_filter',
 'expected_revenue_fuel_additive',
 'expected_revenue_brake_fluid',
 'expected_revenue_coolant',
 'expected_revenue_differential_oil',
 'expected_revenue_fuel_filter',
 'expected_revenue_spark_plugs',
 'expected_revenue_atf',
 'expected_revenue_cvt_oil',
 'expected_revenue_drive_belt',
 'expected_revenue_canister',
 'expected_revenue_timing_belt',
 'expected_revenue_power_steering_pump_belt',
 'expected_revenue_atf_filter',
 'expected_revenue_pms',
 'expected_revenue_tires',
 'expected_revenue_engine_flush',
 'expected_revenue_battery',
 'expected_revenue_ac_services',
 'expected_revenue_headlight_polishing',
 'expected_revenue_suspension',
 'expected_revenue_mineral_oil',
 'expected_revenue_synthetic_oil',
 'is_due_PE',
 'is_due_PAC',
 'expected_revenue_PE',
 'expected_revenue_PAC',
 'monthly_expected_revenue',
 'city',
 'is_pac_city',
 'reference_digits',
 'campaign_group',
 'mobile_total_number_of_visits',
 'mobile_total_number_of_promo_visits',
 'mobile_total_number_of_pms_visits',
 'mobile_total_number_of_visits_last_12_months',
 'mobile_total_number_of_promo_visits_last_12_months',
 'mobile_total_number_of_pms_visits_last_12_months',
 'mobile_total_revenue',
 'mobile_total_promo_revenue',
 'mobile_total_pms_revenue',
 'mobile_total_revenue_last_12_months',
 'mobile_total_promo_revenue_last_12_months',
 'mobile_total_pms_revenue_last_12_months',
 'mobile_last_transaction_dt',
 'mobile_highest_revenue',
 'is_highest_revenue_car',
 'customer_mileage_forecast_bucket',
 'customer_mileage_last_forecast_bucket',
 'crossing_10k_threshold',
 'is_due',
 'preferred_language',
 'is_chinese_brand',
 'last_promo',
 'branch_code',
 'ratio_pms_total_visits_last_12_months',
 'car_age',
 'loyalty_segment',
 'price_segment',
 'decile',
 'ratio_pms_total_visits_last_12_months_bucket',
 'car_age_bucket',
 'is_station_closed',
 'mpd_bucket',
 'churn_probability',
 'churn_bucket',
 'Month_Wave',
 'Launch Date',
 'is_toyota',
 'is_due_mineral_synthetic',
 'is_on_warranty_period',
 'is_pms_final_flag',
 'active_client',
 'new_waves']

In [11]:
df["customer_current_mileage"].isna()

0          True
1          True
2          True
3          True
4          True
           ...
1022989    True
1022990    True
1022991    True
1022992    True
1022993    True
Name: customer_current_mileage, Length: 1022994, dtype: bool

In [20]:
df["plate_number"] = df["_id"].str.split("__", expand=True)[0]
df["vin_code"] = "NONE"
df["owner"] = "NONE"

In [21]:
vehicles_cols = [
    "plate_number",
    "maker",
    "model",
    "model_year",
    "vin_code",
    "customer_last_current_mileage",
    "customer_last_transaction_dt",
    "owner",
]

In [22]:
vehicles_table = df[vehicles_cols]
vehicles_table.head()

,plate_number,maker,model,model_year,vin_code,customer_last_current_mileage,customer_last_transaction_dt,owner
0,3692GHD,CHANGAN,CS95,2021.0,NONE,80606.0,2024-10-02 10:50:16,NONE
1,8132LSR,KIA,PEGAS,2023.0,NONE,10247.0,2024-09-10 17:11:18,NONE
2,3329JKR,TOYOTA,URBAN CRUISER,2024.0,NONE,4047.0,2024-11-15 17:56:22,NONE
3,7029ZLB,TOYOTA,RAV4,2012.0,NONE,329456.0,2025-01-07 12:52:28,NONE
4,3445EZJ,TOYOTA,FORTUNER,2015.0,NONE,335979.0,2025-05-20 22:50:25,NONE

In [24]:
vehicles_table.to_csv("webapp_data/vehicles_table.csv", index=False, header=True)

In [ ]:
# CSV 2
### Services Table

# | Field Name | Type | Required | Notes |
# |------------|------|----------|-------|
# | id | VARCHAR(36) | YES | Primary Key |
# | service | VARCHAR(100) | YES | |
# | priority | VARCHAR(10) | YES | Values: 'high', 'medium', 'low' |
# | interval_miles | INTEGER | YES | Consolidated field (replaces due_at_miles and interval_miles) |
# | description | TEXT | YES | |
# | estimated_cost | VARCHAR(50) | YES | |
# | oem | BOOLEAN | YES | |
# | service_type | VARCHAR(20) | YES | |
# | created_at | TIMESTAMP | YES | Auto-generated |
# | updated_at | TIMESTAMP | YES | Auto-updated |

In [25]:
services_df = pd.read_csv("Servicing Rules.csv")
services_df.head()

  category          product      TP mileages car brand car model servicing BU
0      OEM  Cabin AC Filter  141.38   20,000    TOYOTA       All           PE
1      OEM       Air Filter  111.45   40,000    TOYOTA       All           PE
2      OEM    Fuel Additive   63.44   10,000    TOYOTA       All           PE
3      OEM      Brake Fluid   65.00   40,000    TOYOTA       All          PAC
4      OEM          Coolant  232.18   80,000    TOYOTA       All           PE

In [31]:
import uuid

uuid_list = [str(uuid.uuid4()) for id in range(services_df.shape[0])]

In [76]:
services_df["id"] = uuid_list
services_df["oem"] = np.where(services_df["category"] == "OEM", True, False)
services_df["priority"] = np.where(services_df["category"] == "OEM", "high", "medium")
services_df["service"] = services_df["product"].str.lower()
services_df["estimated_cost"] = services_df["TP"]
services_df["interval_miles"] = services_df["mileages"]
services_df["maker"] = services_df["car brand"].str.upper()
services_df["model"] = services_df["car model"].str.upper()
services_df["description"] = 'None'
services_df["service_type"] = 'None'

In [77]:
services_table_cols = [
    "id",
    "service",
    "priority",
    "interval_miles",
    "description",
    "estimated_cost",
    "oem",
    "service_type",
    "maker",
    "model",
]

services_table = services_df[services_table_cols]
services_table.to_csv("webapp_data/service_table.csv", index=False, header=True)

In [38]:
cols = [col for col in df.columns if "is_due_" in col]
cols

['is_due_mineral_oil',
 'is_due_synthetic_oil',
 'is_due_cabin_ac_filter',
 'is_due_air_filter',
 'is_due_fuel_additive',
 'is_due_brake_fluid',
 'is_due_coolant',
 'is_due_differential_oil',
 'is_due_fuel_filter',
 'is_due_spark_plugs',
 'is_due_atf',
 'is_due_cvt_oil',
 'is_due_drive_belt',
 'is_due_canister',
 'is_due_timing_belt',
 'is_due_power_steering_pump_belt',
 'is_due_atf_filter',
 'is_due_pms',
 'is_due_tires',
 'is_due_engine_flush',
 'is_due_battery',
 'is_due_ac_services',
 'is_due_headlight_polishing',
 'is_due_suspension',
 'is_due_PE',
 'is_due_PAC',
 'is_due_mineral_synthetic']

In [52]:
service_plate_table = pd.melt(df[["plate_number", "maker", "model"] + cols], id_vars=["plate_number", "maker", "model"], value_vars=cols, var_name="service")
service_plate_table["service"] = service_plate_table["service"].astype(str).str.split("is_due_", expand=True)[1]
service_plate_table["service"] = service_plate_table["service"].str.replace("_", " ")
service_plate_table

         plate_number    maker           model            service  value
0             3692GHD  CHANGAN            CS95        mineral oil      0
1             8132LSR      KIA           PEGAS        mineral oil      0
2             3329JKR   TOYOTA   URBAN CRUISER        mineral oil      0
3             7029ZLB   TOYOTA            RAV4        mineral oil      1
4             3445EZJ   TOYOTA        FORTUNER        mineral oil      1
...               ...      ...             ...                ...    ...
27620833      4651ZJR   TOYOTA         COROLLA  mineral synthetic      0
27620834      6125ERD  HYUNDAI          SONATA  mineral synthetic      0
27620835      9606XKR   NISSAN           SUNNY  mineral synthetic      0
27620836      5588SBJ   TOYOTA          INNOVA  mineral synthetic      1
27620837      6993XDR    GEELY  COOLRAY   SX11  mineral synthetic      1

[27620838 rows x 5 columns]

In [ ]:
x = pd.merge(
    service_plate_table,
    services_table,
    on=["id"],
    how="inner"
)
x.shape, services_table.shape, service_plate_table.shape

((6652981, 13), (125, 10), (27620838, 5))

In [121]:
print(row.to_string())

plate_number            8132LSR
maker                       KIA
model                     PEGAS
service         cabin ac filter
value                         0

In [145]:
service_plate_table["service"].value_counts()

service
mineral oil                 1022994
timing belt                 1022994
PAC                         1022994
PE                          1022994
suspension                  1022994
headlight polishing         1022994
ac services                 1022994
battery                     1022994
engine flush                1022994
tires                       1022994
pms                         1022994
atf filter                  1022994
power steering pump belt    1022994
canister                    1022994
synthetic oil               1022994
drive belt                  1022994
cvt oil                     1022994
atf                         1022994
spark plugs                 1022994
fuel filter                 1022994
differential oil            1022994
coolant                     1022994
brake fluid                 1022994
fuel additive               1022994
air filter                  1022994
cabin ac filter             1022994
mineral synthetic           1022994
Name: count, dtype: int64

In [149]:
def get_id(row, services_table):
    row_service = row["service"].upper()
    row_maker = str(row["maker"]).upper()
    row_model = str(row["model"]).upper()

    if row_service in ["PE", "PAC", "MINERAL SYNTHETIC"]:
        return None

    filter_service = services_table["service"].str.upper() == row_service
    filtered_services_table = services_table[filter_service]
    id = None
    if filtered_services_table.shape[0] == 1:
        id = filtered_services_table["id"].values[0]
    elif filtered_services_table.shape[0] > 1:
        if row_model in services_table[filter_service]["model"].str.upper().to_list():
            filter_model = services_table["model"].str.upper() == row_model
            filters = filter_service & filter_model
            filtered_services_table = services_table[filters]

            try:
                id = filtered_services_table["id"].values[0]
            except:
                print(row.to_string())
                raise

        else:
            row_model = "ALL"
            if row_maker not in services_table[filter]["maker"].str.upper().to_list():
                row_maker = "ALL"

            filter_maker = services_table["maker"].str.upper() == row_maker
            filters = filter_service & filter_maker
            filtered_services_table = services_table[filters]
            if filtered_services_table.shape[0] == 1:
                id = filtered_services_table["id"].values[0]
    else:
        print(row.to_string())
        raise ValueError("Service not found!")


    return id

In [113]:
service_plate_table.head()

  plate_number    maker          model      service  value
0      3692GHD  CHANGAN           CS95  mineral oil      0
1      8132LSR      KIA          PEGAS  mineral oil      0
2      3329JKR   TOYOTA  URBAN CRUISER  mineral oil      0
3      7029ZLB   TOYOTA           RAV4  mineral oil      1
4      3445EZJ   TOYOTA       FORTUNER  mineral oil      1

In [115]:
service_plate_table.shape, service_plate_table[service_plate_table["value"] > 0].shape

((27620838, 5), (2542055, 5))

In [126]:
service_plate_table["id"] = None

In [150]:
service_plate_table.loc[service_plate_table["value"] > 0, "id"] = service_plate_table[service_plate_table["value"] > 0].apply(get_id, axis=1, services_table=services_table)

In [151]:
service_plate_table.to_csv("webapp_data/service_plate_table.csv", index=False, header=True)

In [141]:
row = service_plate_table.loc[8186336]
get_id(row, services_table)

False

'e05c693c-0b8a-445a-ad6a-b789abb0a0ad'

In [ ]:
plate_number        3849JED
maker                 HAVAL
model                    H9
service         fuel filter
value                     1
id                     None

In [130]:
services_table[services_table["service"] == "fuel filter"]

,id,service,priority,interval_miles,description,estimated_cost,oem,service_type,maker,model
6,18171d30-18cf-4cdd-93be-3379956b1672,fuel filter,high,"80,000",None,100.0,True,None,TOYOTA,ALL
17,fb36a4ea-ddd0-421c-aa6c-0fe24a0c0c17,fuel filter,high,"60,000",None,100.0,True,None,HYUNDAI,ALL
26,e283585f-0f28-43a7-9bb8-df7421ba6318,fuel filter,high,"30,000",None,100.0,True,None,GEELY,ALL
36,84a667b7-dfa1-495d-92fb-fd961c6a8dcb,fuel filter,high,"60,000",None,100.0,True,None,KIA,ALL
46,5af0693d-3eee-4c32-9bf9-9c55c3ae5266,fuel filter,high,"60,000",None,100.0,True,None,MAZDA,ALL
59,80120e33-2316-426b-b70d-f0d35bb6501b,fuel filter,high,"60,000",None,100.0,True,None,MG,ALL
87,e05c693c-0b8a-445a-ad6a-b789abb0a0ad,fuel filter,high,"20,000",None,100.0,True,None,HAVAL,ALL
105,718f6754-c6f1-4c9d-be16-97ec6aa8c2a8,fuel filter,high,"45,000",None,100.0,True,None,CHANGAN,ALL
106,3c2a4419-f87e-4eac-803c-11de8bf2afec,fuel filter,high,"85,000",None,100.0,True,None,CHANGAN,ALL

In [94]:
row_service = row["service"].upper()
row_maker = row["maker"].upper()
row_model = row["model"].upper()

In [99]:
services_table[filter]["maker"].str.upper().to_list()

['TOYOTA',
 'HYUNDAI',
 'GEELY',
 'KIA',
 'MAZDA',
 'MG',
 'HAVAL',
 'HAVAL',
 'HAVAL',
 'HAVAL',
 'HAVAL',
 'CHANGAN',
 'NISSAN']

In [93]:
filter = services_table["service"].str.upper() == row_service
services_table[filter]

,id,service,priority,interval_miles,description,estimated_cost,oem,service_type,maker,model
0,aa0aadb4-bd09-4e6d-ae10-6f0015aede05,cabin ac filter,high,"20,000",None,141.38,True,None,TOYOTA,ALL
11,9b28ec8c-8028-4a75-a332-b3fa07136952,cabin ac filter,high,"10,000",None,141.38,True,None,HYUNDAI,ALL
21,67f34833-83ca-44ab-a206-c0a06d184035,cabin ac filter,high,"10,000",None,141.38,True,None,GEELY,ALL
30,7033e27b-961a-4b90-a722-8c890b0ace26,cabin ac filter,high,"20,000",None,141.38,True,None,KIA,ALL
40,cfbc3bc2-e9f1-42a5-93a8-668257191560,cabin ac filter,high,"20,000",None,141.38,True,None,MAZDA,ALL
54,39120f52-849a-4aa2-b787-d9af7d158fe3,cabin ac filter,high,"20,000",None,141.38,True,None,MG,ALL
64,285e6f04-6ce6-476c-a5b7-a18e54c71420,cabin ac filter,high,"12,500",None,141.38,True,None,HAVAL,H6 III
65,957e9531-fd8b-46a5-9244-f03102903e26,cabin ac filter,high,"12,500",None,141.38,True,None,HAVAL,JOILION
66,13f81b11-5a97-42c0-b6f4-943c9d6fc91b,cabin ac filter,high,"20,000",None,141.38,True,None,HAVAL,H9
67,63ec2571-58ca-48a8-ac76-f58e796fbe6f,cabin ac filter,high,"20,000",None,141.38,True,None,HAVAL,H6 II
68,39fd29a5-7972-41d0-a144-6b1cebfb06b7,cabin ac filter,high,"20,000",None,141.38,True,None,HAVAL,H2
99,756104a8-c813-485a-bed2-7c139212e69f,cabin ac filter,high,"10,000",None,141.38,True,None,CHANGAN,ALL
112,7da9af3f-efd7-4859-941c-4ff0a3be5196,cabin ac filter,high,"10,000",None,141.38,True,None,NISSAN,ALL

In [84]:
services_table.head()

,id,service,priority,interval_miles,description,estimated_cost,oem,service_type,maker,model
0,aa0aadb4-bd09-4e6d-ae10-6f0015aede05,cabin ac filter,high,"20,000",None,141.38,True,None,TOYOTA,ALL
1,594973ed-a91e-472a-9fac-12e9f9733203,air filter,high,"40,000",None,111.45,True,None,TOYOTA,ALL
2,2b7c764a-e501-4142-ad3b-b5a27138d8de,fuel additive,high,"10,000",None,63.44,True,None,TOYOTA,ALL
3,d1c2ed92-4699-4cba-abb6-49b63b8cad6f,brake fluid,high,"40,000",None,65.00,True,None,TOYOTA,ALL
4,26cf35b7-6d99-4bc1-9413-6a7dae79347f,coolant,high,"80,000",None,232.18,True,None,TOYOTA,ALL

In [78]:
services_table["maker"].value_counts()

maker
HAVAL      35
MAZDA      14
CHANGAN    13
TOYOTA     11
HYUNDAI    10
KIA        10
MG         10
GEELY       9
ALL         9
NISSAN      4
Name: count, dtype: int64

In [70]:
services_table[["service", "maker", "model"]].head()

           service   maker model
0  cabin ac filter  TOYOTA   All
1       air filter  TOYOTA   All
2    fuel additive  TOYOTA   All
3      brake fluid  TOYOTA   All
4          coolant  TOYOTA   All