In [3]:
import numpy as np
import pandas as pd

In [11]:
target_list = pd.read_csv("06.JuneTargetList_withChurn_v8.csv")
# PACPE_df = pd.read_parquet("all_targetlists_performance_analysis_PACPE_v8.parquet")
PACPE_df = pd.read_csv("all_targetlists_performance_analysis_PACPE_v8.csv")

/var/folders/3r/sqxygt_d4gs0bc8yhzxh19vw0000gp/T/ipykernel_33396/3141560897.py:3: DtypeWarning: Columns (1,2,3,4,5,7,12,13,14,16,17,18,19,20,21,24,25,26,27,28,30,31,47,48,56,63) have mixed types. Specify dtype option on import or set low_memory=False.
  PACPE_df = pd.read_csv("all_targetlists_performance_analysis_PACPE_v8.csv")

In [5]:
target_list.head()

,Mobile,PlateNumber,MobileLastDigit,TotalHistoricalVisit,TotalNetAmount,TotalGrossProfit,TotalOilVisits,TotalNetOilAmount,TotalPMSVisits,TotalNetPMSAmount,...,EngineFlush_Revenue,Suspension_Revenue,ACServices_Revenue,ACRepair_Revenue,HeadlightPolish_Revenue,Services_Total_Rev,LastOdometer_bucket,LastOdometer_bucket_v2,Car Brand,isDueConcat2
0,966505420537,7932BUB,7,1,68.7000,47.48400,1,68.7000,0,0.0,...,0.0,0.0,102.56,0,81.82,184.38,490000 - 500000,150k and above,TOYOTA,"DueACServicesFlag, DueHeadlightPolishFlag"
1,966505420572,2803UKR,2,1,408.0000,401.21737,0,0.0000,1,408.0,...,0.0,0.0,0.00,0,0.00,430.00,0 - 10000,upto 10000,NISSAN,NaN
2,966505420660,9304DBD,0,1,119.1304,112.67760,1,119.1304,0,0.0,...,0.0,0.0,0.00,0,0.00,0.00,50000 - 60000,upto 60000,HYUNDAI,NaN
3,966500001031,5880RVJ,1,4,1709.5652,1675.93400,4,1709.5652,0,0.0,...,0.0,0.0,0.00,0,0.00,0.00,80000 - 90000,upto 90000,FORD,NaN
4,966500001061,0800NGA,1,5,1652.1739,1598.03390,5,1652.1739,0,0.0,...,0.0,0.0,0.00,0,0.00,0.00,310000 - 320000,150k and above,TOYOTA,NaN

In [12]:
PACPE_df.head()

,Mobile,PlateNumber,Make,Model,Nationality,PreferredLanguage,IsPromoHunter,CampaignName,Month,Wave,...,READ_flag,FAILED_flag,Conversion_Date_PAC,Total_Revenue_PAC,Total_Invoices_PAC,Is_Conversion_Before_End_PAC,delta_days_PAC,Att_Total_Revenue_PAC,Att_Invoices_PAC,delta_week_bucket_pac
0,5.521212e+10,NaN,HYUNDAI,ELANTRA,NaN,NaN,1,acbundle_ar,April,Wave 1,...,0,0,NaN,0.0,0.0,1.0,NaN,0.0,0,NaN
1,9.660501e+11,NaN,FORD,TAURUS,NaN,NaN,1,acbundle_ar,April,Wave 1,...,0,0,NaN,0.0,0.0,1.0,NaN,0.0,0,NaN
2,9.660505e+11,NaN,LEXUS,LS 460,NaN,NaN,1,acbundle_ar,April,Wave 1,...,0,0,NaN,0.0,0.0,1.0,NaN,0.0,0,NaN
3,9.660540e+11,NaN,TOYOTA,YARIS,NaN,NaN,1,acbundle_ar,April,Wave 1,...,0,0,NaN,0.0,0.0,1.0,NaN,0.0,0,NaN
4,9.660544e+11,NaN,HYUNDAI,Accent,NaN,NaN,1,acbundle_ar,April,Wave 1,...,0,0,NaN,0.0,0.0,1.0,NaN,0.0,0,NaN

In [13]:
PACPE_df.columns

Index(['Mobile', 'PlateNumber', 'Make', 'Model', 'Nationality',
       'PreferredLanguage', 'IsPromoHunter', 'CampaignName', 'Month', 'Wave',
       'Launch Date', 'Group_New', 'Offer_New', 'Segment_New', 'Product_New',
       'HasControl?', 'campaigns', 'SENT', 'DELIVERED', 'READ', 'FAILED',
       'Campaign', 'Churn_Probability_vf', 'PriceCohort', 'RecencyCohort',
       'Segment', 'Visit_Frequency', 'churn_bucket', 'Codes', 'Filename',
       'End Date', 'Conversion_Date', 'Total_Revenue_Non_Oil',
       'Total_Revenue_Oil', 'Total_Revenue_Others', 'Total_Revenue_PMS',
       'Total_Invoices_Non_Oil', 'Total_Invoices_Oil', 'Total_Invoices_Others',
       'Total_Invoices_PMS', 'Total_Unique_Invoices', 'Total Revenue',
       'Is_Conversion_Before_End', 'delta days', 'constant', 'HasEndDate?',
       'Concat', 'delta_week_bucket', 'conversion month', 'conversion year',
       'Att_Total_Revenue', 'Att_Invoices', 'SENT_flag', 'DELIVERED_flag',
       'READ_flag', 'FAILED_flag', 'Conversion_Date_PAC', 'Total_Revenue_PAC',
       'Total_Invoices_PAC', 'Is_Conversion_Before_End_PAC', 'delta_days_PAC',
       'Att_Total_Revenue_PAC', 'Att_Invoices_PAC', 'delta_week_bucket_pac'],
      dtype='object')

In [14]:
PACPE_df["Segment_New"].value_counts()

Segment_New
Lost and Gone            1608032
Multiple                  988971
Uncommitted               639557
Potential Loyal           545636
Loyal                     295416
New Joiner                224341
Outliers                  211847
Uncommitted Customers     105093
New Joiners                75795
PotentialLoyal             60809
Lost & Gone                54767
Outlier                    42733
Name: count, dtype: int64

In [15]:
PACPE_df["Segment_New"].isna().sum()

30031